### PR TITLE
Removed RSA to have a consistent use of elliptic curve crypto.

### PR DESCRIPTION
**Pull request by thkzrl**
Encryption enrollment certificates now use EC, replacing RSA and thereby having a consistent use of EC crypto in OBC.

Signed-off by: Thorsten Kramp thk@zurich.ibm.com

### CODE REVIEW

**Comment by thkzrl** [comment]
Signed-off-by: Thorsten Kramp thk@zurich.ibm.com

**Comment by thkzrl** [comment]
Allowed logging levels to be turned on/off via yaml settings.

**Comment by adecaro** [comment]
@thkzrl "golang.org/x/crypto/hkdf" is missing from the vendor folder and obc-peer doesn't compile inside vagrant. May you add the dependency using govendor following the instructions specified here https://github.com/openblockchain/obc-peer#adding-or-updating-a-go-packages ?

Thanks

**Comment by thkzrl** [comment]
Added  golang.org/x/crypto/hkdf to the vendors libs.

**Pull request merged**
