### PR TITLE
Disable behave issue 680 test

### PR DESCRIPTION
**Pull request by srderson**
## Description

Disables `Scenario Outline: chaincode example02 with 4 peers and 1 membersrvc, issue #680 (State transfer)` behave test.
## Motivation and Context

PR #1758 is breaking the issue 680 behave test. The failure is
`Assertion Failed: Failed to POST to http://172.17.0.47:5000/devops/query:  {"Error": "Error: state may be inconsistent, cannot query"}`

From @jyellick 
"This is likely equivalent behavior, we used to silently reply with out of date or wrong information during state transfer, we now reply with that error. If it is causing headaches, feel free to disable for now, and I'll take a look after some more critical bugs"

This PR disables the test case so others do not think that their changes are breaking the build.
## How Has This Been Tested?

Disables test case for now.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Sheehan Anderson sheehan@us.ibm.com

**Only consider merging if build is passing.**

### CODE REVIEW

**Comment by christo4ferris** [comment]
reverify jenkins

**Comment by christo4ferris** [comment]
Jenkins seems to be having a bad day, but the Travis build passes - suggest this be merged @ghaskins, @tamasblummer or @binhn so that we can all get back to our daily grind and put issue 680 behave test behind us.

**Comment by ghost** [comment]
reverify jenkins

**Comment by ghaskins** [comment]
LGTM

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Pull request merged**
