### PR TITLE
specify unit of measure for block timeout

### PR DESCRIPTION
**Pull request by tuand27613**
for #679 

Specify noops block timeout in seconds/milliseconds etc ... all valid units for time.Duration

### CODE REVIEW

**Comment by tuand27613** [comment]
Signed-off-by: Tuan Dang tdang@us.ibm.com

**Comment by tuand27613** [comment]
@kchristidis  quick check please ?

**Comment by kchristidis** [comment]
@tuand27613 It's been merged already, but everything here looks good.

**Comment by kchristidis** [comment]
(For some odd reason, I missed this yesterday. Sorry.)

**Comment by tuand27613** [comment]
np ! thanks @kchristidis  !

**Pull request merged**
