### PR TITLE
pbft: make quorum counts explicit

### PR DESCRIPTION
**Pull request by corecode**
Signed-off-by: Simon Schubert sis@zurich.ibm.com

### CODE REVIEW

**Comment by corecode** [comment]
This is the PR for #573

**Comment by kchristidis** [comment]
@binhn, @srderson: Same note applies here: https://github.com/openblockchain/obc-peer/pull/624#issuecomment-182106532

**Comment by srderson** [comment]
Confirmed that unit tests and behave tests are passing with this PR.

**Comment by srderson** [comment]
@corecode Could you fix the conflicts in your branch? I can't seem to figure out how to push from my side and keep your commit history.

**Comment by corecode** [comment]
You're all working too much - I thought my branch was in sync with master :)  Now it is fixed.

**Comment by srderson** [comment]
Thanks @corecode. Merged.

**Pull request merged**
