### PR TITLE
Have the certificates created 1 minute in the past

### PR DESCRIPTION
**Pull request by mrshah-at-work**
Have the certificates created 1 minute in the past (update notBefore timestamp) to account for the clock jitter/skew on different machines

### CODE REVIEW

**Comment by mrshah-at-work** [comment]
Signed-off-by: Mihir Shah mrshah@us.ibm.com

**Comment by mrshah-at-work** [comment]
Tagging @adecaro & @thkzrl, so they can have a look at the PR.

**Comment by adecaro** [comment]
@thkzrl, please, give a look at this PR.

**Comment by thkzrl** [comment]
Good, thanks!

**Comment by adecaro** [comment]
@srderson not sure I can handle this PR. As @thkzrl confirmed, the crypto part is fine. May you take care of the rest?

**Comment by srderson** [comment]
Confirmed all tests are passing. Thanks

**Pull request merged**
