### PR TITLE
Consensus threading and queues

### PR DESCRIPTION
**Pull request by jyellick**
This PR is built upon the changeset which @corecode did for persistence.

The first purpose of this changeset is to switch the `pbft-core.go` and each of the respective plugins to operate on a single thread.  This eliminates the need to acquire and drop locks in the code, and eliminates several conditions which existed in the code.

The second purpose is to enable message queueing for consensus so that other message types (in particular state transfer peer messages) are not blocked because the handler is waiting to deliver messages to consensus as this blocking can create deadlocks.  This is accomplished through the standard go fan in pattern, where each handler creates a buffered channel, and these buffered channels fan into a single buffered channel, which is then sent to consensus for processing.  The message fan is currently only employed for consensus requests.  In the future, the same fan code/structure can be utilized for the queueing of queries and potentially peer messages.

With this changeset, (admittedly before rebasing onto Simon's latest), using the classic pbft plugin, my local vagrant environment was able to process 10k requests, being delivered as rapidly as they could be accepted to a single peer, by 20 threads (at 500 requests each).  This processing did not trigger a view change, and all requests were processed successfully.  This is an improvement over last sprint, where deadlocks were often seen beyond about 2k requests.  @bcbrock you might be interested to try your stress tests again against this changset.  I will re-run my local stress test against this PR, assuming it passes the CI tests and will post the results here.

Some code review from @corecode @tuand27613 @kchristidis or others would be appreciated if cycles allow.

Signed-off-by: Jason Yellick jyellick@us.ibm.com

### CODE REVIEW

**Comment by bcbrock** [comment]
@jyellick - Thanks, I'll try it Thursday afternoon or Friday.

**Comment by jyellick** [comment]
@bcbrock Just retested with the 10k request flood.  The current branch still passes it.

**Comment by bcbrock** [comment]
@jyellick - In this case: 4 peers, PBFT classic, 10K back-to-back TX sent to peer 0 - it seems to work most of the time. At least Issue #1091 seems to be gone. It's hard to characterize/repeat the non-working attempts. Other scenarios definitely fail.

My 2 cents would be to go ahead and merge assuming the reviewers agree that the architecture is good, then we can start to tackle the next set of issues.

**Comment by srderson** [comment]
@jyellick There's a merge conflict on this PR. Assume this is because of the requirements on @corecode's PR which also have conflicts.

**Comment by jyellick** [comment]
Closing, because this was rebased into #1325

**Pull request closed without merging**
