### PR TITLE
Allow cc call cc for minimal security settings#issue1530

### LINKED ISSUE #1530: shim.GetRow() fails in chaincode query chaincode context, but succeeds in normal query context
## Description

shim.GetRow() returns the row successfully when querying a chaincode directly. But, when the same chaincode is queried from another chaincode, shim throws an error.
## Describe How to Reproduce

Running in dev mode, single node, vagrant setup, security on, privacy off (but I dont think its related to security).
Implement a query function that does a GetRow for a table. Call the query directly -- this succeeds. Call the query from another chaincode using shim.QueryChaincode, this throws an error.
[GetRow_Fail.txt](https://github.com/hyperledger/fabric/files/273897/GetRow_Fail.txt)
[GetRow_Success.txt](https://github.com/hyperledger/fabric/files/273898/GetRow_Success.txt)

### PR DESCRIPTION
**Pull request by muralisrini**
Chaincode - Chaincode interactions did not support security enablement options. This fix supports chaincode calling chaincode with security enabled but privacy disabled.  Further, the fix returns a "not supported" error if chaincode calls another with privacy enabled.

NOTE : Has undergone a preliminary code review from @adecaro. However, would like another code review... but want to make sure the PR will pass tests while waiting for it.
## Description

The called chaincode is passed the security context (the transaction wrapper with a security context). Both chaincode-query-chaincode and chaincode-invoke-chaincode call a "canCallChaincode" whose only purpose is to prevent interactions when privacy is enabled. This function should be a guideline to complete the fix in future to allow chaincode interactions with privacy enabled.

Rest of the changes are for unit test case to test the "with security" scenario, _pending support for multiple chaincodes in behave test framework_. Part of the changes was to refactor the TestChaincodeQueryChaincode test case to extract common code.

NOTE : resorted to creating a "chaincodetest.yaml" in the chaincode dir after having difficulties getting properties from peer and member services to work together - all other approaches (such as overriding specific properties) yielded interactions I could not figure out.
## Motivation and Context

Issue found in the field where chaincode-chaincode interaction does not work with security enabled.

Fixes #1530
## How Has This Been Tested?

Added a new unit test and ran make unit-test and behave. Also tested the unit test in isolation,
## Checklist:
- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [X] Either no new documentation is required by this change, OR I added new documentation
- [X] Either no new tests are required by this change, OR I added new tests
- [X] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: muralisr@us.ibm.com

### CODE REVIEW

**Comment by muralisrini** [comment]
@prjayach : perhaps you can test this too in your environment please ?

**Comment by prjayach** [comment]
I have tested this and it helps solve #1530 with PRIVACY=false. Thanks @muralisrini!

**Comment by prjayach** [comment]
Is it possible to have this merged today please?

**Comment by muralisrini** [comment]
@prjayach trying to get a behave test implemented today so I can revert some of the unit-test changes (too complex for a unit test with some yaml duplication which would be nice to avoid).

**Comment by muralisrini** [comment]
We could not replace the unit test with the behave code.  I can open an issue to move the unit test to behave when support becomes available so this PR can be accepted. Please let me know.

**Comment by prjayach** [comment]
Any chance we can have this merged? Last week before we show to stakeholders and we can't continue integration testing without this. @muralisrini  @binhn

**Comment by srderson** [comment]
@prjayach One of the great features of Git and GitHub is that it's very easy to merge the code from a PR into your own fork. There's no need for this PR to be merged into the master branch for you to use the code that @muralisrini has provided. This is important because there are times when the community's acceptance of PRs will lag behind your schedule.

To merge the code into a branch, simply run
`git checkout -b muralisrini-allow_cc_call_cc_for_minimal_security_settings#issue153`
`git pull https://github.com/muralisrini/fabric.git allow_cc_call_cc_for_minimal_security_settings#issue1530`
in your Git repository.

**Comment by prjayach** [comment]
@srderson I have done this and tested on my private setup. However, we need to be able to have this on a 4 node Z setup, that requires some patches to be applied for Z. Complicates things too much if we have to pull a private branch for this. I will parallelly explore if the Z patches can be applied on Murali's branch instead of on master.

**Comment by prjayach** [comment]
I have left a comment above that I have tested this branch and this PR helps solve #1530 with PRIVACY=false.

**Comment by ghaskins** [comment]
I spoke with @muralisrini over slack.  The unit-test approach was used because behave currently lacks the ability to store more than one chaincode at a time.  Once this issue with behave is resolved, these tests will be ported to a behave model in a future PR.  While the unit-test approach is slightly unorthodox, the impact to the real code is minimal.  I am fine with merging this.

LGTM

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Comment by muralisrini** [comment]
thanks @ghaskins. Opened issue https://github.com/hyperledger/fabric/issues/1565 to replace the unit test with a behave test.

**Pull request merged**
