### PR TITLE
Normalize the processing of logging options for obc-peer

### PR DESCRIPTION
**Pull request by bcbrock**
This is a proposed change that addresses #569 and #310, and also partially
addresses #578. The handling of logging levels, and ways of managing logging
levels are currently inconsistent and incomplete in the obc-peer
application. In this change:

Logging options are now top-level options in the openchain.yaml file and on
the command line. A single command-line option '--logging-level' applies to
all commands. In the openchain.yaml however, defaults can be set for each of
the obc-peer commands individually. This made sense to me since it seems
reasonable that logging requirements are likely different for server
vs. client commands.

The syntax for specifying logging levels allows the specification of both a
default level for all modules as well as module-specific levels.

The file openchain/logging.go had originally been copied from the examples of
the op/go-logging package, and was therefore mostly dead and irrelevant
code. This file has been completely replaced. This file now defines a 'hook'
routine that is called during the Cobra processing of the obc-peer commands to
set up logging options.  This hook correctly allows command-line options to
override config file options (cf. #578).

main.go was simplified by removing all of the module-specific setup, and the
logging command-line options were promoted to global options. The new hook is
installed in the Cobra Command structures.

The default logging level for the 'peer' server is now INFO; For the other
client commands the default level is WARNING. Developers and others can easily
override these setting in their openchain.yaml files or on the command line or
environment of each invocation of obc-peer.

### CODE REVIEW

**Comment by bcbrock** [comment]
Signed-off-by: Bishop Brock bcbrock@us.ibm.com

**Comment by binhn** [comment]
We need to update the documents to include some info on how to set logging, but I merge this PR now and open up another issue to do the doc. Thanks @bcbrock

**Comment by samding01** [comment]
Now the obc-peer is respecting the logging.level setting, however the chaincode (chaincode_example0[1-5] ) does not respect the logging.level setting. here is the output from 
chaincode_example02:

>  ....
>  Query Response:{"Name":"a","Amount":"100"}
> 2016/02/04 15:17:26 [c886c8f0]Query completed. Sending QUERY_COMPLETED
> 2016/02/04 15:17:26 [d3aa9f3f]Received message TRANSACTION from shim
> 2016/02/04 15:17:26 [d3aa9f3f]Handling ChaincodeMessage of type: TRANSACTION(state:ready)
> 2016/02/04 15:17:26 [d3aa9f3f]Received TRANSACTION, invoking transaction on chaincode(Src:ready, Dst:transaction)
> 2016/02/04 15:17:26 [d3aa9f3f]Sending GET_STATE
> 2016/02/04 15:17:26 [d3aa9f3f]Received message RESPONSE from shim
> 2016/02/04 15:17:26 [d3aa9f3f]Handling ChaincodeMessage of type: RESPONSE(state:transaction)
> 2016/02/04 15:17:26 [d3aa9f3f]before send
> 2016/02/04 15:17:26 [d3aa9f3f]after send
> 2016/02/04 15:17:26 [d3aa9f3f]Received RESPONSE, communicated (state:transaction)
> 2016/02/04 15:17:26 [d3aa9f3f]GetState received payload RESPONSE
> 2016/02/04 15:17:26 [d3aa9f3f]Sending GET_STATE
> 2016/02/04 15:17:26 [d3aa9f3f]Received message RESPONSE from shim
> 2016/02/04 15:17:26 [d3aa9f3f]Handling ChaincodeMessage of type: RESPONSE(state:transaction)
> 2016/02/04 15:17:26 [d3aa9f3f]before send
> 2016/02/04 15:17:26 [d3aa9f3f]after send
> 2016/02/04 15:17:26 [d3aa9f3f]Received RESPONSE, communicated (state:transaction)
> 2016/02/04 15:17:26 [d3aa9f3f]GetState received payload RESPONSE
> ....

This causes the a lot of debug  msg output, especially multiple peers started by docker containers.   This impacts the performance measurement.  
Could you please clean up the code and make all the components respect the logging.level setting?

Thank

**Comment by bcbrock** [comment]
@samding01 - Are you saying that this change changed the behavior and caused these debug messages to start appearing, or are you simply asking that these messages be suppressed? 

Based on the log messages and by looking at the code, it doesn't look like chaincode logging is controlled by the same mechanisms that control the obc-peer. E.g., there is no command-line flag processing in chaincode_example02, and as far as I can tell it does not read read YAML files. 

For a quick fix, in chaincode_example02.go add the import

```
"github.com/op/go-logging"
```

and in the main() routine make the first line 

```
logger.SetLevel(logger.ERROR, "")
```

The only thing you'll see now is the result of the printf() on line 55 of chaincode_example02.go

**Pull request merged**
