### PR TITLE
Add go tests for ECA

### LINKED ISSUE #1590: Add Enrollment (CA) feature tests
## Description

We need to have a set of tests covering the behavior and functionality using various (Behave) scenarios around Enrollment.

In particular, with a focus on the Enrollment CA (ECA) functionality of Membership Services.
## Motivation

At this point, even a small number of positive- and negative- flows will go a long way, both for development, testing but also as an easy way for new users to learn about Hyperledger fabric and its capabilities.
## Context

Membership Services end-to-end integration tests. A sub-task of [1575](https://github.com/hyperledger/fabric/issues/1575)

### PR DESCRIPTION
**Pull request by mastersingh24**
## Description

Added go test for eca (plus a little related cleanup)
## Motivation and Context

There was very limited test coverage within the membersvcs package for the eca component
Fixes #1590
## How Has This Been Tested?

This is actually adding test cases.  Current tests in the package still work as well
## Checklist:

- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [X] Either no new documentation is required by this change, OR I added new documentation
- [X] Either no new tests are required by this change, OR I added new tests
- [X] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Gari Singh gari.r.singh@gmail.com

### CODE REVIEW

**Comment by mastersingh24** [comment]
@JonathanLevi  - can you take a look when you get a chance?

**Comment by adecaro** [comment]
@mastersingh24 why is coverage.out in? Is it a file that should be in for all packages?

**Comment by JonathanLevi** [comment]
@adecaro: Good point. FYI, this file will be removed auto-magically once the (approved) [1761](https://github.com/hyperledger/fabric/pull/1761) PR is merged.

@mastersingh24: Many, many thanks for this. Will do.

**Comment by adecaro** [comment]
Ah right, thanks @JonathanLevi :)

**Comment by mastersingh24** [comment]
@adecaro - I left it in since it was already there

@JonathanLevi  - thanks for checking it out.  still some things which could be better but wanted to get this in since it has about 80% coverage now

**Comment by bramwelt** [comment]
reverify jenkins

**Comment by JonathanLevi** [comment]
Ignoring Jenkins' BDD/Behave tests failures for now, as suggested. 

LGTM. Thanks again, J

**Comment by christo4ferris** [comment]
@mastersingh24 looks like you need to rebase before this can be merged. I agree with @JonathanLevi that there is room for improvement (e.g. validating that what was expected to happen, actually happened, as opposed to just checking for an unexpected error). LGTM

**Comment by mastersingh24** [comment]
damn - something went awry.  trying to do too many things at the same time

price you pay for not having these test originally.  interface / logic change for creating a user is breaking this

**Comment by christo4ferris** [comment]
reverify jenkins

**Comment by mastersingh24** [comment]
hopefully this passes and the PR is accepted soon.  there is a lot of activity in membersvcs and would like to get these tests checked in so we have a baseline for further changes

**Comment by mastersingh24** [comment]
I don't think this PR broke the build but let me know

**Comment by christo4ferris** [comment]
restarted Travis build...

**Comment by JonathanLevi** [comment]
(Good morning) @mastersingh24, can you please merge down from master into this branch again?

**Comment by mastersingh24** [comment]
@JonathanLevi  - okay.  will do.  I certainly hope nothing breaks

**Comment by mastersingh24** [comment]
looks like we got past `make unit-test`  woo hoo

**Comment by mastersingh24** [comment]
@ghaskins @binhn  - could one of you quickly look at this to get it merged?  there are a bunch of things which will come in under membersvcs so would be good to get some base tests checked in

**Comment by srderson** [comment]
LGTM. Thanks!

**Pull request merged**
