### PR TITLE
Fixhash#issue1789

### LINKED ISSUE #1789: chaincode ID computation ignores chaincode content
## Description

In chaincode/platforms/golang/hash.go, files are collected from the chaincode path and read in sorted order in preparation for chaincode ID computation. However, the bytes from the files are not copied to the allocated byte buffer and so the computation was using a buffer with null bytes, thus ignoring file content completely. This results in chaincode ID remaining unchanged if content is modified while retaining the file size.
## Describe How to Reproduce

Modify a byte in the chaincode "go" file (don't add or delete, just modify). The chaincode ID will remain unchanged.

Thanks to @angrbrd for discovering this bug.

### PR DESCRIPTION
**Pull request by muralisrini**
Copy the file contents to the allocated byte buffer before computing hash.
## Description

Hash computation code prepares for computation correctly (fetch files/folders in sorted order) but missed copying the contents of the file into the allocated buffer. This code fixes that with a "copy" command.

The fix also adds a set of dummy files and a dummy folder to the well-used chaincode_example02 to make sure to catch changes to chaincode ID (mainly test dependence on sorting order). chaincode_example04 hard-codes chaincode_example02's ID thus verifying the invariance via unit tests. A README.txt explains the intent of the dummy files.
## Motivation and Context

The intent was to compute chaincode ID based on the hash of the contents of the files in the chaincode path. 
Fixes #1789
## How Has This Been Tested?

Enhanced chaincode_example02 with dummy files to test ordering. Existing unit test covers the fix (especially TestChaincodeInvokeChaincode).
## Checklist:
- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [X] Either no new documentation is required by this change, OR I added new documentation
- [X] Either no new tests are required by this change, OR I added new tests
- [X] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by:muralisr@us.ibm.com

### CODE REVIEW

**Comment by muralisrini** [comment]
thanks @angrbrd

**Comment by binhn** [comment]
LGTM

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by binhn** [comment]
@rameshthoomu CI is still failing.  Can we just go with Jenkins now?

**Comment by rameshthoomu** [comment]
@binhn: Jenkins is configured and builds are triggering successfully but have some issues on parallel builds on same machine. @bramwelt and me are working on these issues. Travis is failing because of timeout issues. Specific to this build error, `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` Not sure why input is not receiving for 10 mins.

**Comment by christo4ferris** [comment]
@muralisrini please add tests that validate the correct functioning

**Comment by muralisrini** [comment]
@christo4ferris : I used existing test TestChaincodeInvokeChaincode in exectransaction_test.go to test for this fix as well. The hardcoded example02's ID in example04 should never change.  I added dummy files and folder to example02 chaincode folder to strengthen the test further so as to make sure sorted ordering is tested as well. This way the fix is tested without increasing the chaincode test time. 

What do you think ? If you feel a new test is better, I can add one.

**Comment by christo4ferris** [comment]
@muralisrini if that test was effective, it would have caught the bug. It didn't, 'nuf said. You need to add a test that will catch that the file(s) have changed. Further, you could add a unit test that hashed a file's contents and check the result against the expected result.

**Comment by muralisrini** [comment]
@christo4ferris the test is effective to the extent that it tests for id remaining unchanged when code does not change (so when example02 is changed, the test will catch that). But you are right - it does not test the condition that ID should change when file's content is changed.

I will add add a unit test to test hash ID is changed when content changes.

**Comment by muralisrini** [comment]
@christo4ferris added unit test for hash computation

**Comment by christo4ferris** [comment]
restarted Travis, thanks for adding the tests @muralisrini

**Comment by muralisrini** [comment]
@christo4ferris one more change (pretty) please ..... should have checked random quantities are always different.

**Comment by bramwelt** [comment]
reverify jenkins

**Pull request merged**
