### PR TITLE
Update test info and go tool info in PR template

### PR DESCRIPTION
**Pull request by srderson**
## Description

This PR updates the PR template to ask additional questions about testing and also ask committers to run several Go tools and resolve warnings and errors
## Motivation and Context

The goal of the PR is to reduce the work for maintainers who are asking the same questions over and over. This should also speed up the PR process as it will help submitters understand what needs to be completed for approval.
## How Has This Been Tested?

There are no new tests because this is only a change to the PR template.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

Signed-off-by: sheehan@us.ibm.com

### CODE REVIEW

**Comment by ghaskins** [comment]
LGTM

Related to this, I wonder if we can automate anything like golint as part of travis?

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Comment by srderson** [comment]
I'm concerned that @dco-bot has gained self awareness, named itself Chris, and is considering making a PR :p
...
or maybe it's just @christo4ferris on the wrong account? :)

+1 for adding gometalinter, goimports, and gofmt to Travis. [gometalinter](https://github.com/alecthomas/gometalinter) is what I use and I think it's a good tool, but let me know if there are other suggestions. I think it would be best for everyone to try to standardize on one tool.

**Comment by ghaskins** [comment]
I hadn't heard of gometalinter prior to your PR, but IIUC it looks like it might be a superset of all the others?  If so, it seems like travis could just call that one tool to get coverage across the board.

**Comment by christo4ferris** [comment]
I hadn't heard of this before, either... but looks like it is slow... I am still trying to figure out why even the barest of builds is failing now. All I want is to test the golint command. 

As for the previous comment, I replied to the email notification of the comment. Weird that it thought I was dco-bot.

dco-bot

**Pull request merged**
