### PR TITLE
Fix some typo and mis-translate in protocol-spec_zh.md

### PR DESCRIPTION
**Pull request by HaiyangDING**
## Description

Fix some typos and mis-translation in protocol-spec_zh.md
## Motivation and Context

Fixes #

There are some typos in protocol-spec_zh.md and they should be fixed. See details in the PR.
## How Has This Been Tested?

Updating docs does not require tests.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by:

Signed-off-by: HaiyangDING dinghaiyang@huawei.com

### CODE REVIEW

**Comment by HaiyangDING** [comment]
I have no idea why jenkins fails on this PR. Does this build include other changes as well? Would someone please give me some hint on this? Thanks.

**Comment by yeasy** [comment]
Please migrate to gerrit.
See docs/Gerrit.

**Comment by HaiyangDING** [comment]
@yeasy 

Thanks, I will do this right away.

**Comment by christo4ferris** [comment]
@HaiyangDING can this be closed now?

**Comment by HaiyangDING** [comment]
@christo4ferris 

Sure, let's close this.

**Pull request closed without merging**
