### PR TITLE
Fix Issue #653 - Incorrect Logging Levels

### LINKED ISSUE #653: Several serious container errors are being reported at the DEBUG level
There are several log messages related to container handling that I think should be promoted from DEBUG level to a higher level, as these represent errors from the user's perspective. This will make it easier for users (like me) to figure out what's going on, as these messages are normally not printed.

Here are a few examples:

```
12:38:25.785 [container] build -> DEBU 029 Error building Peer container: Error: image bcbrock/golang:latest not found
12:38:25.800 [container] start -> DEBU 031 start-container does not exist, attempting to create API error (404): no such id: dev-vp1-60caf3632e0f43a5a7f14f27115bfaf84f76ee59d3490bbb337703e098ada77fc7b7bddd093f354e8ef89f644330131e5799c966503070b94eb1a83cbc9dc10c
12:38:25.803 [container] start -> DEBU 033 start-could not recreate container no such image
12:57:11.180 [chaincode] LaunchChaincode -> DEBU 09c launchAndWaitForRegister failed Error starting container: no such image
```

### PR DESCRIPTION
**Pull request by juliancarrivick-ibm**
## Description

Replace a number of Debug log statements with Error log statements as they were reporting errors, not debug information.
## Motivation and Context

Fixes #653 
It will be easier for users to determine why things are not working if errors are reported correctly.
## How Has This Been Tested?

There is no logic changes, so hence no new unit tests.
I have ensured the code builds.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Julian Carrivick cjulian@au1.ibm.com

### CODE REVIEW

**Comment by bcbrock** [comment]
@juliancarrivick-ibm Thank you. May I suggest a few tests to try just to be sure? Basically, try every possible way that chaincode deployment could fail and make sure we get errors in the logs:
1) Run in an environment where the Docker server does not map the TCP port
2) Modify the chaincode Dockerfile to name a bogus image
2) Deploy a Go chaincode that doesn't compile
3) Deploya chaincode with bogus initialization parameters

**Comment by christo4ferris** [comment]
@bcbrock I like the idea of moar testing, as you know... Otherwise, the changes LGTM

**Comment by juliancarrivick-ibm** [comment]
@bcbrock Results of your scenarios:
1) Run in an environment where the Docker server does not map the TCP port

``` bash
02:44:03.453 [rest] processChaincodeDeploy -> INFO 01f Successfully deployed chainCode: d47ee9365d66d6ed09100f123dea3a8e02ae264aca56a3bb19392118e909869013058899233c13eac9ffe14f0bd63813f282cb52b6e74013919d03166ebd87d3
02:44:03.453 [rest] ProcessChaincode -> INFO 020 REST successfully deploy chaincode: {"jsonrpc":"2.0","result":{"status":"OK","message":"d47ee9365d66d6ed09100f123dea3a8e02ae264aca56a3bb19392118e909869013058899233c13eac9ffe14f0bd63813f282cb52b6e74013919d03166ebd87d3"},"id":0}
02:44:04.465 [dockercontroller] deployImage -> ERRO 021 Error building images: cannot connect to Docker endpoint
02:44:04.472 [dockercontroller] Start -> ERRO 022 start-could not recreate container cannot connect to Docker endpoint
02:44:04.472 [chaincode] Launch -> ERRO 023 launchAndWaitForRegister failed Error starting container: cannot connect to Docker endpoint
```

2) Modify the chaincode Dockerfile to name a bogus image

``` bash
02:50:40.100 [rest] processChaincodeDeploy -> INFO 022 Successfully deployed chainCode: d47ee9365d66d6ed09100f123dea3a8e02ae264aca56a3bb19392118e909869013058899233c13eac9ffe14f0bd63813f282cb52b6e74013919d03166ebd87d3
02:50:40.100 [rest] ProcessChaincode -> INFO 023 REST successfully deploy chaincode: {"jsonrpc":"2.0","result":{"status":"OK","message":"d47ee9365d66d6ed09100f123dea3a8e02ae264aca56a3bb19392118e909869013058899233c13eac9ffe14f0bd63813f282cb52b6e74013919d03166ebd87d3"},"id":0}
02:50:41.359 [dockercontroller] deployImage -> ERRO 024 Error building images: Error parsing reference: "hyperledger/fabric-INCORRECTbaseimage" is not a valid repository/tag
```

3) Deploy a Go chaincode that doesn't compile

``` bash
2:56:08.811 [rest] ProcessChaincode -> INFO 01e REST successfully deploy chaincode: {"jsonrpc":"2.0","result":{"status":"OK","message":"a995a211c45d5fb0070ae23fa64993a15728bb5f30e11b08a70da93a97b745a736068edbc5908f16567073d513d5e9a5ec721e54cf6dd79c245b7fdacf53ffae"},"id":0}
02:56:14.166 [peer] ensureConnected -> INFO 01f Touch service indicates no dropped connections
02:56:15.975 [dockercontroller] deployImage -> ERRO 020 Error building images: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/a995a211c45d5fb0070ae23fa64993a15728bb5f30e11b08a70da93a97b745a736068edbc5908f16567073d513d5e9a5ec721e54cf6dd79c245b7fdacf53ffae' returned a non-zero code: 2
02:56:20.166 [peer] ensureConnected -> INFO 021 Touch service indicates no dropped connections
02:56:21.237 [dockercontroller] deployImage -> ERRO 022 Error building images: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/a995a211c45d5fb0070ae23fa64993a15728bb5f30e11b08a70da93a97b745a736068edbc5908f16567073d513d5e9a5ec721e54cf6dd79c245b7fdacf53ffae' returned a non-zero code: 2
02:56:21.237 [chaincode] Launch -> ERRO 023 launchAndWaitForRegister failed Error starting container: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/a995a211c45d5fb0070ae23fa64993a15728bb5f30e11b08a70da93a97b745a736068edbc5908f16567073d513d5e9a5ec721e54cf6dd79c245b7fdacf53ffae' returned a non-zero code: 2
```

4) Deploy a chaincode with bogus initialization parameters

``` bash
02:59:47.469 [container] WriteGopathSrc -> INFO 01f rootDirectory = /opt/gopath/src
02:59:48.304 [rest] processChaincodeDeploy -> INFO 020 Successfully deployed chainCode: 51c2793ead88cb2a785180261cfff676e7ee6c12882cecced73ed4c30e9eabc858de3e653672e48428145825e171b3f6dfe31e03e3a2f5e1368fdec0edfefaf3
02:59:48.304 [rest] ProcessChaincode -> INFO 021 REST successfully deploy chaincode: {"jsonrpc":"2.0","result":{"status":"OK","message":"51c2793ead88cb2a785180261cfff676e7ee6c12882cecced73ed4c30e9eabc858de3e653672e48428145825e171b3f6dfe31e03e3a2f5e1368fdec0edfefaf3"},"id":0}
02:59:50.310 [peer] ensureConnected -> INFO 022 Touch service indicates no dropped connections
02:59:56.304 [peer] ensureConnected -> INFO 023 Touch service indicates no dropped connections
02:59:57.694 [chaincode] processStream -> ERRO 024 Got error: Incorrect number of arguments. Expecting 4
02:59:57.695 [chaincode] Launch -> ERRO 025 sending init failed(Error initializing container 51c2793ead88cb2a785180261cfff676e7ee6c12882cecced73ed4c30e9eabc858de3e653672e48428145825e171b3f6dfe31e03e3a2f5e1368fdec0edfefaf3: Incorrect number of arguments. Expecting 4)
02:59:57.719 [chaincode] processStream -> ERRO 026 Error handling chaincode support stream: connection error: desc = "transport is closing"
```

If there any other scenarios that need testing let me know and I'll do them.

One thing I noticed is that these failures are not relayed to the user (via REST). I think this definitely needs to be relayed back to the user. I'll create an issue so it can be tracked.

**Comment by bcbrock** [comment]
@juliancarrivick-ibm Thank you! Since you're changing messages, could you also make the REST API messages less positive? (It always claims "success", even when the actual deployment fails!)

**Comment by bcbrock** [comment]
Also, I'm not a Docker expert, but when we get messages like 

```
The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/a995a211c45d5fb0070ae23fa64993a15728bb5f30e11b08a70da93a97b745a736068edbc5908f16567073d513d5e9a5ec721e54cf6dd79c245b7fdacf53ffae' returned a non-zero code: 2
```

is there any way to recover the stdout/stderr from the failed command and inject it into the logs? This is always frustrating to me, since you have to guess what happened. Maybe the solution is to rewrite the Dockerfile, I'm not sure.

**Comment by srderson** [comment]
@juliancarrivick-ibm Thanks, LGTM. It sounds like @bcbrock's suggestions can be handled in a different PR.

**Comment by juliancarrivick-ibm** [comment]
@bcbrock I'll see what I can do :)

**Pull request merged**
