### PR TITLE
Fixup the map example to conform to the new shim interface

### PR DESCRIPTION
**Pull request by zmanian**

### CODE REVIEW

**Comment by zmanian** [comment]
Signed-off-by: Zaki Manian zaki@skuchain.com

**Comment by zmanian** [comment]
Closing in favor of #1036

**Comment by srderson** [comment]
Reopening as this PR came in first and @muralisrini removed the map changes from his after seeing an email for this PR.

**Comment by srderson** [comment]
LGTM. Thanks!

**Pull request merged**
