### PR TITLE
Fixes issue #617

### PR DESCRIPTION
**Pull request by genggjh**
Signed-off-by: David Geng david@esse.io

### CODE REVIEW

**Comment by genggjh** [comment]
First patch is using to update vender code to fix panic issue.
Second patch is using to add a new flag '--password' when run login command.

**Comment by bcbrock** [comment]
@genggjh Hi David - I'm not sure why you needed to pass the command object into the login routine, none of the other routines do this even though they handle flags.

Also a typo:
`
The password for user. You will be requested to enter the password if this flag does not specified.
`
should be
`
The password for user. You will be requested to enter the password if this flag IS not specified.
`

**Comment by genggjh** [comment]
@bcbrock , thanks for your comment, I will fix the typo and refine the code to get the password from global variable.

**Comment by bcbrock** [comment]
@genggjh Also, please add some brief documentation of the feature in Section 6.1.3.2 of docs/protocol-spec.md.

**Comment by genggjh** [comment]
@bcbrock I tried to find out where to doc this new argument, now you did it, thanks.

**Comment by bcbrock** [comment]
This looks OK to me, assuming it works. I see that there are no tests for _any_ of the CLI functions in this repo (@angrbrd @bmos299 ?) so I don't think we need to require @genggjh to provide one.

**Comment by srderson** [comment]
LGTM. Confirmed tests are passing.

@angrbrd @bmos299 - Let me know if I should open an issue for CLI tests or if we already have one.

**Pull request merged**
