### PR TITLE
Update formatting

### PR DESCRIPTION
**Pull request by ghost**
Added line breaks to fix formatting run-ons

## Motivation and Context

Fixes #
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Ry Jones rjones@linuxfoundation.org

### CODE REVIEW

**Comment by rjones-lf** [comment]
reverify jenkins

**Comment by rjones-lf** [comment]
reverify jenkins

**Comment by ghost** [comment]
@srderson this passed travis, please ignore Jenkins and merge if you approve

**Comment by ghaskins** [comment]
LGTM

**Pull request merged**
