### PR TITLE
Fix Travis build issues

### LINKED ISSUE #2266: ImportError: No module named google.protobuf error only in Travis
## Description

Observed google.protobuf error in travis builds while executing behave tests. This issue observed in almost all the Travis PR Builds after merge the PR #2213 (commit https://github.com/hyperledger/fabric/commit/a511daa6bde7bef7e658c4059fc7b467dca871a1) in fabric master.  

```
Binary available as build/bin/peer
Running behave tests
Exception ImportError: No module named google.protobuf
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 678, in run_with_paths
    self.load_step_definitions()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 658, in load_step_definitions
    exec_file(os.path.join(path, name), step_module_globals)
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 304, in exec_file
    exec(code, globals, locals)
  File "steps/bdd_grpc_util.py", line 20, in <module>
    import devops_pb2
  File "/home/travis/gopath/src/github.com/hyperledger/fabric/bddtests/devops_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf
make: *** [behave] Error 1
rm build/docker/bin/membersrvc build/docker/bin/peer
```

commit a511daa6bde7bef7e658c4059fc7b467dca871a1
Author: Jeronimo jeronimo.irazabal@gmail.com
Date:   Tue Jul 19 11:40:25 2016 -0300
## Describe How to Reproduce

Travis Builds - 
https://travis-ci.org/hyperledger/fabric/jobs/146260865
https://travis-ci.org/hyperledger/fabric/jobs/145844081

### PR DESCRIPTION
**Pull request by juliancarrivick-ibm**
## Description

Attempt to re juggle the python package installations in `scripts/provision/host.sh`
## Motivation and Context

Fixes #2266 
New Pull Requests won't pass the Travis CI tests if this is not fixed.
## How Has This Been Tested?

None needed, trying to get the tests to run correctly in Travis.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Julian Carrivick cjulian@au1.ibm.com

### CODE REVIEW

**Comment by juliancarrivick-ibm** [comment]
reverify travis

Passed 1st time: re-verifying as I found issue to be intermittent and want to make sure this fixes it

**Comment by juliancarrivick-ibm** [comment]
Ready to be merged sans feedback!

**Comment by christo4ferris** [comment]
LGTM thanks

**Comment by ghaskins** [comment]
LGTM, will squash merge it in.

**Pull request merged**
