### PR TITLE
Restructure peer/main.go

### PR DESCRIPTION
**Pull request by juliancarrivick-ibm**
## Description

Split the commands that `peer/main.go` defines into separate packages. This particular pull request changes no logic and only moves code around into new files/packages.

I would like some feedback that this is a worthwhile endeavour and is along a path that is desired by the maintainers. If I get the go ahead to continue I would also do the following (in separate PRs):
- Introduce a generic way of initialising the loggers for each sub command (node, network, chaincode, version)
- Start writing tests for the peer commands 
- Disentangle the peer functions from the large number of global variables
- Refactor each of the leaf commands into their own packages (e.g. `node start` with `start` going into its own package - in this PR it resides in the `node` package)

I would suggest it would be good to track all of this via #2170
## Motivation and Context

Addresses #2170 
`peer/main.go` is currently a monolithic >1100 line file which makes it difficult to read and understand. It would greatly enhance the maintainability of this module to have it split up into separate files. Additionally, once it is split up it will be much easier to write tests for (of which there are none currently).
## How Has This Been Tested?

There is no logic changes so I have not added any new unit tests. I have run all the behave tests to make sure I have not broken the command line.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Julian Carrivick cjulian@au1.ibm.com

### CODE REVIEW

**Comment by juliancarrivick-ibm** [comment]
Not quite sure why CI hasn't run here...

**Comment by corecode** [comment]
I think we should discuss this here, rather than in #2170

**Comment by corecode** [comment]
i like this change.

**Comment by srderson** [comment]
I also like this change.

Not sure why CI didn't run, it should have run automatically. @rameshthoomu any ideas?

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
I don't see any build log created for this build in fabric travis. I don't have any clue why the build is not triggered here.. Will check and update here..

**Comment by rameshthoomu** [comment]
no clue on why Travis is not triggered build for this specific commit.. I received below note from Travis Support team: We identified an issue with our scheduling engine that was throwing an unexpected error when trying to schedule a set of builds.

**Comment by juliancarrivick-ibm** [comment]
Cool, thanks @rameshthoomu 
I'll resubmit on Gerrit and it'll hopefully get run over there :)

**Comment by juliancarrivick-ibm** [comment]
Moved to Gerrit

**Pull request closed without merging**
