### PR TITLE
Update user password in SandboxSetup.md

### PR DESCRIPTION
**Pull request by iamsamwood**
Jim had the wrong password. 

Signed-off-by: Sam Wood iamsamwood@gmail.com

Fix to set Jim's password to match membersrvc.yaml

### CODE REVIEW

**Comment by christo4ferris** [comment]
Good catch, LGTM thanks! Please add the [DCO sign-off](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff) as dco-bot requested

**Comment by iamsamwood** [comment]
Signed-off-by: Sam Wood <iamsamwood@gmail.com>

**Comment by bramwelt** [comment]
reverify jenkins

**Comment by bramwelt** [comment]
reverify jenkins

**Comment by christo4ferris** [comment]
restarted Travis - the previous fail was resolved with subsequent merged PR

**Comment by srderson** [comment]
Thanks! LGTM

**Pull request merged**
