### PR TITLE
Issues/961/rbac tcerts no attrs

### LINKED ISSUE #1851: Peer2 doesn't restart communication with Peer1 once the communication breaks
## Description

When communication breaks between Peer1 & Peer2 due to a network glitch, Peer2 doesn't reconnect to Peer1 and stays idle.
## Describe How to Reproduce

1. Start a network with 2 peers
2. Break the communication between the two peers
3. Peer 2 doesn't reconnect to Peer 1
## Proposal

Ref: https://github.com/masterDev1985/fabric/commit/6adb13c053b14ab19ace0d095806046bc2086724
In the communication loop in chatPeer() function, continue on an error - thus reconnecting.

Note: In the above solution, the sleep between reconnects should be configurable from yaml file & there should be a maximum number of retries (or handle the "duplicate handler" error differently).

### PR DESCRIPTION
**Pull request by jeffgarratt**
## Description

Adds ability to test RBAC based chaincode through enhancements to behave user registration mechanism.  Also added Python generated GRPC stubs for all services and utilize these stubs for the chaincode to chaincode behave test.  Added coverage report capability for behave testing, with aggregate calculation.  Can be tuned based upon desired coverage.  Added simple touch function to Peer to ensure reconnect on total network disconnect.   
## Motivation and Context

These changes are required to enhance the capability of behave testing wrt to RBAC and to lay the groundwork for moving from HTTP based testing to GRPC.

Fixes #1851 #961 
## How Has This Been Tested?

New behave tests have been added and tested locally, but they are disabled pending an image update for the grpcio python library.
## Checklist:
- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [X] Either no new documentation is required by this change, OR I added new documentation
- [X] Either no new tests are required by this change, OR I added new tests
- [X] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Jeff Garratt garratt.jeff@gmail.com

### CODE REVIEW

**Comment by jeffgarratt** [comment]
@ghaskins I need to add a new pip install entry on or around https://github.com/hyperledger/fabric/blob/master/scripts/provision/host.sh#L23 as I wanted to begin leveraging python GRPC stubs for behave testing.  Is there any issue related to CI by adding a new entry such as:

> pip install 'grpcio==0.13.1'

This PR depends on the addition.

**Comment by binhn** [comment]
LGTM - Thanks.

**Comment by srderson** [comment]
`golint` was NOT run against the code in this PR despite the box being checked. For example, there are functions with underscores in their names in `devops.go`

**Comment by jeffgarratt** [comment]
@srderson I did run it but did not change as I wanted the fact that they are experimental to be very explicit, and thought leaving them would highlight this.

**Pull request merged**
