### PR TITLE
Update vendor pkg

### LINKED ISSUE #2044: HostConfig will be deprecated since Docker 1.12
## Description

With Docker 1.12, the following error will happens when deploying chaincode with hyperledger fabric.

```
[dockercontroller] Start -> ERRO 02e start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
```
## Describe How to Reproduce

Use Docker 1.12, and deploy chaincode with hyperledger fabric.

### PR DESCRIPTION
**Pull request by yeasy**
Update the docker client related vendor pkg to newer version
## Description

Existing docker client pkg does not support latest docker API,
e.g., Docker 1.12. This patch will update docker client pkg to latest
version, and add necessary dependencies, including:
- some sub pkgs of github.com/docker/docker
- github.com/docker/engine-api/types/filters
- github.com/docker/engine-api/types/versions
- github.com/fsouza/go-dockerclient
- github.com/docker/go-units
- github.com/hashicorp/go-cleanhttp
- github.com/opencontainers/runc
- github.com/Sirupsen/logrus

On the other hand, to meet the usage of go vendor, move docker client
dependent pkgs to outside for easier further updating.
## Motivation and Context

Fixes #2044.
## How Has This Been Tested?

Related test cases are passed, may need the CI testing.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Baohua Yang baohyang@cn.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
Did you use govendor to perform this update? See https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#adding-or-updating-go-packages-
I ask because I did not see changes to https://github.com/hyperledger/fabric/blob/master/vendor/vendor.json though I may have missed it in the giant list of files.

**Comment by yeasy** [comment]
@srderson Yes, it's updated with govendor.

You can find the latest vendor.json at https://github.com/yeasy/fabric/blob/update_vendor_pkg/vendor/vendor.json.

**Comment by yeasy** [comment]
After checking travis-ci and jenkins logs, no find explicit clue.
Could anyone help to verify?
Thanks!

**Comment by christo4ferris** [comment]
@yeasy see my comment on #2327 regarding transition to Gerrit.

**Comment by gbolo** [comment]
I can confirm that this patch is working as expected with docker 1.12 (api 1.24). Lets get this merged.

**Comment by yeasy** [comment]
Migrated to gerrit, and close it.

**Pull request closed without merging**
