### PR TITLE
 correct some typos and mistakes.

### PR DESCRIPTION
**Pull request by mqshen**
According @yeasy 's suggestion, correct some typos and mistakes. #2114

### CODE REVIEW

**Comment by christo4ferris** [comment]
@yeasy can you please confirm the changes? Is there any other feedback that needs to be addressed?

**Comment by yeasy** [comment]
@christo4ferris 
Yes, I'm rechecking these days. To help guarantee the quality, I'm also asking other hyperledger guys in China to help the check. I will post the feedback ASAP.

By the way, I saw lots of similar requirements to keep a multi-language version of all docs like spec, usage. While currently it's difficult to keep the quality and the updating interval to maintain these works.

Is it necessary to initiate some i18n workgroup to handle these issues?

Welcome for any feedback, thanks!

**Comment by GrapeBaBa** [comment]
@christo4ferris I am all in favor of @yeasy 's suggestion.

**Comment by ckeyer** [comment]
LGTM

**Comment by yeasy** [comment]
Thanks, will reply in email.

**Comment by christo4ferris** [comment]
@yeasy agree that we'll need to consider i18n aspects. I have some ideas.

**Comment by srderson** [comment]
@yeasy are you satisfied with the latest updates?

**Comment by yeasy** [comment]
@christo4ferris Great! Chris, and what's your ideas?

@srderson LGTM. Let's merge this version first and keep syncing with latest doc content. Thanks!

**Comment by srderson** [comment]
@yeasy Thanks!

**Pull request merged**
