### PR TITLE
CA Update.

### PR DESCRIPTION
**Pull request by thkzrl**
- Root path changes to /var/openchain/production (#528)
- ECA double-checks encryption key during certificate creation
- TCAA.ReadCertificateSet implemented
- Added roles to users distinguishing peers, validators, and auditors.

Signed by: Thorsten Kramp thk@zurich.ibm.com

### CODE REVIEW

**Comment by thkzrl** [comment]
Signed-off by: Thorsten Kramp thk@zurich.ibm.com

**Comment by thkzrl** [comment]
Changed common name in certificates to user id. This change has been urgently requested for the forthcoming demo!

Signed-off by: Thorsten Kramp thk@zurich.ibm.com

**Comment by binhn** [comment]
@thkzrl 
I see `Panic.Panicln(err)` and that prompts question whether we handle the error right because it will shutdown the CA and render the entire chain inoperable.  Is that the right thing to do here?

**Comment by thkzrl** [comment]
The CA panics only during startup, that is, when it cannot create its own key pairs or certificates. There was one panic for an impossible error condition left which I've just removed.

**Comment by binhn** [comment]
@thkzrl thanks

**Pull request merged**
