### PR TITLE
Fix proto build

### PR DESCRIPTION
**Pull request by gabre**
## Description

This PR fixes proto build ('make protos') which gave an error cause of a wrong import.
## Motivation and Context

To motivation is to make protos compile again on master.

## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Gabor Hosszu gabor@digitalasset.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
This whole script seems rather klunky to me. Why not simply iterate through every folder under fabric that has .proto files and build them? I note that the example and sdk directory trees are missing from this anyway.

eg.

cd $GOPATH/src/github.com/hyperledger/fabric/
  for f in $(find $GOPATH/src/github.com/hyperledger/fabric/  -name '*.proto'); do
    # Core protos do not depend on each other except the ones which are in the same directory
    d=$(dirname "$f")
    cd "$d"
    protoc --proto_path="$d" --go_out=plugins=grpc:. $f
  done

**Comment by srderson** [comment]
1. We need to run `make protos` as part of Travis so this doesn't happen again
2. @christo4ferris Yes, that would make the most sense, but I encountered the same issues as @gabre. I came up with some other way, but the script difficult to read. I opted to make it more verbose, but readable. Maybe someone can find a better way though.
3. The PR is compiling the protos under `chaincode/shim/java/` to `.pb.go` files which is not correct. They should be Java files. Likely we should skip these for now just to get this script working again?

**Comment by srderson** [comment]
@gabre Did `make protos` work for you? I ran that command and it failed with the following error. I believe we need to skip the SDK also.

```
vagrant@hyperledger-devenv:v0.0.10-c79898b:/opt/gopath/src/github.com/hyperledger/fabric$ make protos
cd gotools && make
make[1]: Entering directory `/opt/gopath/src/github.com/hyperledger/fabric/gotools'
make[2]: Entering directory `/opt/gopath/src/github.com/hyperledger/fabric/gotools'
Building gomega
go get github.com/onsi/gomega
make[2]: Leaving directory `/opt/gopath/src/github.com/hyperledger/fabric/gotools'
make[1]: Leaving directory `/opt/gopath/src/github.com/hyperledger/fabric/gotools'
./devenv/compile_protos.sh
+ protoc --go_out=plugins=grpc:/opt/gopath/src /usr/include/google/protobuf/timestamp.proto
+ protoc --go_out=plugins=grpc:/opt/gopath/src /usr/include/google/protobuf/empty.proto
+ cd /opt/gopath/src/github.com/hyperledger/fabric/protos
+ protoc --go_out=plugins=grpc:. api.proto chaincodeevent.proto chaincode.proto devops.proto events.proto fabric.proto server_admin.proto
+ cd /opt/gopath/src/github.com/hyperledger/fabric/core/
++ find /opt/gopath/src/github.com/hyperledger/fabric/core/ -name '*.proto'
+ for f in '$(find $GOPATH/src/github.com/hyperledger/fabric/core/  -name '\''*.proto'\'')'
+ protoc --proto_path=/opt/gopath/src/github.com/hyperledger/fabric/core/ --go_out=plugins=grpc:. /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.proto
+ for f in '$(find $GOPATH/src/github.com/hyperledger/fabric/core/  -name '\''*.proto'\'')'
+ protoc --proto_path=/opt/gopath/src/github.com/hyperledger/fabric/core/ --go_out=plugins=grpc:. /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/java/src/main/proto/chaincode.proto
chaincodeevent.proto: File not found.
chaincode/shim/java/src/main/proto/chaincode.proto: Import "chaincodeevent.proto" was not found or had errors.
chaincode/shim/java/src/main/proto/chaincode.proto:158:5: "ChaincodeEvent" is not defined.
make: *** [protos] Error 1
vagrant@hyperledger-devenv:v0.0.10-c79898b:/opt/gopath/src/github.com/hyperledger/fabric$ 
vagrant@hyperledger-devenv:v0.0.10-c79898b:/opt/gopath/src/github.com/hyperledger/fabric$ 
vagrant@hyperledger-devenv:v0.0.10-c79898b:/opt/gopath/src/github.com/hyperledger/fabric$ 
vagrant@hyperledger-devenv:v0.0.10-c79898b:/opt/gopath/src/github.com/hyperledger/fabric$ 
vagrant@hyperledger-devenv:v0.0.10-c79898b:/opt/gopath/src/github.com/hyperledger/fabric$ 
vagrant@hyperledger-devenv:v0.0.10-c79898b:/opt/gopath/src/github.com/hyperledger/fabric$ make protos
cd gotools && make
make[1]: Entering directory `/opt/gopath/src/github.com/hyperledger/fabric/gotools'
make[2]: Entering directory `/opt/gopath/src/github.com/hyperledger/fabric/gotools'
Building gomega
go get github.com/onsi/gomega
make[2]: Leaving directory `/opt/gopath/src/github.com/hyperledger/fabric/gotools'
make[1]: Leaving directory `/opt/gopath/src/github.com/hyperledger/fabric/gotools'
./devenv/compile_protos.sh
+ cd /opt/gopath/src/github.com/hyperledger/fabric/
++ find . -name '*.proto'
+ ALL_PROTO_FILES='./consensus/pbft/messages.proto
./core/chaincode/shim/chaincode.proto
./core/chaincode/shim/java/src/main/proto/chaincode.proto
./core/chaincode/shim/java/src/main/proto/chaincodeevent.proto
./core/crypto/attributes/proto/attributes.proto
./examples/chaincode/go/utxo/util/dah.proto
./membersrvc/protos/ca.proto
./protos/api.proto
./protos/chaincode.proto
./protos/chaincodeevent.proto
./protos/devops.proto
./protos/events.proto
./protos/fabric.proto
./protos/server_admin.proto
./sdk/node/lib/protos/google/protobuf/empty.proto
./sdk/node/lib/protos/google/protobuf/timestamp.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/protoify/json.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/websocket/www/example.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/src/google/protobuf/descriptor.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/annotations.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/camelcase.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/comments.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/complex.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/custom-options.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport/common.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport/dep1.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport/dep2.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport/main.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example1.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example1u.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example2.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example3.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example4.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example5.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/extend.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/field_name_same_as_package/main.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/field_name_same_as_package/sub.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/google/protobuf/descriptor.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/groups.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/gtfs-realtime.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_a.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_a_single_quote.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_b.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_common.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot/file1.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot/file2.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot/file3.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/imports-toplevel.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/imports.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/inner.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/negid.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/numberformats.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/oneof.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/optional.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/options.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/packed.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/PingExample.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto2js/Bar.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto2js/Foo.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto3.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/protobufnet.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/repeated.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/setarray.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/string_single_quote.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/T139.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/T263.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/toplevel.proto
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/x64.proto
./sdk/node/node_modules/grpc/src/proto/grpc/health/v1/health.proto
./sdk/node/node_modules/grpc/src/proto/grpc/lb/v0/load_balancer.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/control.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/duplicate/echo_duplicate.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/echo.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/echo_messages.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/empty.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/messages.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/metrics.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/payloads.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/perf_db.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/services.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/stats.proto
./sdk/node/node_modules/grpc/src/proto/grpc/testing/test.proto
./sdk/node/node_modules/grpc/src/proto/math/math.proto'
++ uniq
++ dirname ./consensus/pbft/messages.proto ./core/chaincode/shim/chaincode.proto ./core/chaincode/shim/java/src/main/proto/chaincode.proto ./core/chaincode/shim/java/src/main/proto/chaincodeevent.proto ./core/crypto/attributes/proto/attributes.proto ./examples/chaincode/go/utxo/util/dah.proto ./membersrvc/protos/ca.proto ./protos/api.proto ./protos/chaincode.proto ./protos/chaincodeevent.proto ./protos/devops.proto ./protos/events.proto ./protos/fabric.proto ./protos/server_admin.proto ./sdk/node/lib/protos/google/protobuf/empty.proto ./sdk/node/lib/protos/google/protobuf/timestamp.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/protoify/json.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/websocket/www/example.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/src/google/protobuf/descriptor.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/annotations.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/camelcase.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/comments.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/complex.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/custom-options.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport/common.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport/dep1.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport/dep2.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport/main.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example1.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example1u.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example2.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example3.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example4.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example5.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/extend.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/field_name_same_as_package/main.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/field_name_same_as_package/sub.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/google/protobuf/descriptor.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/groups.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/gtfs-realtime.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_a.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_a_single_quote.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_b.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_common.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot/file1.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot/file2.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot/file3.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/imports-toplevel.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/imports.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/inner.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/negid.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/numberformats.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/oneof.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/optional.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/options.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/packed.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/PingExample.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto2js/Bar.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto2js/Foo.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto3.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/protobufnet.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/repeated.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/setarray.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/string_single_quote.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/T139.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/T263.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/toplevel.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/x64.proto ./sdk/node/node_modules/grpc/src/proto/grpc/health/v1/health.proto ./sdk/node/node_modules/grpc/src/proto/grpc/lb/v0/load_balancer.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/control.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/duplicate/echo_duplicate.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/echo.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/echo_messages.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/empty.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/messages.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/metrics.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/payloads.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/perf_db.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/services.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/stats.proto ./sdk/node/node_modules/grpc/src/proto/grpc/testing/test.proto ./sdk/node/node_modules/grpc/src/proto/math/math.proto
++ sort
+ PROTO_DIRS='./consensus/pbft
./core/chaincode/shim
./core/chaincode/shim/java/src/main/proto
./core/crypto/attributes/proto
./examples/chaincode/go/utxo/util
./membersrvc/protos
./protos
./sdk/node/lib/protos/google/protobuf
./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/protoify
./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/websocket/www
./sdk/node/node_modules/grpc/node_modules/protobufjs/src/google/protobuf
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/field_name_same_as_package
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/google/protobuf
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto2js
./sdk/node/node_modules/grpc/src/proto/grpc/health/v1
./sdk/node/node_modules/grpc/src/proto/grpc/lb/v0
./sdk/node/node_modules/grpc/src/proto/grpc/testing
./sdk/node/node_modules/grpc/src/proto/grpc/testing/duplicate
./sdk/node/node_modules/grpc/src/proto/math'
++ printf '%s\n' ./consensus/pbft ./core/chaincode/shim ./core/chaincode/shim/java/src/main/proto ./core/crypto/attributes/proto ./examples/chaincode/go/utxo/util ./membersrvc/protos ./protos ./sdk/node/lib/protos/google/protobuf ./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/protoify ./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/websocket/www ./sdk/node/node_modules/grpc/node_modules/protobufjs/src/google/protobuf ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/field_name_same_as_package ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/google/protobuf ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto2js ./sdk/node/node_modules/grpc/src/proto/grpc/health/v1 ./sdk/node/node_modules/grpc/src/proto/grpc/lb/v0 ./sdk/node/node_modules/grpc/src/proto/grpc/testing ./sdk/node/node_modules/grpc/src/proto/grpc/testing/duplicate ./sdk/node/node_modules/grpc/src/proto/math
++ grep -v java/src
+ PROTO_DIRS_WITHOUT_JAVA='./consensus/pbft
./core/chaincode/shim
./core/crypto/attributes/proto
./examples/chaincode/go/utxo/util
./membersrvc/protos
./protos
./sdk/node/lib/protos/google/protobuf
./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/protoify
./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/websocket/www
./sdk/node/node_modules/grpc/node_modules/protobufjs/src/google/protobuf
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/dupimport
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/field_name_same_as_package
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/google/protobuf
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/importRoot
./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto2js
./sdk/node/node_modules/grpc/src/proto/grpc/health/v1
./sdk/node/node_modules/grpc/src/proto/grpc/lb/v0
./sdk/node/node_modules/grpc/src/proto/grpc/testing
./sdk/node/node_modules/grpc/src/proto/grpc/testing/duplicate
./sdk/node/node_modules/grpc/src/proto/math'
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./consensus/pbft --go_out=plugins=grpc:. ./consensus/pbft/messages.proto
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./core/chaincode/shim --go_out=plugins=grpc:. ./core/chaincode/shim/chaincode.proto
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./core/crypto/attributes/proto --go_out=plugins=grpc:. ./core/crypto/attributes/proto/attributes.proto
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./examples/chaincode/go/utxo/util --go_out=plugins=grpc:. ./examples/chaincode/go/utxo/util/dah.proto
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./membersrvc/protos --go_out=plugins=grpc:. ./membersrvc/protos/ca.proto
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./protos --go_out=plugins=grpc:. ./protos/api.proto ./protos/chaincodeevent.proto ./protos/chaincode.proto ./protos/devops.proto ./protos/events.proto ./protos/fabric.proto ./protos/server_admin.proto
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./sdk/node/lib/protos/google/protobuf --go_out=plugins=grpc:. ./sdk/node/lib/protos/google/protobuf/empty.proto ./sdk/node/lib/protos/google/protobuf/timestamp.proto
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/protoify --go_out=plugins=grpc:. ./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/protoify/json.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: json.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/websocket/www --go_out=plugins=grpc:. ./sdk/node/node_modules/grpc/node_modules/protobufjs/examples/websocket/www/example.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: example.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./sdk/node/node_modules/grpc/node_modules/protobufjs/src/google/protobuf --go_out=plugins=grpc:. ./sdk/node/node_modules/grpc/node_modules/protobufjs/src/google/protobuf/descriptor.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: descriptor.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
+ for d in '$PROTO_DIRS_WITHOUT_JAVA'
+ protoc --proto_path=./sdk/node/node_modules/grpc/node_modules/protobufjs/tests --go_out=plugins=grpc:. ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/annotations.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/camelcase.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/comments.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/complex.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/custom-options.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example1.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example1u.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example2.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example3.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example4.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/example5.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/extend.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/groups.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/gtfs-realtime.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_a.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_a_single_quote.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_b.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/import_common.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/imports.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/imports-toplevel.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/inner.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/negid.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/numberformats.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/oneof.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/optional.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/options.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/packed.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/PingExample.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/proto3.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/protobufnet.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/repeated.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/setarray.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/string_single_quote.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/T139.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/T263.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/toplevel.proto ./sdk/node/node_modules/grpc/node_modules/protobufjs/tests/x64.proto
annotations.proto:26:8: "google.protobuf.MethodOptions" is not defined.
make: *** [protos] Error 1
```

**Comment by gabre** [comment]
For me, it worked. I will check it.
Edit: after building sdk, there are some proto files in ./sdk - so yes, blacklisting that is needed.

**Comment by srderson** [comment]
@gabre I ran with the updates. It looks like it now compiles the correct proto files, but it outputs the `pb.go` in the incorrect spot. Here are the commands I ran

```
cd $GOPATH/src/github.com/hyperledger/fabric
make protos
```

The `pb.go` files are all placed under the `$GOPATH/src/github.com/hyperledger/fabric` directory. Instead, each `pb.go` needs to be placed in the same location as its associated `.proto` file. This would match the behavior of the current script.

**Comment by ghaskins** [comment]
Sorry for late response, just getting back online from a vacation.

Generally, I am a little concerned with the direction.  The better solution as @christo4ferris mentioned would be to get rid of the script and use the makefile for this.  This was the intention all along anyway, but it just hasn't been a priority.

The way I would do it is something along the lines of having the modules in question depend on the output (e.g. pb.go) with a compiler directive for how to formulate the output from the input.  Has this been considered?

**Comment by gabre** [comment]
@ghaskins At first, I just tried to add a quick&notsodirty solution. Of course, we can use Makefile for this, but that needs some greater effort IMO.

**Comment by gabre** [comment]
@srderson now, it seems to generate the protos to the proper place.

**Comment by christo4ferris** [comment]
I agree with @ghaskins concerns. But, if this is working, let's merge and open an issue to address in the Makefile.

**Comment by srderson** [comment]
Thanks @gabre. I pulled the fix locally and the generated `.pb.go` look slightly different. I'm running tests builds/tests locally to confirm there are no issues.

**Comment by srderson** [comment]
I needed to change the package name of the `dah.proto` file in the UTXO example. Otherwise after running this script using `make protos`, you will receive a compile error using make to build. I did this in PR #2224 which also includes the update `pb.go` files. They really just contain changes in the auto generated comments. 

@ghaskins could you look at merging PR #2224?

Once that is merged, people will be able to run this script and compile. I'll merge this PR now as the current script is broken anyway.

Thanks @gabre for resolving this!

@gabre @ghaskins @christo4ferris I agree with looking at moving to the make file in a future PR.

**Pull request merged**
