### PR TITLE
minor fix to block-listener to adapt to events api change

### LINKED ISSUE #1818: block-listener code broken
## Description

I'm getting the following error when trying to build the block listener with this morning's git pull:

./block-listener.go:37: cannot use "block" (type string) as type protos.EventType in field value
./block-listener.go:37: unknown protos.Interest field 'ResponseType' in struct literal
## Describe How to Reproduce

cd to `examples/events/block-listener`

`go build`

### PR DESCRIPTION
**Pull request by pmullaney**
## Description

very minor change to block-listener to adapt to api change
## Motivation and Context

Fixes #1818 
## How Has This Been Tested?

ran block-listener againt peer to see that it logs block events

minor
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Patrick Mullaney pm.mullaney@gmail.com

### CODE REVIEW

**Comment by srderson** [comment]
@jimthematrix could you please verify? Thanks.

**Comment by jimthematrix** [comment]
@srderson  I verified that the fix in the PR worked.
@pmullaney thanks for submitting the fix

**Comment by srderson** [comment]
Thanks, LGTM

**Comment by srderson** [comment]
Travis failure is 680 which was disabled in a later PR.

**Pull request merged**
