### PR TITLE
[ci skip] update glossary

### PR DESCRIPTION
**Pull request by frankyclu**
add new key terms and definitions to the glossary list

DCO1.1 Signed-off-by Frank Lu fylu@us.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
@frankyclu Please add [ci skip] to your comment in future doc only changes. This will prevent the travis build from running. Thanks

**Comment by joshhus** [comment]
A few quick examples would be helpful adds to the definitions. e.g. Chain Member examples: NVN? etc. (... What are some example "entities" that fit the description.)

**Comment by joshhus** [comment]
For Network owners, maybe avoid "full member" ... confusing compared to just a "member"? ... perhaps define a Network owner simply as a VN owner.

**Comment by joshhus** [comment]
Please tweak: "Approval from network owner is required when adding or deleting a participant with ownership right" to: "Approval from a network owner is required when adding or deleting a participant with ownership rights." (I guess a participant with ownership rights = an owner.) ... Note this is kind of interesting; could a nefarious owner, on his own, keep adding nefarious owners to the point of influencing consensus?

**Comment by joshhus** [comment]
So Owner and Member registration also involves "inviting" whereas User reg. does not involve "inviting." ... Sounds reasonable. Does the inviting come after the registration, as presented?

**Comment by joshhus** [comment]
Finally, for the transaction defs. - so a "Public Transaction" is not a chaincode transaction? What kind of code is it? .... (as compared to a Confidential Chaincode Transaction). Thanks!

**Comment by christo4ferris** [comment]
Network Owner seems an odd term, since there can and likely will be multiples. I would think Stakeholder would be more suitable term. At the end of the day, they are Validators. Also, should there be a heirarchy? e.g. a Network Stakeholder is also a Network Member, etc.

**Comment by srderson** [comment]
@frankyclu You also need to sign off on this PR. Thanks.

**Comment by christo4ferris** [comment]
@frankyclu there are also a few vestigial references to "OBC" in the glossary that should be changed to "Hyperledger Fabric". Also, there is a parenthetical reference to "the Dev team" which should be removed.

**Comment by frankyclu** [comment]
@joshhus 
1) updated the sentence, I modified a few words to reflect the fact that "for a new owner to be added to co-own a network, existing members must agree"
2) yes, inviting come after the registration (someone has to setup the network first before new members can be added)
3) I added a new paragraph "confidential transaction" to differentiate the difference between that and "confidential chaincode transaction"

@christo4ferris 
1) I updated a few words and hopefully it will make it more clear (to point out there could be multiple "owners". 

I think the word "owner"  is better because for some would all members that transact on a network are technically "stakeholders" of that network (e.g. bitcoin owners have a stake in the bitcoin network although they don't run full nodes

2) done, replaced OBC with hyperledger fabric

**Comment by joshhus** [comment]
Do you folks think we should move the "terminology" section of prot-spec to the "glossary". I see prot-spec being split up eventually also anyway: e.g. into a separate security doc. We could open Issues for these for the community. 

I agree that Network Owner is sort of, well, is it a necessary concept; can we do better with another term. e.g. what do we really mean; isn't it just an owner of a VN/VP.

**Comment by joshhus** [comment]
If we keep Network Owner, let's add a clear definition of that to glossary. ty.

**Pull request merged**
