### PR TITLE
Remove deploy payload from blocks for events/api. Issue #518

### PR DESCRIPTION
**Pull request by srderson**
For issue #518. The goal is to make events and the REST API a bit more lightweight by removing the payload from deploy transactions when blocks are retrieved. If the user wishes to retrieve the payload, they can access the transaction directly via UUID.

@angrbrd @manish-sethi @muralisrini please review. Thanks.

### CODE REVIEW

**Comment by srderson** [comment]
Signed-off-by: sheehan@us.ibm.com

**Comment by muralisrini** [comment]
@srderson : looks good to me. Not pulling this in case others wants to review and test.

**Comment by muralisrini** [comment]
moved to @angrbrd for review / test

**Comment by angrbrd** [comment]
I have taken a look at the code and it makes sense to me. Though, I will wait for @srderson to address the issue that @rameshthoomu just opened with the behave test failing before I merge. Thanks.

**Comment by srderson** [comment]
It's a timeout which I hit all the time on my machine. I increased the timeouts in PR #634

**Comment by angrbrd** [comment]
Thank you @srderson for the clarification. @rameshthoomu, please keep PR #634 in mind and retest after it has been merged. Thanks.

**Pull request merged**
