### PR TITLE
Workaround for Issue 1234

### PR DESCRIPTION
**Pull request by bcbrock**
Please see #1234 for the rationale behind this change.

Signed-off-by: Bishop Brock bcbrock@us.ibm.com

### CODE REVIEW

**Comment by bcbrock** [comment]
Where are the peer logs from the Behave tests? I don't believe my changes are causing this failure.

**Comment by binhn** [comment]
@rameshthoomu could you help @bcbrock locate the logs

**Comment by christo4ferris** [comment]
I think that the logs are still a TBD - we need to upload to objectstore and display the URL to fetch them

**Comment by srderson** [comment]
LGTM. Manually confirmed tests are passing.

**Pull request merged**
