### PR TITLE
Improved core/crypto/* tests

### PR DESCRIPTION
**Pull request by adecaro**
## Description

This PR improves on the tests of the core/crypto/\* packages. It builds up on top of PR #1717 and #1698 and can be accepted after or in place of them.
## Motivation and Context

Improving test coverage and stress tests. 
## How Has This Been Tested?

By running the tests included.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Angelo De Caro adc@zurich.ibm.com

### CODE REVIEW

**Comment by binhn** [comment]
LGTM but pending #1717

**Comment by binhn** [comment]
@adecaro I thought I could merge it after #1717 but apparently not. Could you resolve conflicts

**Comment by binhn** [comment]
thanks

**Comment by andresgaragiola** [comment]
@adecaro I'm seeing commented some tests that I had added in this PR. For example I had added a scenario to test multi thread tcert pooll and I'm seeing that commented right now [here](https://github.com/hyperledger/fabric/blob/master/core/crypto/crypto_test.go#L83#L122). Do you know if this is a mistake or there are a reason to comment this tests?

**Pull request merged**
