### PR TITLE
Confidentiality 1.2

### PR DESCRIPTION
**Pull request by adecaro**
This PR introduces a new security model for the confidentiality of the transactions stored on the blockchain. In the previous version of confidentiality, all the users, registered to the membership service, were able to decrypt the content of the blockchain. Now, only the validators can do that. If a chaincode deployer or invoker wants to explicitly disclose part of the information stored in the transactions she has generated, the deployer or invoker has to do that by using the metadata field.

Notice that access control policies and mechanisms are not affected by this PR. This is an intermediate step forward to reach the full version of confidentiality the we are planning to release.

Signed-off-by: Angelo De Caro adc@zurich.ibm.com

### CODE REVIEW

**Comment by adecaro** [comment]
Signed-off-by: Angelo De Caro adc@zurich.ibm.com

**Comment by muralisrini** [comment]
@adecaro : ran unit tests without issues
go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor/) 1> /tmp/out 2>&1

Running behave after that produces these errors

Failing scenarios:
  peer_basic.feature:132  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.1 Consensus Options
  peer_basic.feature:133  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.2 Consensus Options
  peer_basic.feature:134  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.3 Consensus Options
  peer_basic.feature:135  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.4 Consensus Options
  peer_basic.feature:216  chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.1 Consensus Options
  peer_basic.feature:217  chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.2 Consensus Options
  peer_basic.feature:218  chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.3 Consensus Options
  peer_basic.feature:344  4 peers and 1 obcca, consensus still works if one backup replica fails -- @1.1 Consensus Options
  peer_basic.feature:345  4 peers and 1 obcca, consensus still works if one backup replica fails -- @1.2 Consensus Options
  peer_basic.feature:346  4 peers and 1 obcca, consensus still works if one backup replica fails -- @1.3 Consensus Options
  peer_basic.feature:406  4 peers and 1 obcca, consensus fails if 2 backup replicas fail -- @1.1 Consensus Options
  peer_basic.feature:407  4 peers and 1 obcca, consensus fails if 2 backup replicas fail -- @1.2 Consensus Options
  peer_basic.feature:408  4 peers and 1 obcca, consensus fails if 2 backup replicas fail -- @1.3 Consensus Options
  peer_basic.feature:451  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.1 Consensus Options
  peer_basic.feature:452  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.2 Consensus Options
  peer_basic.feature:453  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.3 Consensus Options

0 features passed, 1 failed, 0 skipped
4 scenarios passed, 16 failed, 1 skipped
44 steps passed, 16 failed, 312 skipped, 0 undefined

Can you try at your end ? Perhaps rebase to make sure recent changes are picked up ?

**Comment by adecaro** [comment]
@muralisrini, actually, I can see the same errors but I'm not able to get the logs. Where are they?

**Comment by binhn** [comment]
@tuand27613 @jeffgarratt would this change require any mods on the behave tests? The failure messages are not clear to me

**Comment by muralisrini** [comment]
@binhn, @adecaro was able to recreate and has identified some issues. Just fyi...

good thought about adding behave tests stemming from that investigation.

**Comment by adecaro** [comment]
@muralisrini now there is only one scenario that fails:

Failing scenarios:
  peer_basic.feature:278  chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.3 Consensus Options

The reason for the failure is the following:

Assertion Failed: Failed to POST to http://172.17.0.5:5000/devops/query:  {"Error": "Error:Failed to execute transaction or query({'Error':'Nil amount for a'})"}

But it fails also on the current master. Yesterday, the master did not fail. 
I have the output of the execution, just in case.

@jeffgarratt @binhn @tuand27613  Still, we need a way to access the logs when there is an error.

**Comment by tuand27613** [comment]
The behave error you see is #739. @jyellick and @corecode are looking at potential solutions.
I'll look at how to get the docker logs when a test fails.

It's a bit painful for now but if you can isolate to a single test, run it by itself , tell it to not decompose the docker images ( set the tags _DoNotDecompose_ and _wip_ , run as `behave -w` ) then you can get the logs via `docker-compose logs` which sends them all to the console or `docker logs container_name` for individual ones

**Comment by binhn** [comment]
so it looks like the failures are caused by something else. I am merging this PR

**Pull request merged**
