### PR TITLE
Fixing Issue 1975

### LINKED ISSUE #1975: make node-sdk-unit-tests fails: panic: Cannot parse block timeout: time: invalid duration
## Description

Environment:  windows 7 -> virtualbox -> gitbash -> vagrant 
Ramesh Thoomu and I both see this failure running make node-sdk-unit-tests:

_<lines deleted>_ 
member services is started
Begin running tests in net mode ...
**ERROR: peer failed to start; see /tmp/node-sdk-unit-test/peer.log**

So we find this in peer.log:
=============================begin peer.log excerpt==============================
18:20:06.401 [consensus/controller] NewConsenter -> INFO 013^[[0m Creating default consensus plugin (noops)
panic: Cannot parse block timeout: time: invalid duration

goroutine 1 [running]:
panic(0xd2f5e0, 0xc8203e0d20)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/consensus/noops.newNoops(0x2ac81e8506a0, 0xc8203ca200, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/consensus/noops/noops.go:76 +0x956
github.com/hyperledger/fabric/consensus/noops.GetNoops(0x2ac81e8506a0, 0xc8203ca200, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/consensus/noops/noops.go:55 +0x48
github.com/hyperledger/fabric/consensus/controller.NewConsenter(0x2ac81e8506a0, 0xc8203ca200, 0x0, 0x0)
                                               28,2-9        42%
===================end peer.log excerpt =================================

Ramesh switched to an earlier commit, and the tests succeeded.  This is the commit that seems to cause the error: 2ad27bd

Entire peer.log  
[peer.zip](https://github.com/hyperledger/fabric/files/330639/peer.zip)
## Describe How to Reproduce

1.From Gitbash, synchronize your laptop with the latest level 
2.vagrant up
3.vagrant ssh
4.cd into 'fabric'.  For example, cd /opt/gopath/src/github.com/hyperledger/fabric
5.make node-sdk-unit-tests

### PR DESCRIPTION
**Pull request by angrbrd**
## Description

This change addresses issue #1975 , which was causing a runtime panic when running Node sdk unit tests with `make node-sdk-unit-tests`.
## Motivation and Context

The two commits here are required to address issue #1975. The two changes are as follows.

Firstly, the "make node-sdk-unit-tests" spins up a peer and membersrvc to run the tests against, but it did not check whether the executables should be rebuilt to update them. This resulted in the tests running agains an oder version of the peer, which has since then been updated. This was causing the panic, as the peer consensus code was looking for a setting that was no longer in the .yaml. Therefore, the Makefile was modified to rebuild the peer and membersrvc executables prior to running the unit tests.

Secondly, during the Node sdk work, it appears that two temporary (transient) files were accidentally checked into the repo. This was causing git ls-files to pick them in the list of build dependencies. It looks like these two files are later deleted in the build process (as it appears in the git repo afterwards through `git status`) and this causes the peer build to fail. Therefore, these temporary files are now being removed from the repo, as they should have never been checked in.

Fixes #1975 
## How Has This Been Tested?

You can now run `make node-sdk-unit-tests` and everything passes with no panic.
## Checklist:
- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

The continuous integration build process will run [make checks](https://github.com/hyperledger/fabric/blob/master/Makefile#L22) to confirm that tests pass and that code quality meets minimum standards. You may optionally run this locally as PRs will not be accepted until they pass.

Signed-off-by: Anna D Derbakova adderbak@us.ibm.com

### CODE REVIEW

**Comment by ghaskins** [comment]
LGTM

**Comment by ghaskins** [comment]
@srderson @binhn possible candidate for developer-preview merge?

**Comment by angrbrd** [comment]
@ghaskins @srderson @binhn 

Yes, this definitely needs to go into the developer-preview merge. Please let me know what the process is and I will open another PR to that branch. Thanks.

**Comment by srderson** [comment]
I tagged the issue. You just need to open a second PR against the other branch.

**Comment by angrbrd** [comment]
Thanks, @srderson. Will do shortly.

**Pull request merged**
