### PR TITLE
Clarify maintainer process

### PR DESCRIPTION
**Pull request by christo4ferris**
## Description

clarify process for removing a maintainer
## Motivation and Context

documented process did not cover removal of a maintainer
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Christopher Ferris chrisfer@us.ibm.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
note that I believe it appropriate for a majority of the maintainers to agree on this PR. @srderson @binhn @tamasblummer @ghaskins

**Comment by srderson** [comment]
+1

**Comment by christo4ferris** [comment]
+1

**Comment by tamasblummer** [comment]
+1

**Comment by christo4ferris** [comment]
migrated PR to Gerrit, closing

**Comment by ghaskins** [comment]
FWIW, +1

**Pull request closed without merging**
