### PR TITLE
No complaints preview PR

### LINKED ISSUE #1091: REST API /chain/blocks/<n> returns empty blocks (other than block 0)
This issue is observed in conjunction with another error case, see #920. When a test program makes the REST API call /chain/blocks/<n>, it gets a normal HTTP response but the data is NULL, i.e., the block has no transactions. I don't think this makes sense except for the genesis block. This issue is observed in

```
commit 92cc78029d04736928c3c07b7c3336023de2d747
Merge: c4b31f9 96210ef
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Sun Apr 10 21:17:43 2016 -0400

    Merge pull request #1044 from ghaskins/rebrand
```

and is easy to reproduce if required.

@jyellick offered the following opinion in #920:

  My suspicion is that the peer is currently performing state transfer and so his block height does not    necessarily match the number of blocks he has. This is probably fooling the error checking that exists at that layer which assumes the chain is always unbroken.

  I think we need to think about a policy for more clearly handling requests when a replica knows its state is not complete. Do we make a best effort to return a correct result? Do we reject all queries? This seems like it should be a well studied problem, maybe <at>chetmurthy could weigh in?

### PR DESCRIPTION
**Pull request by jyellick**
## Description

This changeset is targeted at eliminating bugs discovered while working through the busywork stress2b test.  

First, this changeset removes the old custody framework from batch, and replaces it with a much simpler broadcast and retain mechanism.

Secondly, this changeset fixes several state transfer logic related bugs and consolidates this logic into one location in the code.

This PR is built on top of #1785, so please consider only the newer commits in your review for this PR.
## Motivation and Context

The more sophisticated custody framework introduced which included deduplication, and selective broadcast of complaints is a technically superior solution, but delicate and difficult to implement.  There were several outstanding bugs, such as requests not being removed from custody when they should be, as well as the potential for some replicas to choose to include requests, and others to not, forking the blockchain.  In the future, hopefully the more robust complaints framework can be re-introduced, but until that time, this changeset considerably reduces the bug surface.

The state transfer logic was separated into multiple pieces of PBFT, and so changes to the logic required propagating it into all relevant pieces.  This was error prone and resulted in bugs, like not flagging state as invalid after a view change initiating state transfer, and increased the bug surface for conflicts like initiating state transfer during an execution.  Consolidating the logic makes for cleaner, and more visibly correct code.

Fixes #1091 
## How Has This Been Tested?

This PR contains new unit tests for the naive custody logic, as well as new unit tests for the PBFT state transfer behavior.  This code has been tested to consistently pass the busywork `stress2b` test.

The failures discovered in the busywork tests were each converted into the unit tests mentioned above.
## Checklist:
- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [X] Either no new documentation is required by this change, OR I added new documentation
- [X] Either no new tests are required by this change, OR I added new tests
- [X] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Jason Yellick jyellick@us.ibm.com

---

This PR was originally submitted as a preview, not ready for inclusion, below is the original text of this PR.

This pull request is intended as a preview for stability, especially for @bcbrock in regards to issue #1091.

There were several outstanding bugs in the logic of the complaints code, so this changeset removes it entirely from the logic flow of batch in favor of a much simpler broadcast and store outstanding policy.

Running the busywork stress2b test, things still don't complete successfully, but the block with no transaction bug seems to be gone, as does the 'null' block.  I'm hoping that @bcbrock can give some additional insight.

I get errors like:

```
driver:ERROR: Peer 0.0.0.0:34498 : Count mismatch for chaincode cc0, array a1.
Expected 10000, Reported 9998 9997
driver:ERROR: Peer 0.0.0.0:53581 : Count mismatch for chaincode cc0, array a1.
Expected 10000, Reported 340 7130
driver:ERROR: Aborting due to errors, mismatches or disagreements above
make: *** [stress2b] Error 1
```

which I think may be because executions and state transfer are still occurring.

Some of the assorted bugs that were fixed via the view change state transfer need test cases added yet, as does the new naive broadcast and resubmission system, so this PR is not ready to be merged yet, but is intended to be visible for review, especially from @corecode @tuand27613 and @kchristidis.

DCO signoff intentionally omitted for now.

### CODE REVIEW

**Comment by jyellick** [comment]
Just as an update, re-ran busywork stress2b, and got the following which looks like success:

```
checkAgreement: Blockchain logs will be written into /home/vagrant/.busywork
checkAgreement: Logging 0.0.0.0:49826 into /home/vagrant/.busywork/0.0.0.0:49826.chain
checkAgreement: Logging 0.0.0.0:32824 into /home/vagrant/.busywork/0.0.0.0:32824.chain
checkAgreement: Logging 0.0.0.0:53482 into /home/vagrant/.busywork/0.0.0.0:53482.chain
checkAgreement: Logging 0.0.0.0:45529 into /home/vagrant/.busywork/0.0.0.0:45529.chain
checkAgreement: Checking agreement
checkAgreement: Checking for duplicates in file /home/vagrant/.busywork/0.0.0.0:45529.chain
checkAgreement:   10003 Blocks; 1 Deploys; 10001 Invokes
checkAgreement: All peers agree; All log files have been deleted
driver: Terminating normally
```

**Comment by bcbrock** [comment]
@jyellick - Yes, that looks like success. I'll try this out over the weekend. Thanks!

**Comment by christo4ferris** [comment]
reverify Jenkins

**Comment by bcbrock** [comment]
@jyellick I'm trying your no-complaints-preview branch on my system. With PBFT batch it seems to "hang". Here are the logs:

[logs.tar.gz](https://github.com/hyperledger/fabric/files/312001/logs.tar.gz)

FWIW, Sieve is still working.

**Comment by jyellick** [comment]
@bcbrock Which commit level of this PR is it? If you pulled it Friday, there were some fixes that went in since.

Also, which busywork test is this? Looking at the logs now, ~~but without DEBUG logging enabled, it is unlikely to reveal the problem.~~ my mistake, I see they are at debug, they were so small I thought INFO only.

**Comment by jyellick** [comment]
Sorry for all the commits, after rebase after rebase, and a few bug fixes, it's getting to look a little crufty.  Let me know if you'd like me to go back and try to re-curate this.

**Comment by srderson** [comment]
@jyellick no problem, I can squash when I merge. Unfortunately it looks as though this needs to be rebased on master again, perhaps because I merged PR #1785? Also, I'm waiting for @kchristidis to complete his review of this PR.

**Comment by christo4ferris** [comment]
--- FAIL: TestEventTimerSoftReset (0.00s)
    events_test.go:118: Received wrong output (&{two}) from event timer
2016/06/14 14:49:55 Starting timer
2016/06/14 14:49:55 eventLoop told to exit
2016/06/14 14:49:55 Halting timer
2016/06/14 14:49:55 Event timer fired
2016/06/14 14:49:55 Stopping timer
2016/06/14 14:49:55 Timer cleared pending event
FAIL
coverage: 91.2% of statements
FAIL    github.com/hyperledger/fabric/consensus/obcpbft/events  0.209s

**Comment by jyellick** [comment]
Ah, sorry, re-ran the PBFT tests but not the events tests before pushing.  Looks like rebasing clobbered the fix from #1777, fixed and pushed.

**Comment by kchristidis** [comment]
Reviewed and good to go. @srderson

**Comment by srderson** [comment]
@kchristidis Thanks for the review! LGTM

**Pull request merged**
