### PR TITLE
Fix a bunch of go vet issues

### PR DESCRIPTION
**Pull request by srderson**
## Description

Fixes go vet issues reported at https://goreportcard.com/report/github.com/hyperledger/fabric#go_vet
## Motivation and Context

Fix issues reported at https://goreportcard.com/report/github.com/hyperledger/fabric#go_vet
## How Has This Been Tested?

Ran `make checks`. No new tests as there is no new functionality.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Sheehan Anderson sheehan@us.ibm.com

### CODE REVIEW

**Comment by rjones-lf** [comment]
reverify jenkins

**Comment by genggjh** [comment]
Maybe we need consider to add the go_vet examines as a necessary condition in our CI verification. The go vet examines must 100% green before run other tests.

**Comment by srderson** [comment]
Yes, that would be great. I'm working on adding it to the `make linter`. Will have an issue # shortly.

**Comment by genggjh** [comment]
👍

**Comment by srderson** [comment]
See issue #1859. I'm running `make checks` locally and will submit a PR once that is complete.

**Comment by genggjh** [comment]
Great.

**Comment by christo4ferris** [comment]
LGTM thanks!

**Comment by ghaskins** [comment]
LGTM

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Comment by cendhu** [comment]
Yes, @mastersingh24. Due to very minor conflicts, I couldn't use mergify. Already 3/4 cherry-picked PRs got merged and 5 are remaining.

**Pull request merged**
