### PR TITLE
change the slack url according to info from LF

### PR DESCRIPTION
**Pull request by binhn**
We are using the slack self-register URL

### CODE REVIEW

**Comment by binhn** [comment]
Signed-off-by: binh nguyen binhn@us.ibm.com

**Comment by srderson** [comment]
It looks like the space in `[Hyperledger Slack]( https://slack.hyperledger.org/)` is breaking the link. See preview at https://github.com/binhn/fabric/blob/bn-readme/README.md

**Comment by binhn** [comment]
@srderson I removed the space. Thanks.

**Comment by srderson** [comment]
LGTM. Thanks

**Pull request merged**
