### PR TITLE
Update makedoc.sh for typings installation

### LINKED ISSUE #2197: makedoc.sh assumes 'typings' installed
## Description

The node sdk doc makedoc.sh script that generates the node sdk documentation presumes that the user has 'typings' installed. 
## Describe How to Reproduce

try to run https://github.com/hyperledger/fabric/tree/master/sdk/node/makedocs.sh on a system that does not have the 'typings' command installed.

### PR DESCRIPTION
**Pull request by kamraanki**
## Description

makedoc.sh will check typings installed or not. If not, it will install typings.
## Motivation and Context

Fixes #2197 
## How Has This Been Tested?

Tested script on environment with and without, typedoc and typings.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Ankit Kamra [ankitkamra54@gmail.com](mailto:ankitkamra54@gmail.com)

### CODE REVIEW

**Comment by christo4ferris** [comment]
@kamraanki Thanks for submitting this PR. This LGTM, but we have transitioned to Gerrit. Please migrate your PR using  instructions on how to do that posted [here](http://lists.hyperledger.org/pipermail/hyperledger-fabric/2016-July/000168.html), and updated the documentation (staged) to provide Gerrit usage guidance [here](http://cbf-fabric-docs.readthedocs.io/en/latest/CONTRIBUTING/). 

Please close this once you have transferred this PR to Gerrit.

**Comment by angrbrd** [comment]
Hi @kamraanki, I see that this PR has not been merged yet. Please transfer your PR to Gerrit so it can be merged. Thanks!

**Comment by christo4ferris** [comment]
@kamraanki we will be transferring the fabric and fabric-api repository and all the corresponding issues and pull requests to the hyperledger-archives org on GH and replacing this repository with a read-only mirror of our Gerrit source. As a result, any automatic GH redirects will be broken. If you haven't already migrated your PR to Gerrit, and intend to do so, you will need to change your git remote to reference the transferred repository (e.g. git@github.com:hyperledger-archives/fabric) on your local clone.

**Comment by kamraanki** [comment]
@angrbrd @christo4ferris  I am sorry for late reply, I will transfer my PR to Gerrit. Thanks!

**Pull request closed without merging**
