### PR TITLE
Ignore build files

### PR DESCRIPTION
**Pull request by binhn**
## Description

Adding build outputs to `.gitignore` to untrack files.
## Motivation and Context

The build creates some artifacts that result into git untracked files. For example,

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

    build/
    sdk/node/lib/protos/api.proto
    sdk/node/lib/protos/ca.proto
    sdk/node/lib/protos/chaincode.proto
    sdk/node/lib/protos/devops.proto
    sdk/node/lib/protos/events.proto
    sdk/node/lib/protos/fabric.proto
    sdk/node/lib/protos/server_admin.proto
```

This change adds these to the `.gitignore` to untrack these files.
## How Has This Been Tested?

Run a build then enter `git status`; there should be no untracked files.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: binhn@us.ibm.com

### CODE REVIEW

**Comment by ghaskins** [comment]
This would probably be best as localized in the tree (e.g. ./sdk/node/.gitignore) but we also have the sdk build in the top-level makefile which should ideally also move down.  We can clean this up together later, as I don't think it looks too bad as it is.

LGTM

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Comment by mastersingh24** [comment]
> Since our CI does not build each commit, I pulled this down locally to see if each would build independently. It does not look like they do. This will make it harder to bisect or find issues in the future.

Yeah - I realized this.  :(

**Comment by mastersingh24** [comment]
> Since our CI does not build each commit, I pulled this down locally to see if each would build independently. It does not look like they do. This will make it harder to bisect or find issues in the future.


Should be fixed now

**Comment by mastersingh24** [comment]
> Maybe another one @ 38232d7012030d430db2652db3566d6752721b61
> 
> ```
> Executing: ./scripts/run-unit-tests.sh
> # github.com/hyperledger/fabric/bccsp/pkcs11
> bccsp/pkcs11/pkcs11.go:295:2: syntax error: unexpected default, expecting }
> bccsp/pkcs11/pkcs11.go:299:2: syntax error: non-declaration statement outside function body
> ok  	github.com/hyperledger/fabric/bccsp	(cached)	coverage: 63.0% of statements
> FAIL	github.com/hyperledger/fabric/bccsp/factory [build failed]
> ```
> 
> Need to apply this to 38232d7012030d430db2652db3566d6752721b61
> 
> ```diff
> diff --git a/bccsp/pkcs11/pkcs11.go b/bccsp/pkcs11/pkcs11.go
> index ba9793448..cdf7c4dc5 100644
> --- a/bccsp/pkcs11/pkcs11.go
> +++ b/bccsp/pkcs11/pkcs11.go
> @@ -291,12 +291,7 @@ func (csp *impl) getSession() (session pkcs11.SessionHandle, err error) {
>                         // cache is empty (or completely in use), create a new session
>                         return csp.createSession()
>                 }
> -
> -       default:
> -               // cache is empty (or completely in use), create a new session
> -               session, err = createSession(csp.ctx, csp.slot, csp.pin)
>         }
> -       return session, err
>  }
> 
>  func (csp *impl) createSession() (pkcs11.SessionHandle, error) {
> ```
> 
> I rebased on current release-2.2 so my hashes won't match. I believe it's `Add object handle cache to PKCS#11 bccsp provider` or the [94ac63c](https://github.com/hyperledger/fabric/commit/94ac63cb0f9ef42bd0f17cbbc6a7d3f0cffa9382) commit in your tree.

Pulled in the drain sessions change as well

**Comment by sykesm** [comment]
Sorry to do this to you again.

```
Testing with pkcs11...
# github.com/hyperledger/fabric/bccsp/pkcs11 [github.com/hyperledger/fabric/bccsp/pkcs11.test]
bccsp/pkcs11/pkcs11_test.go:1250:2: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1251:2: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1282:2: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1286:2: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1290:2: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1294:2: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1307:3: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1324:3: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1329:2: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1380:2: undefined: assert
bccsp/pkcs11/pkcs11_test.go:1380:2: too many errors
ok  	github.com/hyperledger/fabric/bccsp/factory	6.931s	coverage: 84.8% of statements
FAIL	github.com/hyperledger/fabric/bccsp/pkcs11 [build failed]
FAIL
warning: execution failed: ./scripts/run-unit-tests.sh
You can fix the problem, and then run

  git rebase --continue
```

This is running against the commit for `Make ecPoint a method on impl'

**Pull request merged**
