### PR TITLE
State-hash changes

### PR DESCRIPTION
**Pull request by manish-sethi**
This PR contains following changes
- Fix for unique bytes for trie-node in trie based implementation
- Exposed bucket-hash configurations in yaml file

### CODE REVIEW

**Comment by manish-sethi** [comment]
Signed-off-by:manishsethi@in.ibm.com

**Comment by manish-sethi** [comment]
@srderson - Please have a look if the changes look fine.

**Comment by srderson** [comment]
`numBuckets` and `maxGroupingAtEachLevel` are only applicable to the buckettree, correct? Could you add some additional comments around these to indicate that? Possibly

```
config:

   # configurations for 'bucketree'
   numBuckets:
   maxGroupingAtEachLevel:

   # configurations for 'trie'
   # 'tire' has no additional configurations
```

Also, I think some comments around the `numBuckets` and `maxGroupingAtEachLevel` would be helpful to explain what they do, how potential settings may impact the system, and what the default values are.

**Comment by manish-sethi** [comment]
@srderson - I have added basic description to newly added configurations. 
I'll add more on the impact of these configurations later after having some performance results.

**Comment by srderson** [comment]
Thanks @manish-sethi. Looks good.

**Pull request merged**
