### PR TITLE
obc removed and Transaction types updated

### PR DESCRIPTION
**Pull request by nickgaski**
More instances of OBC removed from prot spec.  Refarch.png updated and Transaction types updated.  New ==> Invoke  Execute ==> Deploy.

Still need to address doc hits that relate to chaincode interface changes:  Init function changed to Run - @ratnakar-asara

### CODE REVIEW

**Comment by nickgaski** [comment]
Signed-off-by:  Nick Gaski - ngaski@us.ibm.com

**Comment by nickgaski** [comment]
@binhn @muralisrini @srderson 

Are there any additional doc hits for Transaction Types (Deploy, Invoke, Query) and the corresponding Chaincode (Init, Invoke, Query) function.  Prot Spec and CoreAPI are only updates so far...

**Comment by srderson** [comment]
Not that I'm aware of. Add @angrbrd as she may know of some, but as the REST API did not change, the doc changes may be somewhat limited.

**Comment by srderson** [comment]
LGTM. Thanks!

**Pull request merged**
