### PR TITLE
Add chaincode event support

### LINKED ISSUE #1129: Custom events design
Ability for chaincode to emit custom events when the transaction it processes has been committed. The existing event consumer framework should be able to listen for these events.

### PR DESCRIPTION
**Pull request by pmullaney**
## Description

This PR provides support for chaincode events called out in issue 1129. It adds the core support to allow chaincode to send events(associated with eventname and payload) and allows the existing consumer client to register and receive those events.
## Motivation and Context

See issue 1129

Fixes #1129
## How Has This Been Tested?

The unit test has been extended to verify that chaincode events and sent and received. An example chaincode is also provided that demonstrates usage.

## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
  *updating wiki right now
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by:Patrick Mullaney pm.mullaney@gmail.com

### CODE REVIEW

**Comment by ghaskins** [comment]
This is great @pmullaney thank you.  Would it be possible to update/add documentation for this?  For instance, I see stub.SetEvent() is a new verb available in the chaincode ABI.  What are the rules governing its behavior?  For instance, will the event only go out to interested parties iff the transaction confirms? Etc.

**Comment by binhn** [comment]
LGTM.  Thanks!

**Comment by binhn** [comment]
@ghaskins From the code, the event will only be sent out iff the transaction (block) successfully committed.

**Comment by muralisrini** [comment]
@pmullaney LGTM!

**Comment by ghaskins** [comment]
@binhn Right, what I meant was: Perhaps there should be a doc/doc-section that explains it?  Maybe it isn't necessary.

**Comment by pmullaney** [comment]
@ghaskins sorry for the late response, I am working on updating the wiki for events right now. We had it in place before starting the coding but we drifted significantly. Its not updated yet but will be here shortly: https://github.com/hyperledger/fabric/wiki/Custom-Events-High-level-specification

**Pull request merged**
