### PR TITLE
Remove Whitespace from README [Do Not Merge]

### PR DESCRIPTION
**Pull request by bramwelt**
## Motivation and Context

Fixes #
## Checklist:

- [] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [] Either no new documentation is required by this change, OR I added new documentation
- [] Either no new tests are required by this change, OR I added new tests
- [] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Trevor Bramwell tbramwell@linuxfoundation.org

Testing Jenkins Integration

### CODE REVIEW

**Comment by bramwelt** [comment]
reverify

**Comment by bramwelt** [comment]
reverify

**Comment by bramwelt** [comment]
reverify

**Comment by bramwelt** [comment]
reverify

**Comment by ghost** [comment]
reverify

**Comment by bramwelt** [comment]
reverify

**Comment by ghost** [comment]
reverify jenkins

**Comment by srderson** [comment]
Closing as there has been no activity for a while. Please reopen if still needed.

**Pull request closed without merging**
