### PR TITLE
Improve the log message - issue #1078

### PR DESCRIPTION
**Pull request by genggjh**

### CODE REVIEW

**Comment by genggjh** [comment]
Signed-off-by: David Geng david@esse.io

**Comment by srderson** [comment]
@genggjh why does this PR include an update to the .gitignore file? Did you include that by accident?

**Comment by genggjh** [comment]
@srderson because the membersrvc binary file which is used for my testing will be included into my path if i do not ignore it in the .gitignore.

**Comment by genggjh** [comment]
If you want I can move the changes into a separate commit.

**Comment by srderson** [comment]
ah, ok. Makes sense. Thanks.

**Comment by genggjh** [comment]
done, @srderson please help to review it again.

**Comment by srderson** [comment]
sorry, was not clear. You were correct. The .gitignore file should include `membersrvc/membersrvc`. Can you please add it back to this PR?

**Comment by srderson** [comment]
never mind, see you created a second PR. That works also.

**Comment by genggjh** [comment]
Yes, I think so 👍

**Comment by srderson** [comment]
LGTM. Thanks!

**Pull request merged**
