### PR TITLE
Add a test for chaincode over HTTP

### LINKED ISSUE #1597: Missing unit-test for HTTP based chaincode
## Description

Chaincode can be specified locally or over HTTP however we currently have no unit-test for the latter.
## Describe How to Reproduce

There currently are no unit test covering getCodeFromHTTP in core/chaincode/platforms/golang/hash.go

### PR DESCRIPTION
**Pull request by lehors**
## Description

This PR adds a unit test to cover the code in getCodeFromHTTP in core/chaincode/platforms/golang/hash.go
The test currently depends on my fork of the project because the code must reside outside the Fabric repo. It would however be better to have it located in a separate repo within the HLP.
See related discussion on PR #1556 and Issue #737.
## Motivation and Context

Fixes #1597
## How Has This Been Tested?

make unit-test
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Arnaud J Le Hors lehors@us.ibm.com

### CODE REVIEW

**Comment by ghaskins** [comment]
@christo4ferris This is the work that originally inspired the question from @lehors about adding a test repository.  Do you have any thoughts here?  If I may summarize the previous/relevant discussion:
1. The unit-test coverage provided here is important, so we don't want to just drop the test.
2. An external URL (!= https://github.com/hyperledger/fabric) is required for the test
3. It would be ideal if this were not tied to a personal github URL since that _could_ theoretically disappear inadvertently without consensus and/or control of HL/LF.
4. In this case, @lehors URL is probably more stable than an arbitrary URL because he understands it needs to be kept around indefinitely and is motivated to keep the system working.

Assuming we all agree with (1) and (2), we just need to decide between (3) and (4).

**Comment by christo4ferris** [comment]
@ghaskins @lehors ah, so the example chaincode needs to be external to hyperledger/fabric, but the test is fine where it is? I have no problem with a repo for that. Just ask @ryjones and he can hook you up. Have the new repo added to the hyperledger "fabric maintainers" team.

**Comment by ghaskins** [comment]
@christo4ferris That is correct.  Unit-test itself will be as this PR patch indicates.  External repo will just hold an example chaincode.  Propose hyperledger/fabric-test.

**Comment by ghaskins** [comment]
Thank you for going the extra mile to get this coverage in.

LGTM

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Pull request merged**
