### PR TITLE
address issue #1009

### PR DESCRIPTION
**Pull request by christo4ferris**
address issue #1009 by adding MAINTAINERS.txt

### CODE REVIEW

**Comment by christo4ferris** [comment]
Signed-off-by: Christopher Ferris chrisfer@us.ibm.com

**Comment by srderson** [comment]
LGTM. Is @rfajta choosing not to provide his email or do you need me to send it to you?

**Comment by christo4ferris** [comment]
I didn't have it. Send it and I'll update the PR.

**Comment by christo4ferris** [comment]
updated PR

**Comment by srderson** [comment]
oops, I missed an issue. In CONTRIBUTING.md you link to MAINTAINERS.md but here you called the file MAINTAINERS.txt.

**Comment by christo4ferris** [comment]
yes, I was waiting for the merge of #1020

**Comment by christo4ferris** [comment]
see #1021

**Pull request merged**
