### PR TITLE
Update the directory of main.go - issue #1222

### PR DESCRIPTION
**Pull request by genggjh**
Signed-off-by: David Geng david@esse.io

### CODE REVIEW

**Comment by binhn** [comment]
@genggjh @christo4ferris  -  I don't think this is right.  We are in `$GOPATH/src/github.com/hyperledger/fabric/peer`, so the current directory contains `main.go`, NOT `peer/main.go`

**Comment by christo4ferris** [comment]
@binhn @genggjh actually, no... the navigation is relative to the root of the repo for markdown files such as this README.md - I tested the PR and it is working as expected. The current README.md main.go link returns a 404.

**Comment by binhn** [comment]
@christo4ferris thanks for testing it out.

**Comment by genggjh** [comment]
@christo4ferris thanks for your clarification.

**Pull request merged**
