### PR TITLE
Implement issue #875: Passing transaction timestamp to the chaincode

### PR DESCRIPTION
**Pull request by binhn**
Adding shim stub GetTxTimestamp(). See chaincode_example01 for unit test case

### CODE REVIEW

**Comment by srderson** [comment]
@binhn Do we need test cases or documentation associated with this change?

Could you provide more detail in the comment in chaincode.go?

```
// GetTxTimestamp returns transaction timestamp
 +func (stub *ChaincodeStub) GetTxTimestamp() (*gp.Timestamp, error) {
```

Based on that comment it's not clear to me who generates the timestamp or when it is generated.

**Comment by binhn** [comment]
@srderson ok, will add more comment and doc -- the timestamp is currently the transaction created timestamp

**Comment by binhn** [comment]
@srderson I am working on resolving the conflicts

**Comment by binhn** [comment]
@srderson I push a new PR to resolve the conflicts https://github.com/hyperledger/fabric/pull/1433
We should close this one.

**Pull request closed without merging**
