### PR TITLE
TOC links to prot spec

### PR DESCRIPTION
**Pull request by joshhus**
Linked the unlinked headings from fabric/README.md TOC to protocol spec.

Issue: https://github.com/hyperledger/fabric/issues/1324

Signed-off-by joshh@us.ibm.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
@joshhus the convention is

Signed-off-by: Your Name youremail@domain.com

That is what the bot is looking for. That is what the LF bot will insist on. Please update your DCO signoff, Thanks

**Comment by christo4ferris** [comment]
also, if you are just changing markdown files, you can add [ci skip] to the title and body of the PR message and it will bypass running the Travis tests.

**Comment by joshhus** [comment]
Signed-off-by: Josh Horton joshh@us.ibm.com

**Comment by joshhus** [comment]
can add or should add?

**Comment by christo4ferris** [comment]
can... running the CI pipeline for changes to markdown is unnecessary.

**Comment by joshhus** [comment]
Need to tweak a few things. Josh Horton joshh@us.ibm.com

**Pull request closed without merging**
