### PR TITLE
Fixes #653 : [Several serious container errors are being reported at …

### LINKED ISSUE #653: Several serious container errors are being reported at the DEBUG level
There are several log messages related to container handling that I think should be promoted from DEBUG level to a higher level, as these represent errors from the user's perspective. This will make it easier for users (like me) to figure out what's going on, as these messages are normally not printed.

Here are a few examples:

```
12:38:25.785 [container] build -> DEBU 029 Error building Peer container: Error: image bcbrock/golang:latest not found
12:38:25.800 [container] start -> DEBU 031 start-container does not exist, attempting to create API error (404): no such id: dev-vp1-60caf3632e0f43a5a7f14f27115bfaf84f76ee59d3490bbb337703e098ada77fc7b7bddd093f354e8ef89f644330131e5799c966503070b94eb1a83cbc9dc10c
12:38:25.803 [container] start -> DEBU 033 start-could not recreate container no such image
12:57:11.180 [chaincode] LaunchChaincode -> DEBU 09c launchAndWaitForRegister failed Error starting container: no such image
```

### PR DESCRIPTION
**Pull request by ezhilvendhan**
## Description

Errors written on DEBUG Level are moved to ERROR level
## Motivation and Context

This fix will ensure that error messages are not overlooked as debug messages
Fixes #653 
## How Has This Been Tested?

Yes, Ran the Unit tests successfully

## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Ezhil Vendhan uibuddha@gmail.com

…the DEBUG level]

### CODE REVIEW

**Comment by binhn** [comment]
@ezhilvendhan Hi, thanks for the PR; however, I think the change may not be entirely accurate as in some instances, the errors are propagated up to the chain, and so we wouldn't want to output the errors but leave that to the caller to handle. We really need the ability to capture the stacktrace at the time the error occurs #662 so that when the error is logged, we know where it happened in the code.

**Comment by srderson** [comment]
@ezhilvendhan Please do not modify files in the /vendor folder. These are external packages and should only be updated via [govendor](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#adding-or-updating-go-packages-) and PRs to their respective repositories if necessary. Thanks.

**Comment by ezhilvendhan** [comment]
@binhn @srderson Thanks for your comments. Will reverting the changes on vendor folder be sufficient to get this pull request accepted?

**Comment by binhn** [comment]
@ezhilvendhan I think we should not log the error if the caller is also logging the same error, so really have to walk up the chain otherwise we would end up with the same error messages in the log, difficult to support.

I agreed we should not modify the vendor packages here.

**Comment by ezhilvendhan** [comment]
@binh I have updated as per your suggestion. Please let me know if it works.

**Comment by bcbrock** [comment]
This PR does not fix **any** of the issues first raised in issue #653! I am concerned by the fact that numerous fatal errors that occur during chaincode deployment are being squashed.

**Pull request closed without merging**
