### PR TITLE
added check for error

### LINKED ISSUE #1257: test fails to catch nil ledger
core/chaincode/exectransaction_test.go fails to catch possible nil ledger

### PR DESCRIPTION
**Pull request by christo4ferris**
added check for error in ledger.Getledger()

Fixes #1257

Signed-off-by: Christopher Ferris chrisfer@us.ibm.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
re-ran build - original failure was due to known occasional pbft test failure.

**Comment by corecode** [comment]
I don't think this additional conditional is needed.  The test will fail either way.  Under which condition could `GetLedger` even fail?

**Comment by christo4ferris** [comment]
when/if someone changes it. this is cleaner, IMO

**Comment by srderson** [comment]
Ideally I guess we would have used `_` instead of `err` if we wanted to ignore it. I personally agree with @christo4ferris that it's more readable with the check, but I see how opinions could differ here.

It's a moot point because we have issue #904 so eventually `ledger.GetLedger()` will not return an error. So LGTM until #904 is resolved and then this will be removed as part of that change.

**Pull request merged**
