### PR TITLE
Code changes for the issue #788

### PR DESCRIPTION
**Pull request by ratnakar-asara**
Code changes  for issue #788 "inconsistent naming of chaincode transaction types across layers"

### CODE REVIEW

**Comment by ratnakar-asara** [comment]
Signed-off-by: rasara@us.ibm.com

**Comment by srderson** [comment]
@muralisrini @ratnakar-asara First, thanks for this PR. This is a much needed change. I notice there are changes in openchain.proto in the transaction type such as `CHAINCODE_QUERY = 4;` to `CHAINCODE_QUERY = 3;`. This would normally break compatibility. Is this a problem or is it ok as long as you're also using an updated client?

@stanliberman This PR contains the Init function in a chaincode now so it's likely of interest to you.

I know one of Stan's requirements was a guarantee that the Init function is only run one. Is that the case here?

**Comment by muralisrini** [comment]
@srderson : chaincode messages are just between the peer and chaincode (does not bleed into user apis)... so should be fine.

Currently we allow deploy to be called for the same chaincode any number of times (recorded in #581). When that gets fixed, init of a chaincode cannot be called multiple times.

**Comment by muralisrini** [comment]
@srderson : as part of this work @ratnakar-asara had to make APIs such as the REST APIs compatible as well. So yes, as long as clients side are uptodate we should be fine.

@angrbrd : can you review to make sure please ?

As far calling init only once, there's issue #581 to prevent duplicate deploys. Once that's fixed, the init function can only be run once (at the first deploy).

**Comment by muralisrini** [comment]
@ratnakar-asara : we will have to do this work on the Hyperledger codebase anyway. So please keep you branch around for us to continue there. Will close this PR on this repo so we can open a new one on Hyperledger.

**Comment by muralisrini** [comment]
@stanliberman : we will continue with this PR under hyperledger github

**Pull request closed without merging**
