### PR TITLE
Walk bug fix

### PR DESCRIPTION
**Pull request by joequant**
Signed-off-by: Joseph C Wang joequant@gmail.com

### CODE REVIEW

**Comment by srderson** [comment]
@joequant Please rebase on master as there are merge conflicts. Thanks

@muralisrini I think this code is in your area. Would you mind giving it a quick review?

**Comment by muralisrini** [comment]
thanks @joequant, LGTM.

**Comment by joequant** [comment]
Rebased.

**Comment by srderson** [comment]
You two are fast! LGTM. Thanks!

**Pull request merged**
