### PR TITLE
New TCertPool for better performance at client side

### PR DESCRIPTION
**Pull request by adecaro**
This PR addresses the "No TCert in cache found" issue #684 by providing a new infrastructure that loads the TCert from the TCA in background and deliver the TCerts to the application as soon as possible in a streaming fashion.  

@binhn @muralisrini For better performance, a client should be initialized once and kept active as much as possible to avoid to close and reinitialize it. 

The PR also addresses issue #692 by using the property logging.crypto, it is possible to configure the logging level of the crypto layer.

@bmos299 In this PR, I have also added more logging information related to the servers the crypto layer is connecting to. I hope it helps.

Signed-off-by: Angelo De Caro adc@zurich.ibm.com

### CODE REVIEW

**Comment by muralisrini** [comment]
@adecaro : thanks.. will test today.

**Comment by muralisrini** [comment]
this might be related to #714 if logging config changes in this PR is causing the crash.

**Comment by muralisrini** [comment]
ref #714 : we were not sure if the problem was in go-logging or in the way we were using it. It is only with this PR that we see this go-logging related crash. So whatever we are doing with that package prior to this PR is correct till proven otherwise.

Commenting out initialize-log-per-client code avoids the problem. We could try to figure out the right way to maintain that semantics. I suspect that's going to be a bit of work and may not be worth the effort ? An alternative might be to initialize log once at the beginning and write logs for all clients to it, thus avoiding write-read collisions. What do you think @adecaro ?

**Comment by adecaro** [comment]
@muralisrini, @dongmingh I updated the PR to have a centralized log. I took the opportunity to introduce in main.go a line to initialize the crypto layer.

Please, @dongmingh, may you test the updated PR, if the performance are still 'good'. I will merge. Thanks :)

**Pull request merged**
