### PR TITLE
Sieve statetransfer

### PR DESCRIPTION
**Pull request by corecode**
Integrate sieve with state transfer.  Builds on #959.

Signed-off-by: Simon Schubert sis@zurich.ibm.com

### CODE REVIEW

**Comment by corecode** [comment]
Signed-off-by: Simon Schubert sis@zurich.ibm.com

**Comment by kchristidis** [comment]
May occasionally hang during `TestSieveNonDeterministic`. (Even without a high `-count`, got it on my first try when testing this PR.) Sent more info on Slack.

I'm hesitant to proceed with merging unless we have a clear understanding of what's going on here. @jyellick may want to elaborate as this seems to be linked with state transfer.

**Comment by jyellick** [comment]
@kchristidis Fixed the issue you described for `TestSieveNonDeterministic` in https://github.com/jyellick/obc-peer/commit/1c94df6f038348739eeda2bbf7142a5701793f85

This test rarely failed in my environment (required upwards of 40 executions before I received a failure).  Have successfully run 2500 tests with the commit above and no failures.  Let me know if you still have problems.

**Comment by jyellick** [comment]
I am seeing an occasional failure in `TestSieveReqBackToBack` so I would not pull yet.  Am investigating and will attempt to fix.

**Comment by kchristidis** [comment]
See #605.

**Pull request closed without merging**
