### PR TITLE
Modified example 'chaincode_example_06' by 'attributes_to_state'

### LINKED ISSUE #2235: Chaincode_example06 build fails, missing shim.ChaincodeStub.CertAttributes()
## Description

The stub is missing a method "CertAttributes", the example fails to build
## Describe How to Reproduce

cd $GOPATH/src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example06
go build

./chaincode_example06.go:33: stub.CertAttributes undefined (type *shim.ChaincodeStub has no field or method CertAttributes)

### PR DESCRIPTION
**Pull request by andresgaragiola**
## Description

Modified example 'chaincode_example_06" by 'attributes_to_state' in order to:
- Avoid use pattern 'chaincode_example_XX' in examples names.
- Avoid use of function names 'query' and 'invoke'.
- Improve the example using more attributes features (attribute handler and attributes verification).
- Get example compiled removing no longer supported API.
## Motivation and Context

Fixes #2235 
## Checklist:

- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [X] This change requires no new documentation.
- [X] This change requires no new tests.
- [X] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Andres Garagiola garagiol@ar.ibm.com

### CODE REVIEW

**Comment by rameshthoomu** [comment]
Jenkins build is not proceeding further since long time.. I have canceled this build and re-triggering.

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by christo4ferris** [comment]
@andresgaragiola have you migrated this to Gerrit? If not, please do or close. Thanks!

**Comment by andresgaragiola** [comment]
@christo4ferris I'm closing this PR due to was migrated to gerrit and merged there.

**Pull request closed without merging**
