### PR TITLE
Issue892

### PR DESCRIPTION
**Pull request by andresgaragiola**
Fix of issue892.

### CODE REVIEW

**Comment by andresgaragiola** [comment]
Signed-off-by: Andres Garagiola garagiol@ar.ibm.com/andresgaragiola@gmail.com

**Comment by srderson** [comment]
@andresgaragiola Please rebase on master as there are merge conflicts. Also, could you provide a bit more detail about this PR to help others review? Issue #892 does not have enough info. Thanks

**Comment by andresgaragiola** [comment]
@srderson I'm waiting the processing of PR #1310 before fix this conflicts.

**Comment by andresgaragiola** [comment]
I'm closing this PR because now we have other functionalities to merge with it before process the PR.

**Pull request closed without merging**
