### PR TITLE
Rename ChaincodeSpec.ctor to ChaincodeSpec.input

### PR DESCRIPTION
**Pull request by srderson**
## Description

This change renames `ChaincodeSpec.ctor` to `ChaincodeSpec.Input` in `chaincode.proto`. This causes API changes when deploying, invoking, or querying a transaction. The changes are to the REST API, the gRPC API, and the CLI where `ctor` `c` has been renamed to `input` `i`. All documentation has been updated to reflect these changes.
## Motivation and Context

This is part of issue #1183. The goal is to have a cleaner and more understandable API. `ctorMsg` is a leftover from the days when `ChaincodeSpec` was intended to define a chaincode. At some point this was overloaded and also used for invocation. At this point, we have decided to use `ChaincodeSpec` for all elements that are common between `ChaincodeDeploymentSpec` and `ChaincodeInvocationSpec`. Specific elements will be moved to either `ChaincodeDeploymentSpec` or `ChaincodeInvocationSpec`.

While breaking API changes are unfortunate, this change should result in a better user experience over the long run.
## How Has This Been Tested?

The tests have all been run and passed. There are no new tests because there are no feature changes. Some tests were modified to support the new API.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: sheehan@us.ibm.com

### CODE REVIEW

**Comment by ghaskins** [comment]
@srderson Thanks for taking this on.  While I recognize that ABI affecting changes should not be taken lightly, I also recognize we currently have some suboptimal representations of things in the spec.  To this point, better to try to get it right as early as possible while we still have the option without requiring compatibility baggage.  I would therefore like to voice my enthusiastic support for this effort.

While I fully agree with everything you are proposing here, I still am a little uncertain about specific things that remain in the spec even after your changes that we should discuss.  For example, I am bothered by the current practice of specifying the chaincodeType in invoke.  It seems to me this only belongs in the deployment.

Assuming we agree that additional changes may be ideal, my question is: should we try to identify and tackle them all at once so we only break the ABI once?  Or should we tackle them as isolated efforts for simplicity at the cost of more red-flag events?

**Comment by srderson** [comment]
I also plan to move `chaincodeType` as you suggest, but was trying to avoid dropping too much at once to make review a bit easer. I agree that we should try to break all at once rather than slowly overtime.

Option 1) You could review this change, but not merge, and then I can add a second commit with the other mentioned change. Then you could review again and merge.

Option 2) I submit a second PR with the other change. You could wait to merge this change until the second one is submitted, but I may need to rebase quickly after this one is merged.

@christo4ferris thoughts on how to handle this case?

**Comment by srderson** [comment]
spoke with @jyellick and he suggested stacking PRs which has worked for him. This GitHub UI doesn't handle this perfectly because the files tab shows all changes in the latest PR, but it seems like the best approach based on his experience.

**Comment by jyellick** [comment]
To expound on what @srderson said, my flow has been:

```
git checkout upstream/master
git checkout -b bigfeature-pr1
# do changes and commits push, submit PR
git checkout -b bigfeature-pr2
# do changes and commits push, submit PR
...
git checkout -b bigfeature-prn
...
```

Then if there ends up being a merge conflict at some point, it's as easy as walking back through the tree

```
git checkout bigfeature-pr2
git rebase upstream/master
git checkout bigfeature-pr3
git rebase bigfeature-pr2
git push -f
git checkout bigfeature-pr4
git rebase bigfeature-pr3
git push -f
...
```

Github PRs seem to handle the `push -f` pretty gracefully.  Though the diffs in the UI won't initially be great, they can always be viewed through the git cli.

**Comment by ghaskins** [comment]
This is my first time using github as the patch review mechanism, so I suspect there will be a little bit of a learning curve and trial+error until we come up with a good workflow.  But FWIW, I've done lots of work on other projects like the Linux kernel that (at least at the time) used more crude methods such as patches mailed to the ML.  In that environment, the email was the "PR", and the one or more patches in the thread were the individual commits for an atomic, individually reviewable change.  This is of course analogous to the patches in the branch that are submitted in the PR.

It seems the same basic principle _should_ work here as long as people adhere a small amount of discipline in how they aggregate the patches.  If people push PRs with willy-nilly merges and incremental changes, this wont work.  However, if people curate a clean, rebased, patch series with the goals of making each patch an individual, sensible, and self-contained changeset, I see no reason this would be difficult for reviewers to see the breakdown:  Yes, the top "Files Changed" tab shows an aggregate of the series, but its straight forward to review individual patches as well I have found.

Personally, I use stgit to help curate series in this manner, but there are other workflows that work just as well.

This is the round-about way of saying "Option 1", with the intent of spurring a dialog regarding general methods going forward.  Thoughts?

**Comment by binhn** [comment]
I think option 1 would likely be less work for submitters while option 2 would be easier for reviewers but high potential of merge conflicts. So I think we should go with option 1.

**Comment by christo4ferris** [comment]
@binhn why optimize for the submitter?

**Comment by binhn** [comment]
@christo4ferris Hope to encourage more contribution. Resolving merge conflicts some time takes a lot of time and some time has to be done manually, so option 1 is to hopefully avoid that possibility.

**Comment by ghaskins** [comment]
@srderson We should ideally get this cleanup done ASAP.  How would you like to proceed?

**Comment by srderson** [comment]
Closing. Will be optimized as part of V2

**Pull request closed without merging**
