### PR TITLE
add log-level support for chaincode

### LINKED ISSUE #2023: Add log-level support for chaincode
## Description

Docker daemon has a very high cpu usage when run performance test.
Profile shows that the high cpu usage is caused by verbose logging in chaincode container.
When docker daemon started with option --log-driver="none", the problem gone.
## Describe How to Reproduce

1. Start 4 validator peer nodes on single node.
2. Deploy chaincode_example02, start 20 clients to invoke chaincode_example02
3. Use top to see docker daemon's cpu usage

### PR DESCRIPTION
**Pull request by zuowang**
## Description
1. read in config file from current path
2. config log-level for chaincode 
## Motivation and Context

Fixes #2023
## How Has This Been Tested?

deploy a chaincode, check log-level with command "docker logs chaincode-container-id"
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

The continuous integration build process will run [make checks](https://github.com/hyperledger/fabric/blob/master/Makefile#L22) to confirm that tests pass and that code quality meets minimum standards. You may optionally run this locally as PRs will not be accepted until they pass.

Signed-off-by: Zuo Wang wangzuo3@wanda.cn

### CODE REVIEW

**Comment by srderson** [comment]
@muralisrini @bcbrock As you have both been active in this area do you have any comments?

**Comment by bcbrock** [comment]
@srderson -  If merged as-is this would be the second time that people have misunderstood or ignored the documentation in the core.yaml file surrounding logging control. The logging.<subcommand> keys are clearly documented as applying to subcommands of the peer command. The first mistake is the presence of the "crypto" key here - see #769. 

Note that the subcommand controls include a syntax for fine-grained control of logging "modules" within the peer program, which is very different from what is being proposed here - namely a simple level control over a single logging object in the shim.

I think if we want to control this from a YAML file then it should at least be done as a completely separate set of keys from logging.<subcommand>, to avoid the types of confusion listed above. Also note that the control suggested here only applies to user-mode chaincodes but not to system chaincodes. Is that an oversight?

As long as we're doing the shim we should also go ahead and have a control that would apply a default to the objects created by the shim.NewLogger() function. Of course the PR also needs to include updates to documentation before being accepted.

**Comment by zuowang** [comment]
@bcbrock could you help to review the code?

**Comment by bcbrock** [comment]
Hi @zuowang you may be sorry you asked - I am hard to please.

This utility only currently only applies to go-language chaincodes. That needs to be made clear in the docs. I think. We also need more than a single incomplete sentence to describe the operation of these parameters.

Also, your key 'shim.logging.chaincode' only applies to system chaincodes. I was suggesting that there should be a way to apply this setting as a default to the logging objects created by shim.NewLogger(). So we probably want 3 settings: shim, system chaincode, user chaincode.

Rather than creating a new top-level hierarchy called 'shim', maybe these keys should be placed under the pre-existing 'chaincode' hierarchy?

Also, if I am not mistaken it is not necessary to reload the Viper file in startInProc() since by definition you are already running in the context of a running peer.

**Comment by zuowang** [comment]
@bcbrock 
It's already in the 'Go chaincodes' section. I made it more clear by adding to example.

I added 3 key "chaincode.logging.shim" "chaincode.logging.scc" "chaincode.logging.ucc" for setting default log level of shim, system chaincode, user chaincode.

no need to reload the Viper file.

**Comment by bcbrock** [comment]
@srderson I believe this PR should be closed. I apologize to @zuowang for not coming to this conclusion  earlier, but some of the issues he had to solve in his latest code leads me to this conclusion.

First, the logging level of the shim for system chaincodes can already be controlled in no less than 4 different ways. If anything is missing, it is only an explicit line of documentation describing how to do this.

Second, I have become a big anti-fan of Viper and YAML files for configuration. The YAML files are part of the source code of the system. We need to allow users change the configuration without changing the source code of the system. Also consider that logging levels are user preferences that change day by day. Why should ephemeral chaincode logging settings be stored in the same configuration file that the system administrator uses to configure critical functions of the server?

At the moment I will argue that it is cleaner for the chaincode writer to explicitly control the chaincode operations through private configurations. For example in `tools/busywork/counters/counters.go` the chaincode accepts "command line parameters" (iinitialization arguments) that include logging levels for the shim and the chaincode. These level default according to a personal preference but can can be changed by anyone without modifying any system source code.

Finally, I believe I've heard @muralisrini lament in the past that the user-chaincode shim should be a lightweight interface, but instead currently brings in the kitchen sink. This shows up in the fact that this PR has to (redundantly) reload the Viper file every time a chaincode allocates a new logging object - the user-chaincode interfaces are not cleanly separated from the system chaincode support.

I think the chaincode interafaces should be refactored, perhaps with a well-thought-out, comprehensive approach to configuring chaincodes. Since there are already other way to accomplish what this PR does, I don't see a need for it at this time.

**Comment by zuowang** [comment]
@bcbrock  The log level of shim is hard coded to be LogDebug. And it caused a very high CPU usage in my performance test. Could you help to point out if there is any way to config it?

```
var shimLoggingLevel = LogDebug // Necessary for correct initialization; See Start()
```

I admit the chaincode interafaces should be refactored. But it's a quick fix to config the log level of the user-chaincode shim.

**Comment by zuowang** [comment]
this part of code requires non-trivial refactor work. close the PR.

**Comment by bcbrock** [comment]
@zuowang The shim uses a logging object that logs as the "shim" _module_. Module-level logging control is documented in the core.yaml file and in docs/dev-setup/logging-control.md. These settings will only apply to the shim used by system chaincodes, however. For example if you want the peer to log at INFO and the system-chaincode shim to log at WARNING:

```
export CORE_LOGGING_LEVEL=info:shim=warning
```

If your own user-chaincode is causing the problem then you can use the shim.SetLoggingLevel API to control it. If it's somebody else's user-chaincode then you could either try to convince them to add an explicit control, copy/modify their code and do it yourself, or modify the line of source code above in your installation. I realize that these are not perfect options. Thank you for your agreement to hold off this PR in lieu of a refactoring if the chainode interface.

**Pull request closed without merging**
