### PR TITLE
Issue156/chaincode invoke chaincode

### PR DESCRIPTION
**Pull request by prjayach**
Includes the following:
1. Support for chaincode transaction to invoke another chaincode, chaincode transaction to query another chaincode, and chaincode query to query another chaincode.
2. Fix to ensure put/del state are not allowed within chaincode query.
3. Additional error paths handled.
4. Additional tests and chaincode examples.

### CODE REVIEW

**Comment by prjayach** [comment]
Signed-off by: Praveen Jayachandran prjayach@in.ibm.com

**Comment by prjayach** [comment]
@muralisrini, @binhn: This fixes Issues #156 and #199. For #148, I don't think any additional API are needed. The support for chaincodes to invoke other chaincodes is now in place.

**Comment by muralisrini** [comment]
thanks, @prjayach ... will test

**Comment by muralisrini** [comment]
"go test" within chaincode folder works. The main test stutters but then there have been other fixes since this PR. Did some code review and codechain-invoke appears to be in line with rest of codechain interactions such as GET/PUT/DEL and INVOKE/QUERY.

Based on above, will merge PR.  By definition, Chaincode-chaincode invocation is more complex than other interactions. So will continue to watch post-merge

**Comment by prjayach** [comment]
Hmm.. there are issues when containers aren't cleaned up properly. Also, the peer test was failing at the time I submitted this. Apart from that, I didn't see any issues with the chaincode tests. I'll continue to watch as well. Thanks!

**Comment by muralisrini** [comment]
Agreed. There's been test stutter all along. By the way, working on #327 to clean up containers.

**Pull request merged**
