### PR TITLE
pbft: work with f=0, N=1

### PR DESCRIPTION
**Pull request by corecode**
Signed-off-by: Simon Schubert sis@zurich.ibm.com

### CODE REVIEW

**Comment by kchristidis** [comment]
_Probably_ best to hold off on this, until we have settled the `TestNewViewTimeout` issue (that @jyellick is working on), and the view-change issue that you pointed out.

**Comment by corecode** [comment]
this is entirely unrelated to view change

**Comment by jyellick** [comment]
@kchristidis I agree with @corecode, this should be pretty unrelated to the `TestNewViewTimeout` issue

**Comment by kchristidis** [comment]
Consistently hangs during the `MinimalFuzz` test.

**Comment by corecode** [comment]
fixed the hang

**Comment by kchristidis** [comment]
@binhn, @srderson: Can you please merge this?

I'm having some issues with the `behave` tests that are local to my machine only; trying to figure these out with @jeffgarratt.

**Comment by srderson** [comment]
Confirmed that unit tests and behave tests are passing with this PR.

**Pull request merged**
