### PR TITLE
Dont lock in read write loop#520

### PR DESCRIPTION
**Pull request by muralisrini**
In progress, for code review.

### CODE REVIEW

**Comment by binhn** [comment]
func (i *Noops) notifyBlockAdded() is to tell the connected NVPs the newly created block. The noops NVPs don't need states nor payload since they never execute txs. 

I don't see the changes to the code in this function to only send the notification to the NVPs. Are there reasons for that or we haven't done that yet?

**Comment by muralisrini** [comment]
@binhn : We haven't done that yet but can do that easily once we verify the root cause fix without perturbing message flows too much.

On the other hand it might make sense to keep them around even if unused so we can catch these kind of issues.

**Comment by muralisrini** [comment]
noops now broadcasts SYNC_BLOCK_ADDED to non-validators only.

**Comment by muralisrini** [comment]
@kchristidis : yes. @binhn is going to create a issue for you though

**Pull request merged**
