### PR TITLE
modify docs about ledger.state.dataStructure.name

### PR DESCRIPTION
**Pull request by ckeyer**
Signed-off-by: Chuanjian Wang me@ckeyer.com

### CODE REVIEW

**Comment by ckeyer** [comment]
This is not match https://github.com/hyperledger/fabric/blob/master/core/ledger/statemgmt/state/state.go#L58-L67

**Comment by christo4ferris** [comment]
re-running Travis even though this is just a doc change. Otherwise, LGTM thanks @ckeyer

**Comment by srderson** [comment]
Does the default of 'bucketTree' not work? I notice there are still variables in the code indicating that 'bucketTree' is the default. For example https://github.com/hyperledger/fabric/blob/2b2ae0cd337fde98fa0cdfaf9b0865dba72dfd49/core/ledger/statemgmt/state/state.go#L37

If we don't have a default, these should probably be cleaned up.

@manish-sethi

**Comment by ckeyer** [comment]
@manish-sethi  this variables is used there https://github.com/hyperledger/fabric/blob/2b2ae0cd337fde98fa0cdfaf9b0865dba72dfd49/core/ledger/statemgmt/state/config.go#L48

**Comment by manish-sethi** [comment]
Default of 'bucketTree' should work. The relevant code is what @ckeyer pointed out in his last comment.
The 'raw' should not be exposed in the core.yaml as it does not implements iterator functions yet. Also, I am not sure how should we compute the state-hash in 'raw' implementation (e.g., return something dummy?)
This is just to benchmark the max throughput that we can get so we can see how other implementations fair.

**Comment by christo4ferris** [comment]
We should document that 'raw' is experimental and incomplete, then... not just omit it. We should be endeavoring to keep docs as consistent with the code as possible.

**Comment by christo4ferris** [comment]
LGTM thanks @ckeyer

**Comment by srderson** [comment]
LGTM, thanks!

**Pull request merged**
