### PR TITLE
CLI Changes to support scripting

### PR DESCRIPTION
**Pull request by bcbrock**
This PR addresses #453.

New documentation (to be added in a separate pull request to obc-docs):

---

To facilitate its use in scripted applications, the `obc-peer` command always
produces a non-0 return code in the event of command failure. Upon success,
many of the subcommands produce a result on **stdout** as shown in the table
below:

| Command | **stdout** result in the event of success |
| --- | --- |
| `peer` | N/A |
| `status` | String form of ServerStatus_StatusCode |
| `stop` | String form of ServerStatus_StatusCode |
| `login` | N/A |
| `vm` | String form of ServerStatus_StatusCode |
| `chaincode deploy` | The chaincode container name (hash) required for subsequent `chaincode invoke` and `chaincode query` commands |
| `chaincode invoke` | The transaction ID (UUID) |
| `chaincode query` | By default, the query result is formatted as a printable string. Command line options support writing this value as raw bytes (-r, --raw), or formatted as the hexadecimal representation of the raw bytes (-x, --hex). If the query response is empty then nothing is output. |

---

Although many lines of main.go are changed, the changes are primarily
cosmetic:

The commands now use the Cobra 'RunE' interface because they return errors to
top-level command processing.

Since Cobra command processing prints the usage message and error string when
commands fail, several places where the code was doing this explicitly have
been removed.

In a few cases logging messages were converted to error objects and returned.

Things are written to **stdout** as documented.

Note that many of the commands still do ad-hoc error processing, e.g., they
call `panic` in the event of certain errors. I tried to change as little as
possible to implement the required function here so did not change these - I
did not feel comfortable to completely "rewrite" error handling.

### CODE REVIEW

**Comment by bcbrock** [comment]
Signed-off-by: Bishop Brock bcbrock@us.ibm.com

**Comment by bcbrock** [comment]
Following @angrbrd suggestion, I made the user interface more consistent by replacing all of the `logging.Error()` calls in `main()` with the creation and return of `error` objects.

In doing/testing this I noticed that the code in `checkChaincodeCmdParams()` that
tried to check the JSON arguments to chaincodes for consistency did not actually work; So
I fixed this as well. This leads to a question though: Is it correct to provide empty JSON arguments `{}` to chaincode delay/invoke/query? I did not change this aspect of the original code.

**Comment by angrbrd** [comment]
@bcbrock, this looks good. I went ahead and merged this change. I agree with the above comment that providing an empty JSON argument to chaincode deploy/invoke/query should be disallowed. However, I think we should put a separate commit in for that. We are already fixing several issues with this merge. It's a two line change, if you'd like to put that check into `checkChaincodeCmdParams()` that's fine with me, otherwise assign to me and I will do it myself. Thanks!

**Comment by bcbrock** [comment]
@angrbrd , Thanks for merging this. Please go ahead and fix the empty JSON problem, I'll work on other things.

**Pull request merged**
