### PR TITLE
Fix Issue 1223

### PR DESCRIPTION
**Pull request by lehors**
This simple fix to issue #1223 stops the local running peer if any before starting the behave tests so that it doesn't get in the way.
This depends on the fix to issue-1224 so that "peer stop" can be invoked successfully from the bddtests directory.

Signed-off-by: Arnaud Le Hors lehors@us.ibm.com

### CODE REVIEW

**Comment by lehors** [comment]
Hmm, the whole build and testing is kind of screwy in my opinion because it is based on running programs from specific directories. The Travis check apparently fails because it doesn't have the peer command in its $PATH.

**Comment by lehors** [comment]
Note that with this fix the clunky command to kill the running peer in .travis.yml can be removed.

**Comment by christo4ferris** [comment]
LGTM

**Comment by srderson** [comment]
Confirmed all tests are passing. LGTM. Thanks!

**Pull request merged**
