### PR TITLE
[WIP] Use stub to get chain code function and arguments

### PR DESCRIPTION
**Pull request by gabre**
This PR adds chaincode function/args state to the stub.
## Motivation and Context

Fixes #
## Checklist:

- [] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [] I have either added documentation to cover my changes or this change requires no new documentation.
- [] I have either added unit tests to cover my changes or this change requires no new tests.
- [] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by:

### CODE REVIEW

**Comment by muralisrini** [comment]
@gabre API's with []string cannot be replaced with []byte.... should be [][]byte.

**Comment by gabre** [comment]
@srderson what is your opinion about using [][]byte instead of []byte? @esgott ?

**Comment by christo4ferris** [comment]
@gabre please edit the description to add the DCO signoff. thanks!

**Comment by christo4ferris** [comment]
@gabre seems you have migrated this PR to Gerrit, can we close this then?

**Comment by christo4ferris** [comment]
@gabre I am closing this as it seems to have been migrated.

**Pull request closed without merging**
