### PR TITLE
Removing auto-generated Node.js SDK files

### LINKED ISSUE #2050: node SDK automatically generated files should not be checked into git
## Description

fabric/sdk/node/doc and fabric/sdk/node/lib (and maybe other directories?) contain automatically generated files and should not be checked into git.  The reason this was done initially was because we want these files to be part of each "npm publish" for the "hfc" node module and it was thought that the only way to do this was to NOT have these directories in .gitignore files.  However, after further investigation, it is possible to put these directories in .gitignore files and also create .npmignore files which do NOT contain these directories.  npm will then ignore the .gitignore files and use .npmignore file instead.   See https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

So I think the following steps will solve this and should be done:
1) Copy fabric/sdk/node/.gitignore to fabric/sdk/node/.npmignore
2) Add "doc/" and "lib/" to fabric/sdk/node/.gitignore
3) Delete the doc and lib directories
4) Create a fabric/sdk/node/bin/build script which does everything currently done in the fabric/Makefile under the "node-sdk" target, which is:
        cp ./protos/_.proto ./sdk/node/lib/protos
        cp ./membersrvc/protos/_.proto ./sdk/node/lib/protos
        cd ./sdk/node && sudo apt-get install npm && npm install && sudo npm install -g typescript && sudo npm install typings --global && typings install
        cd ./sdk/node && tsc
        cd ./sdk/node && ./makedoc.sh
5) Edit fabric/Makefile to call fabric/sdk/node/bin/build and remove the above from Makefile
6) Create a fabric/sdk/node/bin/npm-publish script which does the following:
    a) calls the 'build' script from step #4
    b) performs an npm update according to https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package, which means this script should require the <update-type> argument (i.e. patch, minor, or major).  Note that the "npm version <update-type" actually updates the package.json file and must be done from the fabric/sdk/node directory.

We should always invoke the npm-publish script just before creating a pull request.
## Describe How to Reproduce

Check github to see these files

### PR DESCRIPTION
**Pull request by angrbrd**
## Description

This change removes the auto generated /doc/ and /lib/ files from the Node.js SDK, as they should not be tracked in Git.
## Motivation and Context

This change is required in order to remove auto-generated Node.js SDK files from Git. They do not need to be tracked in the repository in order to be published to npm. Also, modifying the .gitignore file such that these auto-generated files do not clutter up a user's local repo when they build the Node.js SDK.

Fixes #2050
## How Has This Been Tested?

This change has been tested with the existing SDK unit test files to verify that removing auto-generated files does not cause any breaks. These files are re-generated once again when the user executes `make node-sdk-unit-tests`. I am not modifying any code with this change.
## Checklist:
- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Anna D Derbakova adderbak@us.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
@rameshthoomu Any idea why Travis failed to run on this PR?

**Comment by angrbrd** [comment]
@srderson I am not sure. I noted that also and reached out to @rameshthoomu. He said he was also not sure :-], but he will restart it. Stay tuned.

**Comment by srderson** [comment]
Thanks. Oddly enough I do see a Travis result for commit 4b076f16e895870776f7c62ec181797e1755ae8b posted in Slack

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rennman** [comment]
I verified this fix in my local environment. No changed files were tracked bu git.

**Comment by rameshthoomu** [comment]
Somehow travis triggered this commit #`4b076f1` in `angrbrd` gitrepo. https://travis-ci.org/angrbrd/fabric/builds/143422894. Not sure why Travis not triggered in fabric repo.

**Comment by srderson** [comment]
LGTM. Multiple people confirmed Travis passes on their local branches.

**Pull request merged**
