### PR TITLE
Added tests to increase code coverage in ledger and ledger/util package

### PR DESCRIPTION
**Pull request by manish-sethi**
## How Has This Been Tested?

Unit and behave tests passed
This PR mainly contains new unit tests
## Checklist:
- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by:manishsethi@in.ibm.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
@manish-sethi please update the PR description to include complete description of all the changes made. There were functions deleted, but no mention of what motivated the deletions. There is also a new indexing capability added; what is that about? There may indeed be a valid reason, but it is important that we document clearly all of the changes made in a commit.

**Comment by manish-sethi** [comment]
@christo4ferris Thanks for pointing it out. You are right, I missed documenting minor changes. Following is the summary of the changes other than addition of tests
- Deleted some functions in blockchain.go, blockchain_indexes.go
  These functions are not being used and were only adding negatively to code coverage metrics.
- blockchain_indexes.go - fetchBlockNumberByBlockHashFromDB()
  throw error if block is not found for a given blockHash otherwise, the value returned '0' is misleading for block number 'zero'
- blockchain_indexes_async.go:
  - Made the stop function to be synchronous so the caller waits for indexer to stop fully
  - indexPendingBlocks(): Added an explicit check of whether the zeroth block has been indexed.
  - waitForLastCommittedBlock(): Added a check for errors while waiting for a particular block to be indexed

**Comment by christo4ferris** [comment]
@manish-sethi thanks

**Comment by srderson** [comment]
@manish-sethi This PR needs to be rebased as there is a merge conflict.

**Comment by manish-sethi** [comment]
@srderson I rebased this branch to the master. One of the behave tests (with tag `issue_680`) fails which fails in the master branch as well.

**Comment by srderson** [comment]
Thanks, LGTM

**Pull request merged**
