### PR TITLE
change init to get

### PR DESCRIPTION
**Pull request by ckeyer**
## Description

a bug , init() is before main(),so, can not get Environment Variables

Signed-off-by: Chuanjian Wang me@ckeyer.com

### CODE REVIEW

**Comment by srderson** [comment]
@yeasy Does this solve #1269 for you? Someone on Slack mentioned that this still was not working.

**Comment by GrapeBaBa** [comment]
@srderson this can partial fix what i found in #1959

**Comment by yeasy** [comment]
@srderson  seems not work for me.
btw, it's a little bit strange for vipper's design. Its doc suggests put config/init operations into init(), while mostly we have to put in main().

@ckeyer In the title, maybe you mean "chang" --> "change"?

**Comment by ckeyer** [comment]
the Environment Variables not be used. `viper.UnmarshalKey`

**Comment by srderson** [comment]
@ckeyer Is it possible to add a unit test for the `getDockerHostConfig` function?

**Comment by ckeyer** [comment]
@srderson PTAL

**Comment by srderson** [comment]
LGTM, thanks! It seems like this is a partial fix, so I'll merge. @yeasy Could you open PR with a test case for the problem that you're still seeing? Then we can work there to resolve.

**Comment by yeasy** [comment]
With latest code, I've successfully ported hyperledger fabric on top of my container clouds.
Thanks!

**Comment by christo4ferris** [comment]
nice!

**Pull request merged**
