### PR TITLE
Post processing source links in generated typedoc

### PR DESCRIPTION
**Pull request by th-ei**
Post processing source links in generated typedoc
## Description

The shell script which generates the Node.js SDK API documentation now does some postprocessing to change the source code links. The typedoc tools by default inserts the git repository of the developer at the time of execution. The shell script has a variable DOCURI which needs to be adjusted to the final URI when the code is released. The default value just points to the current master branch which might from the release source code eventually. Upon release the should be generated with a URI using the respective release branch.
## Motivation and Context

Source code links in generated API doc for Node.js SDK point to developers git repo.
## How Has This Been Tested?

Regenerated doc (run sdk/node/makedoc.sh) and checked that links point to master branch on github and not my developer repo
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [n/a] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Thomas Eirich eir@zurich.ibm.com

### CODE REVIEW

**Comment by ghaskins** [comment]
LGTM

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Comment by lindluni** [comment]
@Mergifyio backport release-2.2

**Comment by lindluni** [comment]
@Mergifyio backport release-2.1

**Comment by lindluni** [comment]
@Mergifyio backport release-2.0

**Pull request merged**
