### PR TITLE
Issue 1237

### PR DESCRIPTION
**Pull request by christo4ferris**
changed logger.Error to logger.Errorf

### CODE REVIEW

**Comment by christo4ferris** [comment]
Signed-off-by: Christopher Ferris chrisfer@us.ibm.com 

fixes #1237

**Comment by bcbrock** [comment]
@christo4ferris - ~~I think Go vet wanted you to remove the redundant parameter `op.pbft.L` from the call, not change the function being called.~~ I'm sorry I don't know what I'm talking about - I don't know what it was complaining about.

**Comment by christo4ferris** [comment]
@bcbrock neither do I... AFAIK logging.Logger.Errorf is a very real and valid method https://github.com/op/go-logging/blob/master/logger.go line 213. I am baffled.

**Comment by bcbrock** [comment]
@christo4ferris - We are using the "vendor" package: https://github.com/hyperledger/fabric/blob/master/vendor/github.com/op/go-logging/logger.go
This package is not up-to-date. I believe that if we did update it, we would have to change every call of Debug(), Info() etc. in our code to Debugf(), Infof() etc. Maybe @srderson can comment?

In terms of the Go vet error, I'm wondering now if maybe this is a bug where Go vet is not implementing "vendoring" correctly in some cases. The error message from Go vet makes sense in that context.

**Comment by christo4ferris** [comment]
@bcbrock thanks for the explanation... now to hunt down why we are doing this

**Comment by christo4ferris** [comment]
closing this because the correct fix needs much more investment.

**Pull request closed without merging**
