### PR TITLE
add hyperledger slack sign up info

### PR DESCRIPTION
**Pull request by binhn**

### CODE REVIEW

**Comment by binhn** [comment]
Signed-off-by: binh nguyen binhn@us.ibm.com

**Comment by srderson** [comment]
@binhn This links to the wrong slack URL. The correct URL is http://hyperledgerproject.slack.com according to https://www.hyperledger.org/community

**Comment by binhn** [comment]
@srderson fixed now.  Thanks!

**Comment by srderson** [comment]
LGTM

**Comment by joshhus** [comment]
My bluechain slack id/pw doesn't seem to work here. Should it?

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.1

**Pull request merged**
