### PR TITLE
Installation of grpcio package #1922

### LINKED ISSUE #1922: One behave test scenario fails with 4 CPUs, fine with 2 CPUs
## Description

On a zLinux guest (debian 8) with 4 CPUs, behave test fails for either "peer_basic.feature:846  chaincode example02 with 4 peers and 1 membersrvc, test crash fault -- @1.1 Consensus Options" or "peer_basic.feature:968  chaincode example02 with 4 peers, two stopped". All tests pass with 2 CPUs (after taking 2 CPUs offline). Full logs for the two failures attached.

[behave.zip](https://github.com/hyperledger/fabric/files/323037/behave.zip)
## Describe How to Reproduce

make behave with 4 CPUs.

### PR DESCRIPTION
**Pull request by rameshthoomu**
## Description

Added python grpcio package installation steps in setupRHELonZ.sh script. Supporting code has been merged with PR# 1940.
## Motivation and Context

Fixes #1922 on Z machine
## How Has This Been Tested?

@jkirke @gongsu832  tested this in z machines.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by:thoomu@us.ibm.com

### CODE REVIEW

**Comment by rameshthoomu** [comment]
@vpaprots : Inputs please?

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by DanMcCarty** [comment]
reverify jenkins

**Comment by gongsu832** [comment]
@rameshthoomu The patch isn't going to work. You can't use https://github.com/grpc/grpc.git. Because it does not have the fixed boringssl. You need to use https://github.com/gongsu832/grpc.git.

**Comment by rameshthoomu** [comment]
@gongsu832 : there should not be any changes to this git repo after this.. Sure?

**Comment by gongsu832** [comment]
@rameshthoomu For now no there won't be any change to gongsu832/grpc.

BTW, the jenkins/x86_64 and jenkins/z builds are failing for reasons not related to the patch. I submitted a pull request yesterday (https://github.com/hyperledger/fabric/pull/2083) and it's failing the jenkins builds the same way. Somebody needs to fix the jenkins builds.

**Comment by rameshthoomu** [comment]
@gongsu832 : Z builds failed yesterday due to the firewall issue in Jenkins Z machine and x86 builds are failing with behave test failures. We are investigating behave test failures but not getting proper information from the failed build logs.. 

Fixed Firewall issue but we are hitting with another issue.. @DanMcCarty is working on this.

**Comment by gongsu832** [comment]
@rameshthoomu Good to know they are being worked on. Thanks.

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by srderson** [comment]
Any estimate on how long the wait will be until this patch makes it into the actual gRPC repository? Could we clone the actual repository then apply a patch as that may make it a bit more clear what was changed? @christo4ferris thoughts?

**Comment by s390xlinux** [comment]
The patch is not for gRPC, but rather boringssl which gRPC depends on. I just pushed the patch to boringssl which uses a separate system instead of github. I have no idea how long it will take for the patch to be merged. Even if the boringssl patch gets merge relatively quickly, it's still unknown when  gRPC will pick up the fixed version of boringssl. Because it currently uses a back version of boringssl.

**Comment by s390xlinux** [comment]
Well, it's actually simpler than I thought. The boringssl patch will NOT be merged. This is what I got from one of the code maintainer:

Adam Langley has posted comments on this change.

Change subject: Support for s390x and big endian
......................................................................

Patch Set 1:

I'm afraid that we don't support big-endian systems and deciding to support additional platforms is a big decision that we take very carefully. We would need to see significant demand for s390x support in Google's products and that has not been evident so far.

**Comment by Itpeoplecorp** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by gongsu832** [comment]
@rameshthoomu Since we are moving my patched version of boringssl into linux-on-ibm-z org, the way to build grpc on zLinux is slightly changed. The command sequence now is:

```
git clone https://github.com/grpc/grpc.git
cd grpc
pip install -rrequirements.txt
git checkout tags/release-0_13_1
sed -i -e "s/boringssl.googlesource.com/github.com\/linux-on-ibm-z/" .gitmodules
git submodule sync
git submodule update --init
cd third_party/boringssl
git checkout s390x-big-endian
cd ../..
GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install .
```

**Comment by rameshthoomu** [comment]
@gongsu832: Once your patch is moved to linux-on-ibm-z org, will submit new commit with the above mentioned changes. Please let me know once this is done..

**Comment by gongsu832** [comment]
It's already there.

**Comment by rameshthoomu** [comment]
PR #2200 has been created to address this issue. Closing this PR.

**Pull request closed without merging**
