### PR TITLE
Remove the sieve PBFT consensus plugin and all references to it

### PR DESCRIPTION
**Pull request by jyellick**
## Description

This changeset removes the code for the Sieve PBFT variant, as well as references to it, and 'classic' in both the documentation and tests.
## Motivation and Context

Sieve and classic are not PBFT implementations that are needed going forward into the v2 consensus model.

Sieve has always had serious and difficult to resolve bugs, and relies on an increasingly deprecated PBFT plugin architecture which is straining development resources to maintain.  Executing Sieve tests also slows down CI, and as well as local tests.
## How Has This Been Tested?

This is purely removal of an unsupported plugin, so CI should be sufficient.
## Checklist:

- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [X] I have either added documentation to cover my changes or this change requires no new documentation.
- [X] I have either added unit tests to cover my changes or this change requires no new tests.
- [X] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

The continuous integration build process will run [make checks](https://github.com/hyperledger/fabric/blob/master/Makefile#L22) to confirm that tests pass and that code quality meets minimum standards. You may optionally run this locally as PRs will not be accepted until they pass.

Signed-off-by: Jason Yellick jyellick@us.ibm.com

### CODE REVIEW

**Comment by tuand27613** [comment]
There are many people who have created docker or other virtual machine setups that reference classic and/or sieve. How about announcing in slack and the mailing lists and give folks a day or two of advance notice before we merge ?

Otherwise LGTM

**Comment by bcbrock** [comment]
I see you didn't remove Sieve and Classic from busywork. Don't worry - I will do that.

**Comment by jyellick** [comment]
@bcbrock I'd actually meant to call this out in the PR text, but forgot. Thanks for noticing and volunteering!

**Comment by corecode** [comment]
+1

**Comment by srderson** [comment]
Thanks, LGTM. A note was sent to the mailing list

**Pull request merged**
