### PR TITLE
Fix for Issue #1280 "Deploying invalid chaincode gives unclear error"

### PR DESCRIPTION
**Pull request by spomytkin**
Fix for Issue #1280 
## Description

```
per conversation with Sheehan Anderson  changed message to the:
"go get command failed in getCodeFromHTTP.  This may be an issue with
the network or compilation"
```
## How Has This Been Tested?

deployments of  chaincode via co-located peer process in latest vagrant environment
- from local filesystem: valid& compilable, non-compilable, missing 
- from http:valid& compilable, non-compilable, missing
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [ ] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Sergey Pomytkin  spomytkin@gmail.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
@srderson might be worthwhile cleaning up all of the error handling/logging here. none of the error messages are likely clear because they lack context. also, why aren't we using go-logging for this? Seems like we should be preparing for use of syslog or similar interface for collecting logs when we run this in production at scale.

Otherwise, LGTM

**Comment by muralisrini** [comment]
@spomytkin : the following is what I meant by scraping output. Key is to extract the string from the bytes.  If it works it should provide readable context to help users turnaround chaincode errors quickly. 

@christo4ferris : the error from this function does get go-logged up the stack. But agree we need a coherent approach to error handling.

```
        // Use a 'go get' command to pull the chaincode from the given repo
        cmd := exec.Command("go", "get", path)
        ...
        var errBuf bytes.Buffer
        cmd.Stderr = &errBuf //capture Stderr and print it on error
        err = cmd.Start()
         ...
         ...
        select {
         ....
        case err = <-done:
                // If we're here, the 'go get' command must have finished
                if err != nil {
                        err = fmt.Errorf("'go get' failed with error\n\"%s\"\n", err, string(errBuf.Bytes()))
                }
        }
```

Sample output from the above

image

**Comment by srderson** [comment]
@muralisrini ah, @spomytkin showed the me the bytes, did not realize there was a useful string hidden in there. @spomytkin - would it be possible to convert the bytes to string a @muralisrini suggests?

**Comment by spomytkin** [comment]
Yes. I'll update the code to include converted string

**Comment by spomytkin** [comment]
did the change, tested and created new pull reuest: https://github.com/hyperledger/fabric/pull/1506
Should I just close this one?

**Comment by srderson** [comment]
@spomytkin Thanks! Yeah, I'll close this one.

**Pull request closed without merging**
