### PR TITLE
Angrbrd transaction api

### PR DESCRIPTION
**Pull request by angrbrd**
Signed-off-by: Anna D Derbakova adderbak@us.ibm.com

### CODE REVIEW

**Comment by ghaskins** [comment]
LGTM

The CI failures are not believed to be related to this patch.  I am running the tests locally now and will commit this if they pass.

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Comment by ghaskins** [comment]
Confirmed that unit/behave passes.  Talking to @srderson last night, we agreed to hold off on any merges until the CI issues (unrelated to this PR) were resolved.  It seems like @muralisrini has root caused the issue now and it is probably thus safe to merge this.  However, I will wait for an ack from @srderson to open the doors for merges again.

**Comment by rameshthoomu** [comment]
@ghaskins @srderson : Unit tests are failing after commit#eb287d4 merged into master repo. Please check issue #1380

**Comment by srderson** [comment]
Rerunning now that issue #1380 is resolved.

**Comment by srderson** [comment]
Build failure is issue #1358

**Comment by ghaskins** [comment]
I agree, not related to this PR

**Comment by srderson** [comment]
LGTM. @angrbrd nice job on the documentation here.

**Comment by srderson** [comment]
Are these new node tests integrated in Travis? It looks like they're not. Do we have an open issue to add them to Travis? Maintainers will not be able to run them manually for every PR.

**Comment by christo4ferris** [comment]
@angrbrd you could add your test execution (I think) after the go tests on line 42 of the .travis.yml @srderson

**Comment by christo4ferris** [comment]
@angrbrd you might talk to @rameshthoomu if you have questions, but should be pretty self-explanatory

**Comment by srderson** [comment]
Discussion regarding travis integration took place in the Hyperledger slack on the #fabric channel and #fabric-ci-status channel. @rameshthoomu and @ghaskins are looking at solutions. We agreed to merge this PR now and the travis integration will be a second PR.

**Comment by rameshthoomu** [comment]
Integration of nodesdk tests in Makefile has been done and it's working as expected but @angrbrd suggested me to hold on this for couple of days as the team is working on adding more tests to it.

Also, below is the observation while running build process using Travis CI:
Sometimes Travis CI is taking more than 49 mins for each build before it fail the build due to timeout. If we integrate nodesdk tests as part of unit-test verification process, overall build time may increase further. Below are the changes made in Makefile: 

https://github.com/rameshthoomu/hyperledger-fabric/blob/unittest-nodesdk/Makefile#L65

**Pull request merged**
