### PR TITLE
Removed VAGRANT env check for executing CAR platform test

### PR DESCRIPTION
**Pull request by xspeedcruiser**
## Description

To remove the conditional check for VAGRANT env to run the CAR platform unit test
## Motivation and Context

Due to the presence of this conditional check, CAR platform unit test is not run on all platforms

Fixes #
## How Has This Been Tested?

This is a fix to the existing test case, which was not run on all platforms

## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

The continuous integration build process will run [make checks](https://github.com/hyperledger/fabric/blob/master/Makefile#L22) to confirm that tests pass and that code quality meets minimum standards. You may optionally run this locally as PRs will not be accepted until they pass.

Signed-off-by: satheesh.ceg@gmail.com

### CODE REVIEW

**Comment by xspeedcruiser** [comment]
Signed-off-by: satheesh.ceg@gmail.com

**Comment by srderson** [comment]
@ghaskins does this test pass in Travis and Jenkins now? Was the dependency issue resolved?
https://github.com/hyperledger/fabric/pull/1335

I'm rerunning Travis now to confirm as it failed due to an earlier build error unrelated to this PR.

**Comment by ghaskins** [comment]
@srderson Yes, the conditions that precipitated the need for this conditional have since been resolved by the addition of the Makefile mechanism.  @xspeedcruiser submitted this patch at my request after discussing why the conditional was there, to begin with.

**Comment by srderson** [comment]
Thanks @ghaskins and @xspeedcruiser. LGTM

**Pull request merged**
