### PR TITLE
Asset Management App

### PR DESCRIPTION
**Pull request by adecaro**
This PR is the result of the discussion had in #1247.

More specifically, the PR contains an application that shows how to invoke the asset management chaincode. The app works like this: it bootstraps a non-validating peer and constructs fabric transactions to deploy, invoke and query the asset management chaincode.
The details are described in the readme files.

@tuand27613, please, may you verify this PR to ensure that the app behaves as described in the readme files? Thanks.

Signed-off-by: Angelo De Caro adc@zurich.ibm.com

### CODE REVIEW

**Comment by tuand27613** [comment]
LGTM.
Thanks @adecaro for having the READMEs. That made things so much easier to follow

**Comment by srderson** [comment]
This PR has a merge conflict and needs to be rebased on master.

**Comment by adecaro** [comment]
@srderson, done :)

**Comment by srderson** [comment]
Is it possible to write a behave test to exercise this chaincode?

**Comment by srderson** [comment]
Build failure is just issue #1358

**Comment by adecaro** [comment]
@srderson, actually @jeffgarratt is writing such a behave test which will be further extended once the client-sdk will be available. In fact, this PR is meant to show how to exercise the chaincode with what we currently have in the fabric :)

**Comment by srderson** [comment]
LGTM. Spoke with @tuand27613 and confirmed behave test is blocked by SDK and on the way. @adecaro Nice to see a README with the sample chaincode, thanks.

**Pull request merged**
