### PR TITLE
Globally change unofficial Docker port 4243 to official port 2375

### LINKED ISSUE #1263: Change Docker TCP port to 2375
At the time the openblockchain project was started within IBM, there was a convention in wide use to use TCP port 4243 for the Docker REST API, so we currently use 4243. Since that time, the IANA has [registered](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=docker) ports 2375 and 2376 to Docker for their insecure and secure interfaces respectively.

All code, scripts and documentation should be changed to use port 2375 for the Docker interface. I can't think of any reason why hyperledger/fabric should use a non-standard interface to Docker. A very good reason to make this change is that it will likely be consistent with the way that clients will configure their production (non-Vagrant) systems. This will also allow the code to auto-discover (actually, make an intelligent guess) at the CORE_VM_ENDPOINT if not explicitly specified. Finally, port 4243 is officially reserved for another purpose.

I realize that this change will likely cause some hiccups, but it is the right thing to do, and better to do sooner rather than later.

### PR DESCRIPTION
**Pull request by bcbrock**
Fixes #1263

### CODE REVIEW

**Comment by bcbrock** [comment]
Signed-off-by: Bishop Brock bcbrock@us.ibm.com

**Comment by srderson** [comment]
@bcbrock Do the behave tests pass for you with this PR? When I run them I see the following in a number of tests.

```
When I query chaincode "example2" function name "query" on "vp0"                                                            # steps/peer_basic_impl.py:208 0.179s
      | arg1 |
      | a    |
      Assertion Failed: Failed to POST to http://172.17.0.2:5000/devops/query:  {"Error": "Error:Failed to launch chaincode spec(Error starting container: cannot connect to Docker endpoint)"}
      Captured stdout:
      ['Creating', 'bddtests_vp0_1']
      ['bddtests_vp0_1']
      dockerComposeService = vp0
      container bddtests_vp0_1 has env = ['CORE_PEER_ID=vp0', 'CORE_VM_ENDPOINT=http://172.17.0.1:2375', 'CORE_PEER_ADDRESSAUTODETECT=true', 'CORE_LOGGING_LEVEL=DEBUG', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/go/bin:/opt/gopath/bin', 'HOSTNAME=e8c6f43a4fec', 'PWD=/', 'SHLVL=1', 'HOME=/root', 'GOROOT=/opt/go', 'GOPATH=/opt/gopath', '_=/usr/bin/printenv']

      Requesting path = http://172.17.0.2:5000/chain

      Requesting path = http://172.17.0.2:5000/devops/deploy
      {
          "chaincodeID": {
              "path": "github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02", 
              "name": "5844bc142dcc9e788785e026e22c855957b2c754c912702c58d997dedbc9a042f05d152f6db0fbd7810d95c1b880c210566c9de3093aae0ab76ad2d90e9cfaa5"
          }, 
          "type": 1, 
          "ctorMsg": {
              "function": "init", 
              "args": [
                  "a", 
                  "100", 
                  "b", 
                  "200"
              ]
          }
      }

      GETing path = http://172.17.0.2:5000/transactions/5844bc142dcc9e788785e026e22c855957b2c754c912702c58d997dedbc9a042f05d152f6db0fbd7810d95c1b880c210566c9de3093aae0ab76ad2d90e9cfaa5
      GETing path = http://172.17.0.2:5000/transactions/5844bc142dcc9e788785e026e22c855957b2c754c912702c58d997dedbc9a042f05d152f6db0fbd7810d95c1b880c210566c9de3093aae0ab76ad2d90e9cfaa5
      GETing path = http://172.17.0.2:5000/transactions/5844bc142dcc9e788785e026e22c855957b2c754c912702c58d997dedbc9a042f05d152f6db0fbd7810d95c1b880c210566c9de3093aae0ab76ad2d90e9cfaa5
      Result of request to all peers = {'bddtests_vp0_1': 200}

      Requesting path = http://172.17.0.2:5000/chain

      POSTing path = http://172.17.0.2:5000/devops/query

      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2
```

I did not let them complete, so I'm not sure if there are additional errors.

**Comment by bcbrock** [comment]
@srderson - I just pulled in the latest master branch and ran again: 100% success on behave - 1 error on Go tests I'm looking into now. Before you ran your tests, did you reconfigure the Docker server to use port 2375? 

Also note that if this change gets merged, it's _possible_ that the CI environment will start failing. I know that @rameshthoomu had to do some fixups similar to this to get the behave tests to work in Travis - he might have to change them. (Which is another reason for this change, to avoid having to do those fixups in the first place.)

**Comment by bcbrock** [comment]
The failing Go test (mentioned above) is the new platforms/car/test that Greg Haskins just added. It has a lot of dependencies that aren't being met on my system. I don't think the failure has anything to do with this change.

**Comment by srderson** [comment]
@bcbrock I missed the change in `devenv/setup.sh`. Will give that a try.

**Comment by rameshthoomu** [comment]
@bcbrock I am dynamically changing 4243 to 2375 (Travis docker port) in compose-defaults.yml file with the below command.

`sed -i -e 's/172.17.0.1:4243\b/'"$ip:$port"'/g' $HOME/gopath/src/github.com/hyperledger/fabric/bddtests/compose-defaults.yml`

After merge of this PR, I think no need to do above step.

**Comment by srderson** [comment]
@bcbrock Can you rebase this on master please? I want to accept it with https://github.com/hyperledger/fabric/pull/1411 so developers are only required to run `vagrant destory` `vagrant up` once.

**Pull request closed without merging**
