### PR TITLE
Revert "Optimize peer/membersrvc -image generation"

### PR DESCRIPTION
**Pull request by ghaskins**
DO NOT MERGE

This reverts commit 85837442c2dfb92cf0be0455581387bfbe0c2f48.

### CODE REVIEW

**Comment by rjones-lf** [comment]
reverify jenkins

**Comment by rjones-lf** [comment]
reverify jenkins

**Comment by rjones-lf** [comment]
reverify jenkins

**Comment by ghost** [comment]
well, it passed on Z

**Comment by ghaskins** [comment]
Interesting...checking on the other PR now...

**Comment by ghaskins** [comment]
#1836 / #1834 would be the preferred solution here, but those still seem to be a mess w.r.t. CI.  Do we know what the deal is there?  E.g. are those CI processes failing because 1836/1834 do not fix the bug, or is there something else going on?

**Comment by ghaskins** [comment]
One more thing to note: I haven't looked closely, but I do not think _this_ PR completely removes the aspects of UID 0 (there are two docker targets that do the -v mapping, and this reverts only one of them).  

So....if this direction starts to look like the only viable path forward, we would need to address that second leak.

**Comment by ghost** [comment]
I think #1834 is the way to go - #1836 was my experiment in putting #1834 at the tip of master to see if it helped. I can abandon #1836.

Looking at the most recent failures, it didn't look like it was part of your change that caused the issue.

**Comment by rjones-lf** [comment]
reverify jenkins

**Comment by ghaskins** [comment]
Closing this for now because I am advocating #1834 for inclusion

**Pull request closed without merging**
