### PR TITLE
proposed language for the fabric-peer image description on DockerHub

### PR DESCRIPTION
**Pull request by christo4ferris**
## Description

proposed language for DockerHub description for fabric-peer image
## Motivation and Context

Fixes # N/A
## How Has This Been Tested?

markdown plugin for Atom. Usage was verified manually
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [N/A] I have either added unit tests to cover my changes or this change requires no new tests.
- [N/A] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Christopher Ferris chrisfer@us.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
LGTM. @joshhus @nickgaski any comments?

**Comment by nickgaski** [comment]
Line 9.  "If Docker running within Vagrant"  -> "If running Docker within Vagrant"

**Comment by christo4ferris** [comment]
@srderson Unfortunately, I deleted my fork because I messed it up trying to get another change through. If @nickgaski comment above is the only comment, I can address in a follow-on fresh PR.

**Comment by christo4ferris** [comment]
reverify Jenkins

**Comment by srderson** [comment]
@nickgaski thanks for the review.

@christo4ferris sounds good. Will merge this and look for follow-on PR. LGTM

**Pull request merged**
