### PR TITLE
don't create "simple" docker image- skip container/ unit tests as con…

### PR DESCRIPTION
**Pull request by muralisrini**
…tainer is covered by others

### CODE REVIEW

**Comment by muralisrini** [comment]
Signed-off-by: muralisr@us.ibm.com

**Comment by christo4ferris** [comment]
@muralisrini hard-coding the variable's value o_O? why not pass an argument?

**Comment by muralisrini** [comment]
@christo4ferris : added a command line option "-run-controller-tests" to run the tests in controller_test.go so users do not have to change code. Default is to not run them.

**Comment by christo4ferris** [comment]
@muralisrini :-)

**Comment by srderson** [comment]
LGTM

**Pull request merged**
