### PR TITLE
Mem leak fixes/issue#589

### PR DESCRIPTION
**Pull request by muralisrini**
some fixes for mem leak.  This takes care of some big leaks.

As discussed with @jeffgarratt, one issue still remains. gRPC NewClientStream and friends created in sendTransactionsToThisPeer are not getting GCed. All relevent transport clean up calls (in particular, Close and CloseSend) and channel notifications are in place and appear to be working as expected. One (remote and startling) possibility is  local gRPC is suspect and somehow keeps references to these data structures.

Assigning to @jeffgarratt for investigating this. Can pick it up in a few days,

### CODE REVIEW

**Comment by muralisrini** [comment]
Signed-off-by: muralisr@us.ibm.com

**Comment by binhn** [comment]
@jeffgarratt I assume you would continue on this PR and not merge it just yet, right?

**Comment by jeffgarratt** [comment]
@binhn correct

**Comment by muralisrini** [comment]
@jeffgarratt : PR #607 ready for review / merge

**Pull request merged**
