### PR TITLE
Use Role type instead of int32 and fix wrong test link

### PR DESCRIPTION
**Pull request by GrapeBaBa**
Use Role type instead of int32 in membersrvc package and fix wrong test link
## Description

Use Role type in ca.pb.go to replace int32 in some codes and fix wrong test link in contributor file. 
## Motivation and Context

Use specific type seems more readable and avoid magic number.
## How Has This Been Tested?

Unit and Behave Tests have  been passed.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [ ] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Kai Chen 281165273@qq.com

### CODE REVIEW

**Comment by GrapeBaBa** [comment]
Signed-off-by: Kai Chen 281165273@qq.com

**Comment by srderson** [comment]
This looks like an improvement to me. @diegomasini or @adecaro, would you take a look?

**Comment by angrbrd** [comment]
Yes, this looks good. I have taken a look also.

**Comment by ghaskins** [comment]
This LGTM as well.  @srderson do we need more SME input or should this go in?

**Comment by srderson** [comment]
LGTM, we can merge this now.

**Pull request merged**
