### PR TITLE
New architecture

### PR DESCRIPTION
**Pull request by gabre**
In this PR, we tried to start the conversion of fabric towards the new architecture (https://github.com/hyperledger/fabric/wiki/Next-Consensus-Architecture-Proposal).
## Description

The PR and the implementation is not complete, we would like to get feedback.
The PR contains the following changes:
- A proto file was added describing all the new message types and services needed by endorsers (endorser-api) and consenter peers (consensus-api).
- A consensus service was introduced. For a node, whether to act as a consenter can be enabled/disabled from configuration. Other nodes use consensus-api to connect to the consensus layer.
- Nodes ask for endorsements before forwarding a transaction to the consensus. Enabled/disabled status of the endorsement service on a node can be configured in core.yaml. Endorsers can be reached using endorser-api.
- Nodes observe the consensus-layer using a consensus observer and consensus-api and commit to the ledger if a new consensus is made. (Ledger related functionalities were moved from consensus to core)

Functionalities missing:
- Real endorsement checking is needed (not just the endorsement count but signature verification). It is a question how we could handle private/public keys and signatures (Do we need a CA? Do we need preconfigured key lists? What about using Schnorr signatures?)
- Some ledger related code needs to be removed from consensus and maybe moved to core if it is still needed. (The TX execution and commitment are done in consensus-observer)
- All the fields of all the records from consensus-api.proto needs to be populated with real, meaningful values.)
## Motivation and Context

The motivation is to begin work on new architecture and start discussion on implementation level problems.

Fixes #
## How Has This Been Tested?

BDD tests will be added.
## Checklist:

- [] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [] I have either added documentation to cover my changes or this change requires no new documentation.
- [] I have either added unit tests to cover my changes or this change requires no new tests.
- [] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by:
Gabor Hosszu gabor@digitalasset.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
@gabre this has some linter errors that need to be resolved. see the Travis output.

**Comment by srderson** [comment]
For the read set and write set, what about

```

message VerDep {
      repeated VarRead readSet = 1;
      repeated VarWrite writeSet = 2;
 }

message VarRead {
    string key = 1;
    bytes version = 2;
} 

message VarWrite {
    string key = 1;
    bytes value = 2;
    bytes version = 3;
}
```

**Comment by srderson** [comment]
Making a note to myself to consider the following transaction tomorrow

```
Read key A version 1
Write key A version 2
Read key A version 2
Write key A version 3
```

Need to consider if that order needs to be preserved which I cannot be in the above data structure.

**Comment by gabre** [comment]
@christo4ferris Yes I know about that, I will fix it. This is still a proposal, we would like to have more feedback on this (see my questions in the files, the proto definitions and the "lower level" implementation details). I would like to encourage everybody to give us feedback and suggestions.

**Comment by gabre** [comment]
@srderson What about making just one set of repeated VarUsage s (I was unable to find a better name, Usage = Read U Write U EveryThingElseOneCanThinkOf, U stands for union) and this way we could preserve the order if needed? Just came into my mind, haven't considered it deeply..

**Comment by srderson** [comment]
Something @manish-sethi mentioned this morning based on the conversation at https://github.com/hyperledger/fabric/issues/1631 is that maybe `versionDependencies` should just be bytes

```
message TransactionProposal {
    enum TxContentType {
        TRANSPARENT = 0;
        OPAQUE = 1;
        COMMITMENT = 2;
        NONE = 3;
    }

    string submitingPeerID = 1;
    string clientID = 2;
    bytes chaincodeID = 3;
    TxContentType txContentType = 4;
    bytes txContent = 5;
    bytes versionDependencies = 6;
}
```

This allows different ledger implementations to handle the simulation/results differently. This is very powerful as it allows for unlimited flexibility and does not lock us into the readSet/writeSet concept.

The default implementation would store a read/write set in these bytes. It would look something like

```
message VerDep {
      repeated VarRead readSet = 1;
      repeated VarWrite writeSet = 2;
 }
```

Also @manish-sethi and I confirmed that only the first reads and last writes of a key in a transaction need to be stored so we don't need to worry about capturing intermediate reads/writes.

Thoughts?

**Comment by christo4ferris** [comment]
@gabre @srderson have we migrated this discussion to Gerrit?

**Comment by christo4ferris** [comment]
@gabre we will be transferring the fabric and fabric-api repository and all the corresponding issues and pull requests to the hyperledger-archives org on GH and replacing this repository with a read-only mirror of our Gerrit source. As a result, any automatic GH redirects will be broken. If you haven't already migrated your PR to Gerrit, and intend to do so, you will need to change your git remote to reference the transferred repository (e.g. git@github.com:hyperledger-archives/fabric) on your local clone.

**Pull request closed without merging**
