### PR TITLE
sieve: do not bypass pbft state machine, #1366

### PR DESCRIPTION
**Pull request by corecode**
Signed-off-by: Simon Schubert sis@zurich.ibm.com

### CODE REVIEW

**Comment by corecode** [comment]
Linking #1366

**Comment by jyellick** [comment]
@corecode Looks good to me, just spotted this in reviewing #1368, this should fix that issue as well.

**Comment by corecode** [comment]
This should also fix #1368.

**Comment by srderson** [comment]
Is there a test case for this issue?

**Comment by jyellick** [comment]
@srderson Both issues associated with this are races, and occur because two threads start concurrently modifying the internal pbft state.  Since it is a race, any test would most likely be non-deterministic.

**Comment by srderson** [comment]
ok, LGTM

**Comment by lindluni** [comment]
> Nit, but I think we should be updating the version in the vagrant box as well. While it's rarely used, it is a working, viable development environment.

Agreed, I just realized vagrant was on 1.14.2 so I missed it when I grepped for 1.14.1.

Opened #1389

**Pull request merged**
