### PR TITLE
Nominate Jonathan Levi as a maintainer

### PR DESCRIPTION
**Pull request by srderson**
## Description

Nominate Jonathan Levi @JonathanLevi as a maintainer of Hyperledger Fabric. See http://lists.hyperledger.org/pipermail/hyperledger-fabric/2016-July/000160.html for details.

Based on the rules described under the “Becoming a maintainer” section in the [CONTRIBUTING document](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md), existing maintainers should add a comment indicating if they agree with Jonathan's addition as a new maintainer on the project.

Signed-off-by: Sheehan Anderson sheehan@us.ibm.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
+1

**Comment by srderson** [comment]
+1

**Comment by GrapeBaBa** [comment]
@JonathanLevi Great job. Congratulations.

**Comment by ghaskins** [comment]
+1

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by rameshthoomu** [comment]
reverify jenkins

**Comment by tamasblummer** [comment]
+1

**Comment by srderson** [comment]
Looks like there is a majority. Congrats @JonathanLevi

**Comment by JonathanLevi** [comment]
Thank you vm everyone!

**Pull request merged**
