### PR TITLE
Confidentiality 2.0

### PR DESCRIPTION
**Pull request by adecaro**
This PR implements confidentiality as described in Section 4.3.2.1 (Confidentiality against users) of the protocol spec document. The previous versions are still available. The default version of confidentiality will remain 1.2. The new version can be activated by setting the field "ConfidentialityProtocolVersion" in "ChaincodeSpec" to "2.0".

Signed-off-by: Angelo De Caro adc@zurich.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
@adecaro This PR needs to be rebased as some PRs were accepted out of order. Apologies for the inconvenience.

**Comment by adecaro** [comment]
@srderson, rebased :)

Let me add also a remark about this PR: The code impacts mainly the crypto layer to offer the next version of confidentiality. The PR is not supposed to affect the way the fabric is operated :)

**Comment by srderson** [comment]
@adecaro This is a big change! Please try to keep them smaller in the future if possible as it makes review a bit easier. Is there a security expert who could give a first pass review and LGTM comment on this PR? Maybe @elli-androulaki or @diegomasini?

**Comment by muralisrini** [comment]
Also @adecaro, as far as I could tell the only "non-crypto" files touched were chaincode_support.go and exectransaction.go (is that correct?). Could you add a comment about the "TransactionPreExecution" api changes to those files please ?

**Comment by adecaro** [comment]
@srderson Let me apologize for this massive change. I took also the opportunity to refactor the crypto layer to make it more easy to extend. 

@muralisrini In Confidentiality 2.0, in order to allow PreExecute to process an invoke or query transaction, the corresponding deploy transaction must be passed. This is required to retrieve crypto material from the deploy transaction. I would add also that this is also a more general approach with the respect to what we had in the past. 

In order to be able to pass the deploy transaction, PreValidate decrypts the chaincodeID that is so available when it is required.

I want to stress that Confidentiality 2.0 is not active by default. Therefore it will not impact the way the fabric is operated right now.

**Comment by BiscuitBomber** [comment]
This PR/work should really be broken down to smaller pieces and resubmitted, especially if

> Confidentiality 2.0 is not active by default. Therefore it will not impact the way the fabric is operated right now.

To agree with the contribution guidelines, will it be possible to separate/isolate the actual feature/functionality you propose and to:
- separate the many changes of just tabs and spaces
- use meaningful check-in comments (other than the "**minor changes**", **"minor fix"** and **"fixing bugs"**)
- separate the massive renaming of 'conf' to 'primitives'
- fix the introduced lint errors 

At the moment, it is not possible to view the all the diffs (see above the error message from GitHub in Yellow)

> Sorry, we could not display the entire diff because it was too big.

Other than adhering to the contribution guidelines, PRs should make it easier (possible) to view the actual feature work (confidentiality 2.0, in this case).

---

Because poetry is the synthesis of hyacinths and biscuits.

**Comment by adecaro** [comment]
@BiscuitBomber I agree that this PR contains a lot of juice and the commit comments are not really helpful. I apologize for this.

I'm not sure anyway that breaking down this PR is the right thing to do for the following reasons:
1. This PR contains a new security protocol.  If I break it down then the system will be inconsistant and the tests will fail. 
2. With this PR, I took also the opportunity to refactor the crypto layer because it needs to evolve fast to reach a mature state. Notice that, no external interface has been changed apart from a single method to PreProcess transactions.
3. The crypto layer needs to evolve more and I need this PR in to start a new refactoring process to offer more advanced protocols and more flexibility in the configuration. Refactoring is unavoidable to reach a mature state and because we are still in an incubator state, this is the right time to do that.

Regarding the diff, they can be seen more easily looking at the single commits :)

Thanks a lot for the feedback.

**Comment by BiscuitBomber** [comment]
Dear @adecaro,

Thank you so much for the time you spend discussing this further. Frankly, I don't know what my request was missing, but let's go over this again:

> If I break it down then the system will be inconsistant and the tests will fail. 

I am confused as to how will adhering to the contribution guidelines by
- separating the many changes of just tabs and spaces
- using meaningful check-in comments (other than the "minor changes", "minor fix" and "fixing bugs")
- separating the massive renaming of 'conf' to 'primitives'

and,
- fixing the introduced lint errors

will make the system inconsistent and the test will fail?

---

Also, it is questionable whether

> this PR contains a lot of juice 

that's the point that everybody is making. This PR certainly contains a LOT of white-space changes and renaming (conf/util/primitives).

A few people (please see above) have already expressed their dissatisfaction with this PR. It is hard to see the forest through the trees.

---

> I took also the opportunity to refactor the crypto layer because it needs to evolve fast to reach a mature state.

This is great! We are not asking you not to do so. What we are asking is that you re-submit this 'refactoring' work separately (for example under 'renaming **conf** to **primitives**')

---

> Refactoring is unavoidable to reach a mature state and because we are still in an incubator state, this is the right time to do that.

Again, nobody questions or claims that the crypto layer does not need to evolve or that it does not need refactoring. I don't see how this claim is related to what we are asking you to do or how one needs to submit (or review!) such a convoluted PR.

---

Please kindly comply with the contribution guidelines and then we'll start taking a look at the "Confidentiality 2.0" feature.

---

> "I'm not sure anyway that breaking down this PR is the right thing to do"

[ _sigh_ ]

OK, I have gone through all your arguments, and I don't see how your answer addresses what we are asking. 

A bit disappointed in myself for not being able to get my point across.Let's try the following, and I'll continue to take a look at this when I wake up tomorrow.

Can you please refer to the specific things asked from you. To help you, let's try to use this structure:
- **I cannot separate the renaming of conf to primitive, it has to be part of the Confidentiality 2.0 PR, because** ...
- **I simply cannot fix the introduced lint errors** because .... or, **The introduced lint errors have to be part of the Confidentiality 2.0 PR** because ....
- **I cannot use meaningful check-in comments** because ... 
- **I MUST change the tabs and spaces in this PR** because ...

---

> appreciate the feedback

Your welcome. Please also appreciate our time (and simply fix and resubmit separately) to make it easier for us to go over your real/actual suggested changes.

Good night.

---

Because poetry is the synthesis of hyacinths and biscuits.

**Comment by adecaro** [comment]
@BiscuitBomber, thank you for the prompt clarification.
@BiscuitBomber, @srderson, @muralisrini, I apologize for the waste of time I have produced.

I close this pull request and resubmit. Thanks.

**Pull request closed without merging**
