### PR TITLE
Added some clarification about the state and origin of this project

### PR DESCRIPTION
**Pull request by lehors**
Signed-off-by: Arnaud J Le Hors - lehors@us.ibm.com

### CODE REVIEW

**Comment by lehors** [comment]
Signed-off-by: Arnaud J Le Hors lehors@us.ibm.com

**Comment by binhn** [comment]
@lehors I would suggest this change be on the repo (fabric) description rather than in the readme of the code, so that developers don't have to be sidetracked with anything else but set up instruction.

**Comment by lehors** [comment]
@binhn I understand. I don't have access rights to the repo description so, you'll have to make the change then.
I do think it is important to respond to the concerns expressed by several people that the status isn't clear enough and the name may lead people to believe this is **the** fabric of the Hyperledger Project rather than just an incubator.

**Comment by binhn** [comment]
@lehors Ok, I can bring your changes over to the repo description and close this PR. Thanks

**Comment by lehors** [comment]
@binh Please, change the link to the new project lifecycle page: https://github.com/hyperledger/hyperledger/wiki/Project-Lifecycle
We can close this PR after that.
Thanks.

**Pull request closed without merging**
