### PR TITLE
Remove unused env variable

### PR DESCRIPTION
**Pull request by GrapeBaBa**
## Description

Refer comments in issue #1796 by @JonathanLevi @jeffgarratt , remove unused variable in bddtests
## Motivation and Context

Discussion with @JonathanLevi , remove this env variable
## How Has This Been Tested?

All test passed.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by:Kai Chen ckaiwh@cn.ibm.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
This variable isn't referenced in the code, but it is mentioned numerous times in docs. Probably should remove it wherever it occurs and test.

**Comment by GrapeBaBa** [comment]
@christo4ferris Sorry I cannot catch you which doc mentioned this variable.

**Comment by christo4ferris** [comment]
fabric$ grep -r "CORE_VM_ENDPOINT" .
./bddtests/compose-defaults.yml:    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
./bddtests/compose-defaults.yml:    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
./docs/dev-setup/devnet-setup.md:Your output might contain something like `inet 172.17.0.1/16 scope global docker0`. That means docker0 interface is on IP address 172.17.0.1. Use that IP address for the `CORE_VM_ENDPOINT` option. For more information on the environment variables, see `core.yaml` configuration file in the `fabric` repository.
./docs/dev-setup/devnet-setup.md:docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true hyperledger/fabric-peer peer node start
./docs/dev-setup/devnet-setup.md:docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_SECURITY_ENABLED=true -e CORE_SECURITY_PRIVACY=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.1:50051 -e CORE_SECURITY_ENROLLID=vp0 -e CORE_SECURITY_ENROLLSECRET=vp0_secret  hyperledger/fabric-peer peer node start
./docs/dev-setup/devnet-setup.md:docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp1 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_SECURITY_ENABLED=true -e CORE_SECURITY_PRIVACY=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.1:50051 -e CORE_SECURITY_ENROLLID=vp1 -e CORE_SECURITY_ENROLLSECRET=vp1_secret -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303 hyperledger/fabric-peer peer node start
./docs/dev-setup/install.md:Be aware that the Docker bridge (the `CORE_VM_ENDPOINT`) may not come
./examples/events/block-listener/README.md:docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft hyperledger/fabric-peer peer peer
./examples/events/block-listener/README.md:docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp1 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303 -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft hyperledger/fabric-peer peer peer
./examples/events/block-listener/README.md:docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp2 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303 -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft hyperledger/fabric-peer peer peer
./examples/events/block-listener/README.md:docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp3 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303 -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft hyperledger/fabric-peer peer peer
./scripts/idsBuild.sh:  ./docker -H $1 run --name=$2 --restart=unless-stopped -d -it -p $5:5000 -p $4:30303 -e CORE_VM_ENDPOINT=$COMPANION_HOST -e CORE_PEER_ID=$2 -e CORE_PEER_ADDRESSAUTODETECT=false -e CORE_PEER_ADDRESS=$3:$4 -e CORE_PEER_LISTENADDRESS=0.0.0.0:30303 -e CORE_VM_DOCKER_TLS_ENABLED=true -e CORE_VM_DOCKER_TLS_CERT_FILE="/companion_certs/cert.pem" -e CORE_VM_DOCKER_TLS_CACERT_FILE="/companion_certs/cacert.pem" -e  CORE_VM_DOCKER_TLS_KEY_FILE="/companion_certs/key.pem" openchain-peer obc-peer peer
./scripts/idsBuild.sh:  ./docker -H $1 run --name=$2 --restart=unless-stopped -d -it -p $6:5000 -p $4:30303 -e CORE_VM_ENDPOINT=$COMPANION_HOST -e CORE_PEER_ID=$2 -e CORE_PEER_ADDRESSAUTODETECT=false -e CORE_PEER_DISCOVERY_ROOTNODE=$5 -e CORE_PEER_ADDRESS=$3:$4 -e CORE_PEER_LISTENADDRESS=0.0.0.0:30303  -e CORE_VM_DOCKER_TLS_ENABLED=true -e CORE_VM_DOCKER_TLS_CERT_FILE="/companion_certs/cert.pem" -e CORE_VM_DOCKER_TLS_CACERT_FILE="/companion_certs/cacert.pem" -e  CORE_VM_DOCKER_TLS_KEY_FILE="/companion_certs/key.pem" openchain-peer obc-peer peer
./tools/busywork/bin/userModeNetwork:set ::env(CORE_VM_ENDPOINT)             [busywork::dockerEndpoint]

**Comment by GrapeBaBa** [comment]
If my understanding is right, that is all for core.yaml and for peer service. What I removed is for membersrvc.yaml and membersrvc service.

**Comment by JonathanLevi** [comment]
Sorry, more context: when working to clean up some more tests/YAML, we wanted to make a small change to the structure of the TLS section in `membersrvc.yaml` (started and detailed in #1796), @GrapeBaBa found out that the YAML file also contains the `CORE_VM_ENDPOINT=http://172.17.0.1:2375`. While CORE indeed needs `CORE_VM_ENDPOINT` and it is used in many places for the docker services, Membership Services clearly does not need it (and thank you again @jeffgarratt, for confirming this). 

@christo4ferris I can see how the title could make it sound at first as if this PR suggests that the Env variable is to be removed entirely because it's not used at all (the env variable is used all over the place, indeed), my apologies. Effectively, we could not find a reference to it in the Membership Service code or any usage, hence the suggestion/this PR **to remove this one instance of the CORE_VM_ENDPOINT env variable** from **the Membership Service section only** of the YAML...

**Comment by ghost** [comment]
reverify jenkins

**Comment by srderson** [comment]
LGTM, thanks!

**Comment by GrapeBaBa** [comment]
@JonathanLevi Thanks your clarify. @christo4ferris Sorry for confusing,  I  will add more specific title and summary in future.

**Comment by JonathanLevi** [comment]
OMG, the dco-bot runs on coffee too! ;-)

It's all good @GrapeBaBa, it proved good to cover the 2 time-zones thanks again for this!

**Pull request merged**
