### PR TITLE
Use pip install docker-compose

### PR DESCRIPTION
**Pull request by GrapeBaBa**
## Description

Update host.sh, use pip install docker-compose instead of curl
## Motivation and Context

1.More consistent with setupRHELonZ.sh
2.It is faster than docker-compose official site for people network not good.
## How Has This Been Tested?

no test
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by:Kai Chen ckaiwh@cn.ibm.com

### CODE REVIEW

**Comment by GrapeBaBa** [comment]
re-trigger Travis

**Comment by GrapeBaBa** [comment]
@ghaskins Would you like review?

**Comment by GrapeBaBa** [comment]
@ghaskins Are you available for reviewing this PR?
@rameshthoomu Would you like help re-trigger travis build?

**Comment by rameshthoomu** [comment]
@GrapeBaBa: I don't have access to restart the builds on Travis. As we moved to Gerrit now, we are verifying builds only in Jenkins CI machines not in Travis.  If you still want to test this PR in Travis,  please check with ghaskin or srderson to restart the build.

**Comment by GrapeBaBa** [comment]
Not need.

**Pull request closed without merging**
