### PR TITLE
Persistence and more; #1000

### PR DESCRIPTION
**Pull request by corecode**
This addresses #1000 and many other small bug fixes.

Signed-off-by: Simon Schubert sis@zurich.ibm.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
re-running TravisCI build

**Comment by corecode** [comment]
Is there a way to obtain the behave logs?  I'd guess this is a timing issue again.

**Comment by srderson** [comment]
@corecode could you rebase this? Thanks

**Comment by binhn** [comment]
@jyellick or @tuand27613 could you guys help review this PR.  My naive observation is that I don't see a behave test here to cover issue #1000, and I can't tell whether the unit tests cover the said small bug fixes.

**Comment by jyellick** [comment]
@binhn This entire PR should be included in #1325 and has those conflicts resolved.  I believe this PR can be closed, pending confirmation from @corecode

**Comment by corecode** [comment]
All of this has been folded into #1325

**Comment by corecode** [comment]
The behave test for issue680 also tests for persistence.

**Pull request closed without merging**
