### PR TITLE
Fix little typo

### PR DESCRIPTION
**Pull request by GrapeBaBa**
## Description

Fix little typo.
## Motivation and Context

Fix typo.
## How Has This Been Tested?

No test as just fix md file.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by:Kai Chen ckaiwh@cn.ibm.com

### CODE REVIEW

**Comment by corecode** [comment]
Why is "Git Hub" a typo of "GITHUB"?  If anything, it should probably be "GitHub".

**Comment by GrapeBaBa** [comment]
@corecode 
OK, actually I just want to remove the space

**Comment by ghaskins** [comment]
I agree with @corecode

**Comment by christo4ferris** [comment]
agree with @corecode and @ghaskins should be GitHub

**Comment by GrapeBaBa** [comment]
Fixed.

**Comment by corecode** [comment]
I suggest rebasing this branch to fold the multiple commits into a single one.

**Comment by kchristidis** [comment]
We may as well do this right. As @corecode had noted, proper styling is: GitHub (capital H).

**Comment by GrapeBaBa** [comment]
@kchristidis My mistake.Fixed.

**Comment by srderson** [comment]
LGTM. Thanks!

**Pull request merged**
