### PR TITLE
move out install instructions

### PR DESCRIPTION
**Pull request by joequant**
This commit moves the install instructions out of the README.md which makes the repository more friendly to newbies.

Signed-off-by: Joseph Wang joequant@gmail.com

### CODE REVIEW

**Comment by christo4ferris** [comment]
@joequant the reference to CONTRIBUTING.md should be preserved in the main README.md - could you please restore that? I like pulling out the gory details otherwise.

**Comment by joequant** [comment]
Just fixed up the file.  Also I don't recall the standard process for
getting onto slack documented anywhere.

**Comment by christo4ferris** [comment]
@joequant https://slack.hyperledger.org/ is signup page - also listed on hyperledger.org/community

**Comment by srderson** [comment]
@joequant  Sorry, could you rebase and resubmit? Some PRs were merged out of order.

The changes that I'm aware of
1) There's now an 'Incubation Notice' in the README. I believe that has to stay there.
2) The location of the binary changed which resulted in some paths being updated from `$GOPATH/src/github.com/hyperledger/fabric` to `$GOPATH/src/github.com/hyperledger/fabric/peer`

**Comment by joequant** [comment]
Rebased and resubmitted.

**Comment by srderson** [comment]
Thanks. @christo4ferris Could you review please and make sure all the relevant information is where it needs to be? Thanks

**Comment by binhn** [comment]
I don't agree with the changes: Both files contain inconsistent information. We should wait for @joshhus to address #1125 then point the readers to appropriate section/document.

**Comment by srderson** [comment]
@binhn IMO this PR is a step in the right direction. Could you give more detail about what inconsistent information the files contain? It seems that the existing install information was just moved from README.md to INSTALL.md which seems more consistent with other open source projects.

In a future PR I would
1) Include the architecture diagram and a brief description of Fabric in README.md
2) Move some of the content in INSTALL.md to CONTRIBUTING.md, such as how to add or update Go packages in the vendor director. Only a contributor would ever need to worry about that.

**Comment by joequant** [comment]
The reason for making the change is that right now the README.md file is
very, very unfriendly.  Usually a newbie will want an overview of the
project before trying to install.

I just copied README.md to INSTALL.md.   It turns out that we'd likely want
to completely rewrite INSTALL.md but that can be done later.  What I would
propose is that we copy INSTALL.md to a wiki page, and then edit that, and
then periodically sync INSTALL.md to the wiki file.

On Thu, Apr 21, 2016 at 10:15 PM, Sheehan Anderson <notifications@github.com

**Comment by binhn** [comment]
@srderson @joequant For example, the readme contains more explanation of the hyperledger project than about the fabric project, which is what this readme is supposed to describe. The hyperledger project is described in hyperledger/hyperledger, and so no reasons to repeat it here. Also the information about incubation has been described on the repo description. 
The install file repeats the incubation paragraph (why?) and contains sections on communication, contribution, etc... 

So my opinion as expressed above: Let the ID folks do this in a proper way, and we have an issue to do that in this sprint. @joequant could collaborate with @joshhus on the effort.

**Comment by joequant** [comment]
I'm planning on onboarding about a half dozen student interns this summer,
and the problem is that you need to move most of the INSTALL out of the
README and then work on the INSTALL.md separately.  Also there will be
people who are working on chaincode that will be working in alternative dev
environments.

Putting the INSTALL.md in the README is a bad idea since the information in
INSTALL is going to get very quickly out of date as the code changes and
people come up with different and alternative ways of installing the code.
For example, for the people I'm working with should completely ignore the
current install instructions since they will be working on the docker image
directly.

The readme needs to be somewhat because it's the first thing that people
see when they land on the hyperledger/fabric github site, and it's likely
that they will get here without directly seeing the hyperledger README.md.
I was asked to include the incubation information.

Yes we need to work on the INSTALL.md and the README.md, but the point of
the commit is that the installation instructions should not be in the
README.  The README should just have a list of the major resources so that
people can ask questions when the install doesn't work.  If you just put
the INSTALL inside the README, you are going to have a lot of confused
people when the follow the instructions and they don't work.

**Comment by joequant** [comment]
The other thing is that the main source of INSTALL instructions should not
be in a file at all.  The instructions that anyone with github access uses
to install should be a link to the wiki, that way people trying to install
can interactively modify/extend/edit the installation instructions.  The
only reason for an INSTALL.md file is so that who is offline and gets a
tarball can do an install.

One final thing is that friendly documentation is absolutely critical for
this to work.  The reason that fabric is getting more users than any of the
other projects is that fabric happens to be pretty well documented, whereas
the poor documentation in the other parts of hyperledger make it impossible
for a newbie to get started doing anything substantial.

The README should be a link to the major resources (what is this software
and where do you go for help).  That information is unlikely to change
quickly or become out of date.  The install documentation is likely to lag
behind the code base, and the reason that you want to link people to the
slack list is so that people on slack can tell newbies to ignore parts of
the INSTALL.md file.

**Comment by binhn** [comment]
@joequant There're no standards on readme; there're many projects where readme contains install instruction; however, I am with you on this change, just that I can't accept the current contents of either file. Our current plan to attack this is in #1125 . Please voice your opinions and contribution there.

I disagree that the install instruction be a wiki that any one can modify at any time. We need to review and moderate all changes to the fabric. If someone offered up different and improved methods, we should review and accept accordingly.

**Comment by joequant** [comment]
It's going to be an interesting culture clash between big companies and
small companies :-) :-) :-)

I run a two person trading firm here in Hong Kong selling goods to Africa
and issuing small business loans.  The philosophy of manufacturing here is
"just do it."  So you have a lot of short, agile cycles.  For this and
anything else, I'd go out of business if I went through a review process
and looked for consensus for everything.  Just do it.

Anyway.  I'll just keep a copy of the changes on my fork, and people can
merge whenever there is interest in doing it.

It's going to be cool to see development cultures clash.

**Comment by binhn** [comment]
@joequant I don't think it's culture. To me, it is just to maintain the correctness of the important information. People always have different ideas, so we need some kind of "gatekeeper" to make sure the content is appropriate.  I am asking @joshhus to reach out to you on #1125

**Comment by christo4ferris** [comment]
@joequant see PR #1253 - does this start to address your concerns?

**Comment by joshhus** [comment]
I believe the "install instructions" that we want moved to a new INSTALL.md file are basically everything (each internal link and associated content) in /fabric/README.md currently. So the plan is to: 1) copy all of that content to a new file, called /fabric/INSTALL.md; 2) remove all of it from /fabric/README.md; and 3) Add links to README.md to all of the main docs in /fabric/ and to the fabric/docs/README.md. 

I'll proceed with a joshhus/ fork to do this work; LMK if there are any changes/corrections to this plan.

**Comment by binhn** [comment]
The changes have been accommodated by https://github.com/hyperledger/fabric/pull/1341

**Pull request closed without merging**
