### PR TITLE
Update chaintool from v0.5.1 to v0.7

### PR DESCRIPTION
**Pull request by ghaskins**
Updates devenv/tools/chaintool binary with the latest release of chaintool
## Description

[Chaintool](https://github.com/ghaskins/chaintool) has been revised with numerous changes/enhancements (see change log / diffstat  appended below) since it was last merged.

Notable improvements:
- New commands
  - [chaintool proto](https://github.com/ghaskins/chaintool/tree/chaintool-0.7#chaintool-proto) - compiles the domain-specific IDL into standard .proto files
  - [chaintool inspect](https://github.com/ghaskins/chaintool/tree/chaintool-0.7#chaintool-inspect) - allows chaincode instances to be queried at runtime
- New [example clients](https://github.com/ghaskins/chaintool/tree/chaintool-0.7/examples/example02/client) and [documentation](https://github.com/ghaskins/chaintool/blob/chaintool-0.7/examples/example02/README.md).
- Support for new platform-type: system-chaincode
## Motivation and Context

Chaintool is marching toward a HIP proposal to include the source under fabric.git/tools/chaintool.  This release adds new features/enhancements/documentation that strive to make it more useful and relevant.
## How Has This Been Tested?

Currently, chaintool is still generally peripheral to the main fabric processes.  This update only affects the unit-test for the CAR platform, and no behave tests.  Therefore, 
- "make unit-test" has passed after integration.

Prior to integration, numerous manual testing has been done including running chaintool's (admittedly anemic) unit-tests, manually running through the examples and test-harnesses, etc. 

Behave, etc, shall be captured by the CI sweep.
### Changelog

83ca084 lein-release plugin: preparing 0.7 release
6b5bba4 Add arbitrary "facts" to metadata mechanism
6486f95 Add metadata link to README.md
8a949eb Update README.md
1e66c79 Update license headers
6d29fec Add a new "inspect" action to chaintool proper
fff3795 Use protobuf v3.0.0-beta-2
37778ad Add support for metadata interface
3b3e063 Cleanup whitespace damange in golang.stg
035dc54 Make codecs available generally
2c90378 Allow io/resources to be valid path specification for intf/compileintf
226dd47 Remove superfluous (println) in golang generator
421531f cljs-client: use our own Leiningen if its not available
b8c0806 Update README.md
f2cbedc Add a README.md to examples/example02
d1a7def Add basic documentation for system-chaincode platform support
a80d624 More README.md tweaks
9ede01f Add Protocol section to the README.md
9cf8124 Update README.md
e9c6022 Whitespace cleanup in example02
4c8c6d9 Move ./testdata to ./examples and update documentation
05b6303 cljs-client: Add delete-account support
87e55a6 cljs-client: Add support for make-payment
8655e73 More --help cleanup
88899e6 Remove core.async since we are not currently using it
60eeeb1 Add execution instructions to makefile output
e43f7fd Enhanced --help output
5a7799e Add support for path/name specification via command line params
cf22a5b Allow our arguments to be overridden
3638fd4 Unify the command arguments
f07065d More client enhancements
723c9f9 Make response decoding clearer
decac95 More client improvements
9ab6d38 Cljs client enhancements
60309ad Clean up cljs example
d67c86b cljs client now works
5147a23 Add a cljs client for example02
01393ef Move client into nodejs specific directory
ff36fb6 Develop the client further
7ba7533 Add a nodejs-based client for example02
ebd58eb Use base64 encoding for our parameters
0353f3c Remove superfluous error check from golang generator
3c554ee Emit function information in the comments of each proto file
995a881 Add support for proto command
e0a438c User clojure protocol abstraction for platform support
d1436e1 Rename _Stub() to proxy_()
c20069d Clean up the generated interface validation code
1356aae Rename CCInterface.Interface to CCInterface.intf
746dff8 Generalize the function decoder
c429ea7 Use the standard protobuf marshaller
4afd59c Prepare for v0.7 development
ec85b6d lein-release plugin: bumped version from 0.6.1 to 0.6.2-SNAPSHOT for next development cycle
f1f7de9 lein-release plugin: preparing 0.6.1 release
733332f Fix broken unit test
542d0c3 Prepare for v0.6.1 development
4fdf049 lein-release plugin: bumped version from 0.6 to 0.7-SNAPSHOT for next development cycle
33954ff lein-release plugin: preparing 0.6 release
ae7055f Prepare for the v0.6 release
372abac Add support for system chaincode
4cab944 Allow our package base to be passed into the code generator
47c5cdd Split out the code generator from the compiler
0ea903c Split out platform specific code into a platform specifc namespace
aab4d44 Add support for platform based conditional
592f227 Allow the platform to set the path for interface files
8bb05f5 Use a destructured map for input to compile
e563447 lein-release plugin: bumped version from 0.5.1 to 0.5.2-SNAPSHOT for next development cycle
### Diffstat

 .gitignore                                         |    2 +-
 Makefile                                           |   17 +-
 README.md                                          |  191 +-
 examples/example02/README.md                       |  158 +
 examples/example02/app/chaincode.yaml              |   18 +
 .../app/src/chaincode/chaincode_example02.go       |  152 +
 examples/example02/app/src/interfaces/appinit.cci  |   10 +
 .../org.hyperledger.chaincode.example02.cci        |   23 +
 examples/example02/client/cljs/Makefile            |   17 +
 examples/example02/client/cljs/appinit.proto       |   19 +
 .../cljs/org.hyperledger.chaincode.example02.proto |   29 +
 examples/example02/client/cljs/project.clj         |   23 +
 .../example02/client/cljs/src/example02/core.cljs  |   43 +
 .../example02/client/cljs/src/example02/main.cljs  |   98 +
 .../example02/client/cljs/src/example02/rpc.cljs   |   45 +
 examples/example02/client/nodejs/appinit.proto     |   19 +
 examples/example02/client/nodejs/index.js          |  101 +
 .../org.hyperledger.chaincode.example02.proto      |   29 +
 examples/example02/client/nodejs/package.json      |   14 +
 examples/invoker/chaincode.yaml                    |   26 +
 examples/invoker/src/chaincode/chaincode.go        |  101 +
 examples/invoker/src/interfaces/appinit.cci        |    4 +
 .../org.hyperledger.chaincode.example02.cci        |   23 +
 examples/sample_syscc/chaincode.yaml               |   29 +
 examples/sample_syscc/interfaces/appinit.cci       |   10 +
 .../org.hyperledger.chaincode.system.sample.cci    |   23 +
 examples/sample_syscc/sample_syscc.go              |  104 +
 project.clj                                        |    9 +-
 resources/generators/golang.stg                    |  194 +-
 resources/generators/proto.stg                     |    9 +-
 .../metadata/org.hyperledger.chaintool.meta.cci    |   35 +
 resources/proto/car.proto                          |   29 +-
 src/chaintool/ast.clj                              |   25 +-
 src/chaintool/build/core.clj                       |   39 +-
 src/chaintool/build/golang.clj                     |  216 --
 src/chaintool/build/interface.clj                  |   64 +-
 src/chaintool/car/abi/Car.java                     |  940 +++--
 src/chaintool/car/codecs.clj                       |   58 -
 src/chaintool/car/ls.clj                           |   25 +-
 src/chaintool/car/read.clj                         |   27 +-
 src/chaintool/car/types.clj                        |   25 +-
 src/chaintool/car/unpack.clj                       |   25 +-
 src/chaintool/car/write.clj                        |   27 +-
 src/chaintool/codecs.clj                           |   55 +
 src/chaintool/config/parser.clj                    |   25 +-
 src/chaintool/config/util.clj                      |   25 +-
 src/chaintool/core.clj                             |   51 +-
 src/chaintool/inspect/core.clj                     |  109 +
 src/chaintool/platforms/api.clj                    |   23 +
 src/chaintool/platforms/core.clj                   |   30 +
 src/chaintool/platforms/golang/core.clj            |  254 ++
 src/chaintool/platforms/golang/system.clj          |   84 +
 src/chaintool/platforms/golang/userspace.clj       |   82 +
 src/chaintool/protobuf/generate.clj                |   45 +-
 src/chaintool/subcommands/build.clj                |   27 +-
 src/chaintool/subcommands/buildcar.clj             |   27 +-
 src/chaintool/subcommands/clean.clj                |   36 +-
 src/chaintool/subcommands/inspect.clj              |   26 +
 src/chaintool/subcommands/ls.clj                   |   25 +-
 src/chaintool/subcommands/package.clj              |   46 +-
 src/chaintool/subcommands/proto.clj                |   32 +
 src/chaintool/subcommands/unpack.clj               |   25 +-
 src/chaintool/util.clj                             |   30 +-
 .../meta/OrgHyperledgerChaintoolMeta.java          | 3712 ++++++++++++++++++++
 test/chaintool/build/test_interface.clj            |   25 +-
 test/chaintool/platforms/golang/test_system.clj    |   28 +
 testdata/example02/chaincode.yaml                  |   29 -
 .../example02/src/chaincode/chaincode_example02.go |  152 -
 testdata/example02/src/interfaces/appinit.cci      |   10 -
 .../org.hyperledger.chaincode.example02.cci        |   23 -
 testdata/invoker/chaincode.yaml                    |   26 -
 testdata/invoker/src/chaincode/chaincode.go        |  101 -
 testdata/invoker/src/interfaces/appinit.cci        |    4 -
 .../org.hyperledger.chaincode.example02.cci        |   23 -
 74 files changed, 6711 insertions(+), 1554 deletions(-)
## Checklist:
- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [ ] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Gregory Haskins gregory.haskins@gmail.com

### CODE REVIEW

**Comment by srderson** [comment]
Is it possible to build the binary in make rather than put it in the repository? My concerns are
1. It greatly increases the size of the repository each time a new version is released
2. The binary is less transparent than code which is built

**Comment by ghaskins** [comment]
@srderson thats exactly the plan, I just was waiting to go through the HIP process to get the code added to ./tools/chaintool first.  I suppose if you felt this was a problem to curb sooner rather than later, we could have the make clone github.com/ghaskins/chaintool and build it from there, or something along those lines.  I am fine however you would like to do it.

**Comment by ghaskins** [comment]
@srderson It seems I might be able to use something like this:

https://help.github.com/articles/creating-releases/

to get the best of both worlds: avoid the binary bulk in-tree and yet avoid runtime compilation overhead (it takes about 45s to build right now).  I'll redo the PR with a github release + pull down rather than commit the binary.

**Comment by ghaskins** [comment]
I am going to close this for now and refactor this PR to pull the binary in from a github release URL.

**Pull request closed without merging**
