### PR TITLE
Add the busywork tool

### PR DESCRIPTION
**Pull request by bcbrock**
## Description

The busywork tool is added as tools/busywork
## Motivation and Context

The Hyperledger TSC voted to accept the busywork HIP on May 12, 2016
## How Has This Been Tested?

I have tested this code extensively in my server environment. I have also tested it in a Vagrant environment on my Macbook. 
## Checklist:

- [x ] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [ x] Either no new documentation is required by this change, OR I added new documentation
- [ x] Either no new tests are required by this change, OR I added new tests
- [ x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Bishop Brock bcbrock@us.ibm.com

### CODE REVIEW

**Comment by bcbrock** [comment]
There is a problem with the crypto micro benchmarks, I'm working to fix it now. I must have changed something after I tested it.

**Comment by ghaskins** [comment]
I am not qualified to review tcl, but considering this patch is entirely self contained within the agreed upon location, LGTM. 

If I understand your last comment @bcbrock, you are working on an additional change for this PR.  Let me know when its all clear from your perspective.

**Comment by bcbrock** [comment]
@ghaskins Yes, I am fixing an issue in the microbenchmarks, which made me realize that my "crypto" directory is poorly named. I will try to rename it as part of this patch. I'll let you know when I'm done, thanks.

**Comment by bcbrock** [comment]
@ghaskins This is ready to go now, thank you.

For the record: Some of this Tcl code has been with me for a long time. Before submitting this patch I carefully went through each file and removed things that were obviously superfluous, or things which may have had dubious parentage. I have carefully considered the origin of every procedure and I believe we have the right to contribute this code to the project.

This patch adds a script verbatim (bin/wait-for-it) that is open source, and I have included the license along with this file. 

The benchmarks directory includes some code modified from the Go language sources, and I have attributed the origin of the code and included the license (GO_LICENSE) in the benchmarks directory.

**Comment by bcbrock** [comment]
@ghaskins Thanks Greg

**Pull request merged**
