### PR TITLE
Fixes #1635

### LINKED ISSUE #1635: busywork: Correctness checking with NOOPS consensus issues
## Description

@samding01 pointed out today that **busywork** includes several correctness checking mechanisms that do not work with NOOPS consensus, because NOOPS does not require the blockchains on the different nodes to agree. This leads to several kinds of false fails. I will create a fix that does the following:
- Will disallow -checkAgreement when using NOOPS
- Will force -logUsingPeerN 0 when using NOOPS
- Will add a -noops flag for cases where the user does not use a **busywork** script to create the peer network. If using **busywork** networks the drivers know which consensus mechanism is being used from the 'network' file.

### PR DESCRIPTION
**Pull request by bcbrock**
## Description

The busywork/counters/driver is modified to work correctly with NOOPS
networks; checkAgreement is disabled, and logging (interlock) only looks at
the first peer.

Other minor enhancements:
1. checkAgreement now logs multiple peers concurrently to reduce test time
2. driver clients now all use a unique random seed

This change is limited to tools/busywork. None of the peer Go code is modified by this PR.
## Motivation and Context

Fixes #1635
## How Has This Been Tested?

I have been testing this for a few days while profiling NOOPS networks.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Bishop Brock bcbrock@us.ibm.com

### CODE REVIEW

**Comment by bcbrock** [comment]
I don't understand how my changes could cause a failure of a Behave test. Note that PR #1700 fails with the same error - I think there must be a problem with the Behave tests.

**Comment by ghaskins** [comment]
Test #680 is notoriously flaky.  I have learned to ignore the failure as meaningless, so I wouldn't be concerned if you were not changing in the areas of coverage by the test.  I can restart it for you, however.

**Comment by bcbrock** [comment]
@ghaskins - I'm sure it's not my fault, but please resubmit the CI check anyway.

**Comment by ghaskins** [comment]
@bcbrock looks fine this time

**Comment by ghaskins** [comment]
LGTM

Reviewed-by: Greg Haskins gregory.haskins@gmail.com

**Comment by bcbrock** [comment]
@ghaskins Thank you

**Comment by ghost** [comment]
Test Jenkins comment

**Pull request merged**
