### PR TITLE
Fabric docs display using mkdocs and ReadTheDocs #1674

### PR DESCRIPTION
**Pull request by rameshthoomu**
## Description

Proposal using mkdocs and ReadTheDocs open source tools to display markdown documentations of Hyperledger Fabric git repository. An account has been created in ReadTheDocs and setup has been made in github.
## Motivation and Context

Fixes #
#1674: Read the Docs hosts documentation for the open source community. After this PR merge into the fabric master branch, ReadThedocs builds the documentation for every .md file change in git repository.  This only works for Merge requests not for PR's.

The documentation type we have selected for this proposal is `mkdocs` as it supports .md files.
## How Has This Been Tested?

We have created web-hooks and sync has been tested between ReadTheDocs and Fabric git repository.
## Checklist:

- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [X] I have either added documentation to cover my changes or this change requires no new documentation.
- [X] I have either added unit tests to cover my changes or this change requires no new tests.
- [] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

The continuous integration build process will run [make checks](https://github.com/hyperledger/fabric/blob/master/Makefile#L22) to confirm that tests pass and that code quality meets minimum standards. You may optionally run this locally as PRs will not be accepted until they pass.

Signed-off-by: thoomu@us.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
Looks good. I would ask @joshhus @bramwelt @rjones-lf to review as it looks like they were involved in the issue discussion.

**Comment by joshhus** [comment]
This has been well-vetted and tested over recent weeks. I blessed the version at http://chaincode-docs.readthedocs.io/en/latest/ and am confident this result will be equivalent. Note the "final" external URL will be: hyperledger-fabric.readthedocs. (.io)  ... (Note this is a display-only Issue / PR. No issues with content (words) are addressed by this PR.)

**Comment by srderson** [comment]
Thanks for the details @joshhus. Only thing I noticed is at http://hyperledger-fabric.readthedocs.io/en/latest/?badge=latest is currently giving a "page not found" message, but @rameshthoomu says the page will be there after I merge this PR. About to give it a try :) LGTM

**Comment by srderson** [comment]
Still an issue with the link :( @rameshthoomu is investigating now.

**Pull request merged**
