### PR TITLE
Update paths in SandboxSetup.md

### PR DESCRIPTION
**Pull request by iamsamwood**
Minor edits to documentation to reflect latest paths.

### CODE REVIEW

**Comment by ghaskins** [comment]
Hello Sam,

Thank you for the patch.  However, I am afraid I have to NACK this as the paths were correct as they were as of 4c3bd9faf.  Please let me know if you still think they are incorrect.

**Comment by iamsamwood** [comment]
My mistake, i see this was fixed. Thanks.

**Comment by iamsamwood** [comment]
Actually this does not work by default in the devenv. If I update my path then it does:

export PATH="$PATH:/opt/gopath/src/github.com/hyperledger/fabric/build/bin"

**Comment by ghaskins** [comment]
I suspect you need to rebuild your vagrant environment.  https://github.com/hyperledger/fabric/commit/871fa50fc86a81ae12a0a423a37d109bf503271e went in 18 days ago that adds ./build/bin to the $PATH, but if you haven't performed a vagrant destroy/up cycle you wouldn't have picked this up.   You can confirm which commit was used to build your environment by looking at your prompt:

```
vagrant@hyperledger-devenv:v0.0.10-c358b79:/opt/gopath/src/github.com/hyperledger/fabric$
```

(note the c358b79)

**Pull request closed without merging**
